#!/usr/bin/env python3
"""
make_mumford.py

One plate for the first Hodge classes beyond the Weil lines.

  fig_mumford    the weight two cohomology of an abelian fourfold of Mumford
                 type, drawn over the triangle of the three factors of its
                 Hodge group.  At the corners stand the three summands
                 T_i = sl(V_i) of T = Lie G, each of dimension three, as
                 prisms banded by Hodge type after the twist: T_1 and T_2
                 entirely of type (1,1), T_3 of types (2,0), (1,1), (0,2).
                 On the edges stand the three summands U_ij of the primitive
                 part U of H^2(X), each of dimension nine: U_12 of pure type
                 (1,1), U_13 and U_23 in three bands of three.  In the middle
                 is the line of the polarisation.  The arcs are the map mu:
                 T_i (x) T_j onto U_ij, and T_i (x) T_i onto the line of
                 theta.  The violet arcs between the three U_ij are the action of
                 the Galois group, which permutes them as it permutes the
                 embeddings of the cubic field F, so that F acts on U_ij by
                 sigma_k.  Above, a K3 surface S_lambda carries T with the form
                 q_lambda, and the Kuga-Satake map kappa, multiplication by an
                 element e of F on T, comes down to the triangle.

All heights are the dimensions, one unit per dimension; the positions of the
seven summands are schematic, their incidences exact.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_mumford.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"

H = 0.19          # height of one dimension
TW = 0.62         # footprint of a T prism
WW = 0.78         # footprint of a W prism
TYPE = {"20": "PClay", "11": "PBlue", "02": "PAmber"}


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def stack(sc, x, y, w, bands):
    """a prism of footprint w at (x, y), built from bands (type, dim) from
    the bottom up; returns the top point"""
    z = 0.0
    for t, d in bands:
        if d == 0:
            continue
        h = d * H
        sc.box((x, y, z + h / 2.0), (w, w, h), base=TYPE[t], opacity=0.80,
               ambient=0.44, diffuse=0.46,
               edge_style="%s!75!black,line width=0.3pt" % TYPE[t])
        z += h
    return (x, y, z)


def arc(a, b, lift, n=40):
    pts = []
    for k in range(n + 1):
        t = k / float(n)
        pts.append((a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t,
                    a[2] + (b[2] - a[2]) * t + lift * math.sin(math.pi * t)))
    return pts


def fig_mumford():
    cam = Camera(eye=(3.6, -9.4, 10.2), target=(0.0, 0.35, 1.30), focal=10.6,
                 scale=2.45)
    sc, P = Scene(cam), Placer()

    # the ground plate, ruled
    x0, x1, y0, y1 = -3.4, 3.4, -2.35, 3.0
    sc.surface(lambda u, v: (u, v, 0.0), (x0, x1), (y0, y1), 12, 9,
               base="PSlate", opacity=0.10, ambient=0.74, diffuse=0.16)
    for k in range(13):
        x = x0 + (x1 - x0) * k / 12
        sc.polyline([(x, y0, 0), (x, y1, 0)], "PRule!50,line width=0.15pt",
                    priority=1)
    for k in range(11):
        y = y0 + (y1 - y0) * k / 10
        sc.polyline([(x0, y, 0), (x1, y, 0)], "PRule!50,line width=0.15pt",
                    priority=1)

    # the triangle of the three factors
    T = {1: (-2.55, -1.35), 2: (2.55, -1.35), 3: (0.0, 2.35)}
    sc.polyline([T[1] + (0.0,), T[2] + (0.0,), T[3] + (0.0,), T[1] + (0.0,)],
                "PInk!45,line width=0.5pt,dash pattern=on 2pt off 1.6pt",
                priority=1)
    tops = {}
    tops[1] = stack(sc, T[1][0], T[1][1], TW, [("11", 3)])
    tops[2] = stack(sc, T[2][0], T[2][1], TW, [("11", 3)])
    tops[3] = stack(sc, T[3][0], T[3][1], TW,
                    [("02", 1), ("11", 1), ("20", 1)])

    sc.polyline([tops[1], tops[2], tops[3], tops[1]],
                "PBlue!70,line width=0.45pt,dash pattern=on 1.4pt off 1.2pt",
                priority=3)

    # the three U_ij on the edges, pushed outward from the centre
    cx, cy = 0.0, (T[1][1] + T[2][1] + T[3][1]) / 3.0
    W = {}
    for (i, j) in ((1, 2), (1, 3), (2, 3)):
        mx = 0.5 * (T[i][0] + T[j][0])
        my = 0.5 * (T[i][1] + T[j][1])
        dx, dy = mx - cx, my - cy
        r = math.hypot(dx, dy)
        W[(i, j)] = (mx + 0.62 * dx / r, my + 0.62 * dy / r)
    wtop = {}
    wtop[(1, 2)] = stack(sc, W[(1, 2)][0], W[(1, 2)][1], WW, [("11", 9)])
    for key in ((1, 3), (2, 3)):
        wtop[key] = stack(sc, W[key][0], W[key][1], WW,
                          [("02", 3), ("11", 3), ("20", 3)])

    # the line of theta
    th = stack(sc, cx, cy, 0.42, [("11", 1)])

    # mu: T_i (x) T_j onto U_ij, and T_i (x) T_i onto theta
    for (i, j), wt in wtop.items():
        for s in (i, j):
            a = tops[s]
            dx, dy = a[0] - wt[0], a[1] - wt[1]
            r = math.hypot(dx, dy)
            b = (wt[0] + 0.22 * dx / r, wt[1] + 0.22 * dy / r, wt[2] + 0.02)
            sc.arrow(arc(a, b, 0.55), "PInk!80,line width=0.75pt", priority=5)
    for s in (1, 2, 3):
        a = tops[s]
        sc.arrow(arc(a, (th[0], th[1], th[2] + 0.02), 0.35),
                 "PSlate,line width=0.55pt,dash pattern=on 1.6pt off 1.4pt",
                 priority=4)

    # the Galois group permutes the three U_ij: arcs between their tops
    gal_mid = None
    for (p_, q_) in (((1, 2), (2, 3)), ((2, 3), (1, 3)), ((1, 3), (1, 2))):
        a0, b0 = wtop[p_], wtop[q_]
        pts = arc((a0[0], a0[1], a0[2] + 0.08), (b0[0], b0[1], b0[2] + 0.08),
                  0.75)
        sc.arrow(pts[3:-3], "PViolet,line width=0.8pt,"
                 "dash pattern=on 3pt off 1.5pt", priority=4)
        if p_ == (1, 3):
            gal_mid = pts[20]
    zr = 9 * H + 0.55

    # the K3 surface above, and the Kuga-Satake map coming down
    zs = zr + 1.75

    def k3(u, v):
        return (u, 0.55 * v + 0.35,
                zs + 0.16 * math.sin(1.7 * u) * math.cos(2.1 * v)
                + 0.05 * u)
    sc.surface(k3, (-1.7, 1.7), (-1.0, 1.0), 22, 12, base="PTeal",
               opacity=0.70, ambient=0.46, diffuse=0.44)
    for k in range(7):
        u = -1.7 + 3.4 * k / 6
        sc.curve(lambda v, u=u: k3(u, v), (-1.0, 1.0), 12,
                 "PTeal!70!black,line width=0.2pt", priority=2, chunk=3)
    for k in range(5):
        v = -1.0 + 2.0 * k / 4
        sc.curve(lambda u, v=v: k3(u, v), (-1.7, 1.7), 20,
                 "PTeal!70!black,line width=0.2pt", priority=2, chunk=4)
    top_k3 = k3(0.0, 0.0)
    kap_mid = (0.0, 0.5 * (0.35 + cy), 0.5 * (zs + 3 * H) + 0.2)
    tcen = (0.0, cy, 3 * H + 0.03)
    sc.dot3(tcen, "circle,fill=PTeal!80!black,draw=white,line width=0.5pt,"
            "inner sep=1.4pt", priority=7)
    sc.arrow([(top_k3[0], top_k3[1], top_k3[2] - 0.05), kap_mid,
              (tcen[0], tcen[1], tcen[2] + 0.06)],
             "PTeal!80!black,line width=1.3pt", priority=6)

    P.add(k3(-1.7, 1.0), r"$S_{\lambda}$, Picard number $13$, $T(S_{\lambda})\cong(T,q_{\lambda})$", "text=PTeal!80!black", side="L")
    P.add(kap_mid, r"$\kappa=m_{e}$, from the Kuga--Satake class",
          "text=PTeal!80!black", side="R")
    P.add(gal_mid, r"Galois: $a\in F$ acts on $U_{ij}$ by $\sigma_{k}(a)$", "text=PViolet",
          side="L")
    P.add(wtop[(1, 3)], r"$U_{13}$: $(3,3,3)$", "text=PInk",
          side="L")
    P.add(tops[1], r"$T_{1}=\mathfrak{sl}(V_{1})$: $(0,3,0)$", "text=PBlue",
          side="L")
    P.add(tops[3], r"$T_{3}=\mathfrak{sl}(V_{3})$: $(1,1,1)$", "text=PClay",
          side="R")
    P.add(wtop[(2, 3)], r"$U_{23}$: $(3,3,3)$", "text=PInk", side="R")
    P.add(wtop[(1, 2)], r"$U_{12}$: $(0,9,0)$",
          "text=PBlue", side="R")
    P.add(tops[2], r"$T_{2}=\mathfrak{sl}(V_{2})$: $(0,3,0)$", "text=PBlue",
          side="R")
    P.add(th, r"$\QQ\theta=\mu(T_{i}\otimes T_{i})$", "text=PSlate",
          side="L")
    mid12 = arc(tops[1], wtop[(1, 2)], 0.55)[20]
    P.add(mid12, r"$\mu(T_{i}\otimes T_{j})=U_{ij}$",
          "text=PInk", side="L")

    write("fig_mumford",
          "The weight two cohomology of a Mumford fourfold over the triangle "
          "of the three factors, with the map mu, the Galois arcs and the K3 "
          "surface above.", sc, P)


if __name__ == "__main__":
    fig_mumford()
