#!/usr/bin/env python3
"""
make_diagrams.py

Three plates that carry numbers rather than geometry, drawn in three
dimensions so that the numbers can be read against one another, and the
label placement used by every plate of make_diagrams.py, make_more.py,
make_secant.py and make_smooth.py.

  fig_ladder     the Lefschetz decomposition of the cohomology of an abelian
                 fourfold: the Betti numbers binom(8,k) as prisms, each
                 stacked from the pieces L^i P^j, with P^j = H^j_prim of
                 dimension binom(8,j) - binom(8,j-2).  Stacked by j, the
                 translates L^i P^j of one primitive piece sit at the same
                 height in the degrees j, j+2, ..., 8-j, so the sl_2 strings
                 are the horizontal bands of the plate; the hard Lefschetz
                 isomorphisms L^{4-k} : H^k -> H^{8-k} are the nested half
                 ellipses, each clear of every prism it passes over.  P^k
                 is dark, its translates light in the same colour.  Under
                 the prisms the same decomposition as a table, one row for
                 each sl_2 string, above the Betti numbers, and brackets
                 for what restriction j^* to a smooth ample hypersurface
                 does: injective in degrees k < 4, zero on P^4, and
                 H^k = L^{k-4} H^{8-k} for k > 4.

  fig_moduli     for n = 1..6, a stacked prism of height n(2n+1), the
                 dimension of the moduli of principally polarised abelian
                 2n-folds, split into the Weil family of dimension n^2 and
                 its codimension n(n+1); braces on the last prism name the
                 parts, and a table under the prisms gives the numbers.

  fig_signature  the signatures (p,q) of an imaginary quadratic action, with
                 p + q = dim A, on the saddle z = pq, which is the dimension
                 of the family of abelian varieties with that action.  The
                 curves p + q = 2n collect the signatures available in one
                 dimension; the ridge p = q is where the Weil line consists
                 of Hodge classes, and on each curve it is the highest point.
                 A key under the plate says what the filled and the open
                 points are.

All heights are the actual numbers, times one scale per figure.  The two bar
plates use the parallel oblique projection of class Oblique, in which the
front faces of the prisms are true rectangles and every horizontal line is
horizontal: each prism stands on the zero line, fills the depth of the frame,
and its top meets the gridline of its height on the back wall and the tick of
its height on the scale.  fig_signature uses the perspective camera of
render3d.py.

Label placement (class Plate).  The geometry of a plate is compiled once
without labels and rendered to a grey bitmap; every label is typeset by TeX
to measure its box, and is then put at the nearest position, around its
anchor, whose box meets no ink of the bitmap, no other label, no leader line,
and none of the boxes that figures/checkfigs.py estimates for the other
labels.  A label that cannot sit next to its anchor gets a thin leader, and a
leader may cross a shaded surface but never a drawn line, a dot or a label.
Labels at fixed positions (ticks, axis names) are checked in the same way.
"""
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from math import comb

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from render3d import Camera, Scene                              # noqa: E402
from checkfigs import box as cf_box                              # noqa: E402

PT = 2.54 / 72.27            # one TeX point in cm
BORDER = 8 * PT              # the standalone border
DPI = 127                    # 0.02 cm per pixel in the draft bitmaps
PX = 2.54 / DPI

HEAD = r"""%% {name}.tex   (generated by {gen}; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"
TIP = "-{Stealth[length=4.2pt,width=3.4pt]}"

COORD = re.compile(r'\(\s*(-?\d+\.?\d*)\s*,\s*(-?\d+\.?\d*)\s*\)')
MEAS = re.compile(r'MEAS (\d+) (-?[\d.]+)pt (-?[\d.]+)pt (-?[\d.]+)pt')


def ink_bbox(body):
    xs, ys = [], []
    for a, b in COORD.findall(body):
        xs.append(float(a))
        ys.append(float(b))
    return min(xs), min(ys), max(xs), max(ys)


def soften(body):
    """Turn every stroke drawn with the style prefix 'soft,' into a path
    that a leader may cross (light rulings and hatching), and drop the
    prefix."""
    return re.sub(r'\\draw\[soft,([^,\]]+)', r'\\path[draw=\1', body)


def orbit_eye(target, dist, az, el):
    """An eye at distance dist from target, azimuth az and elevation el in
    degrees; a far eye with a long focal length is nearly orthographic."""
    a, e = math.radians(az), math.radians(el)
    return (target[0] + dist * math.cos(e) * math.cos(a),
            target[1] + dist * math.cos(e) * math.sin(a),
            target[2] + dist * math.sin(e))


def strokes_only(body):
    """The body without its shaded fills: what a leader may not cross."""
    keep = []
    for ln in body.splitlines(True):
        s = ln.lstrip()
        if s.startswith("\\path[") or s.startswith("\\fill["):
            continue
        keep.append(ln)
    return "".join(keep)


def _read_pgm(path):
    data = open(path, "rb").read()
    tok, i = [], 0
    while len(tok) < 4:
        while data[i:i + 1].isspace():
            i += 1
        if data[i:i + 1] == b"#":
            while data[i:i + 1] != b"\n":
                i += 1
            continue
        j = i
        while not data[j:j + 1].isspace():
            j += 1
        tok.append(data[i:j])
        i = j
    i += 1
    w, h = int(tok[1]), int(tok[2])
    return np.frombuffer(data[i:i + w * h], dtype=np.uint8).reshape(h, w)


def _seg_hits_box(p, q, b):
    """Does the segment pq meet the axis-parallel box b = (x0,y0,x1,y1)?"""
    x0, y0, x1, y1 = b
    t0, t1 = 0.0, 1.0
    dx, dy = q[0] - p[0], q[1] - p[1]
    for pp, qq in ((-dx, p[0] - x0), (dx, x1 - p[0]),
                   (-dy, p[1] - y0), (dy, y1 - p[1])):
        if abs(pp) < 1e-12:
            if qq < 0:
                return False
        else:
            t = qq / pp
            if pp < 0:
                t0 = max(t0, t)
            else:
                t1 = min(t1, t)
            if t0 > t1:
                return False
    return True


def _segs_cross(a, b, c, d):
    def orient(p, q, r):
        return (q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0])
    o1, o2 = orient(a, b, c), orient(a, b, d)
    o3, o4 = orient(c, d, a), orient(c, d, b)
    return (o1 * o2 < 0) and (o3 * o4 < 0)


def _meet(a, b, pad=0.0):
    return (a[0] - pad < b[2] and b[0] - pad < a[2] and
            a[1] - pad < b[3] and b[1] - pad < a[3])


LOOSE = bool(os.environ.get("PLATE_LOOSE"))


def fail(msg):
    """A placement failure stops the build, unless PLATE_LOOSE is set, when
    it is reported and the plate is written anyway for inspection."""
    if LOOSE:
        print("  WARNING " + msg)
    else:
        raise SystemExit(msg)


class Plate:
    """A figure: TikZ geometry plus labels placed clear of it."""

    def __init__(self, name, gen, blurb, thresh=236, sthresh=246,
                 pad=0.05, gap=0.07):
        self.name, self.gen, self.blurb = name, gen, blurb
        self.parts = []
        self.fixed = []
        self.movable = []
        self.thresh = thresh      # grey level below which a pixel is ink
        self.sthresh = sthresh    # the same for the strokes a leader avoids
        self.pad = pad            # clear margin around a label box
        self.gap = gap            # minimum clearance between two labels

    # ------------------------------------------------------------ input
    def add(self, tikz):
        self.parts.append(tikz)

    def put(self, x, y, text, color="PInk", font=r"\small", extra="",
            anchor="c"):
        """A label at a fixed position; anchor is one of c, w, e, n, s and
        says which point of the box is at (x, y)."""
        self.fixed.append(dict(x=x, y=y, text=text, color=color, font=font,
                               extra=extra, anchor=anchor))

    def label(self, at, text, color="PInk", font=r"\small", dirs=None,
              rmin=0.04, rmax=3.5, lead=0.26, skip=0.10, frame=None,
              penalty=0.9):
        """A label near the point `at`; dirs lists preferred directions in
        degrees (0 = east, 90 = north)."""
        self.movable.append(dict(ax=at[0], ay=at[1], text=text, color=color,
                                 font=font, dirs=dirs, rmin=rmin, rmax=rmax,
                                 lead=lead, skip=skip, frame=frame,
                                 penalty=penalty, extra=""))

    # ---------------------------------------------------------- helpers
    @staticmethod
    def _spec(it):
        ex = ",align=center" if "\\\\" in it["text"] else ""
        return "text=%s,font=%s,inner sep=0pt%s%s" % (
            it["color"], it["font"], ex,
            ("," + it["extra"]) if it["extra"] else "")

    @staticmethod
    def _node(it, x, y):
        return "  \\node[%s] at (%.3f,%.3f) {%s};\n" % (Plate._spec(it), x, y,
                                                        it["text"])

    def _compile(self, tex, tmp, stem):
        with open(os.path.join(tmp, stem + ".tex"), "w") as f:
            f.write(tex)
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                            "-halt-on-error", stem + ".tex"], cwd=tmp,
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stdout.write(r.stdout[-3000:])
            raise SystemExit("pdflatex failed on the draft of %s" % self.name)
        return r.stdout

    def _render(self, tmp, stem):
        subprocess.run(["pdftoppm", "-gray", "-r", str(DPI), "-singlefile",
                        stem + ".pdf", stem], cwd=tmp, check=True)
        return _read_pgm(os.path.join(tmp, stem + ".pgm"))

    # ------------------------------------------------------------ build
    def build(self):
        body = "".join(self.parts)
        bx0, by0, bx1, by1 = ink_bbox(body)
        M = 5.0
        X0, Y0, X1, Y1 = bx0 - M, by0 - M, bx1 + M, by1 + M
        ubox = "  \\useasboundingbox (%.3f,%.3f) rectangle (%.3f,%.3f);\n" % (
            X0, Y0, X1, Y1)
        items = self.fixed + self.movable
        meas = []
        for i, it in enumerate(items):
            t = it["text"]
            if "\\\\" in t:
                t = "\\begin{tabular}{@{}c@{}}%s\\end{tabular}" % t
            meas.append("  \\pgfinterruptpicture\\setbox0\\hbox{%s %s}"
                        "\\typeout{MEAS %d \\the\\wd0 \\space\\the\\ht0 "
                        "\\space\\the\\dp0 }\\endpgfinterruptpicture\n"
                        % (it["font"], t, i))
        head = HEAD.format(name=self.name, gen=self.gen, blurb=self.blurb)
        tmp = tempfile.mkdtemp(prefix="plate_")
        try:
            shutil.copy(os.path.join(HERE, "palette.tex"), tmp)
            log = self._compile(head + ubox + body + "".join(meas) + TAIL,
                                tmp, "draft")
            sizes = {}
            for m in MEAS.finditer(log):
                i = int(m.group(1))
                w = float(m.group(2)) * PT
                h = (float(m.group(3)) + float(m.group(4))) * PT
                sizes[i] = (w, h)
            for i, it in enumerate(items):
                w, h = sizes[i]
                if "rotate=90" in it["extra"]:
                    w, h = h, w
                it["w"], it["h"] = w, h
                a = it.get("anchor", "c")
                it["x"] = it.get("x", 0) + {"w": w / 2, "e": -w / 2}.get(a, 0)
                it["y"] = it.get("y", 0) + {"s": h / 2, "n": -h / 2}.get(a, 0)
            full = self._render(tmp, "draft")
            self._compile(head + ubox + strokes_only(body) + TAIL, tmp,
                          "strokes")
            strk = self._render(tmp, "strokes")
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

        H, W = full.shape
        ink = (full < self.thresh).astype(np.int32)
        S = np.zeros((H + 1, W + 1), dtype=np.int64)
        S[1:, 1:] = ink.cumsum(0).cumsum(1)
        sink = strk < self.sthresh
        ox, oy = X0 - BORDER, Y1 + BORDER

        def box_ink(b):
            c0 = int(math.floor((b[0] - ox) / PX))
            c1 = int(math.ceil((b[2] - ox) / PX))
            r0 = int(math.floor((oy - b[3]) / PX))
            r1 = int(math.ceil((oy - b[1]) / PX))
            if c0 < 0 or r0 < 0 or c1 > W or r1 > H:
                return 10 ** 6
            return int(S[r1, c1] - S[r0, c1] - S[r1, c0] + S[r0, c0])

        def pix_stroke(x, y):
            c = int((x - ox) / PX)
            r = int((oy - y) / PX)
            if c < 1 or r < 1 or c >= W - 1 or r >= H - 1:
                return True
            return bool(sink[r - 1:r + 2, c - 1:c + 2].any())

        placed = []        # (real box, cf box, text)
        leaders = []       # (p, q)
        pad, gap = self.pad, self.gap

        def clear_of_labels(rb, cb):
            for (pb, pc, _) in placed:
                if _meet(rb, pb, gap) or _meet(cb, pc, 0.0):
                    return False
            return True

        # the fixed labels first: they must be clear as given
        for it in self.fixed:
            x, y, w, h = it["x"], it["y"], it["w"], it["h"]
            rb = (x - w / 2, y - h / 2, x + w / 2, y + h / 2)
            cb = cf_box(self._spec(it), x, y, it["text"])[:4]
            n = box_ink((rb[0] - pad, rb[1] - pad, rb[2] + pad, rb[3] + pad))
            if n:
                fail("%s: fixed label %r meets the ink (%d px)"
                     % (self.name, it["text"], n))
            if not clear_of_labels(rb, cb):
                fail("%s: fixed label %r meets another label"
                     % (self.name, it["text"]))
            placed.append((rb, cb, it["text"]))

        out_lead, out_node = [], []
        for it in self.fixed:
            out_node.append(self._node(it, it["x"], it["y"]))

        for it in self.movable:
            ax, ay, w, h = it["ax"], it["ay"], it["w"], it["h"]
            cands = []
            pref = it["dirs"]
            for k in range(32):
                th = 11.25 * k
                if pref is None:
                    pen = 0.15 * abs(math.sin(math.radians(th)))
                else:
                    dd = min(min(abs(th - p) % 360, 360 - abs(th - p) % 360)
                             for p in pref)
                    pen = 0.0 if dd < 1e-6 else it["penalty"] * (0.5 + dd / 180.0)
                ux, uy = math.cos(math.radians(th)), math.sin(math.radians(th))
                s = abs(ux) * w / 2 + abs(uy) * h / 2
                r = it["rmin"]
                while r <= it["rmax"] + 1e-9:
                    cands.append((r + pen, r, ux, uy, s))
                    r += 0.03
            cands.sort()
            done = False
            for score, r, ux, uy, s in cands:
                cx, cy = ax + (r + s) * ux, ay + (r + s) * uy
                rb = (cx - w / 2, cy - h / 2, cx + w / 2, cy + h / 2)
                fr = it["frame"]
                if fr and (rb[0] < fr[0] or rb[1] < fr[1] or rb[2] > fr[2]
                           or rb[3] > fr[3]):
                    continue
                if box_ink((rb[0] - pad, rb[1] - pad, rb[2] + pad,
                            rb[3] + pad)):
                    continue
                cb = cf_box(self._spec(it), cx, cy, it["text"])[:4]
                if not clear_of_labels(rb, cb):
                    continue
                grown = (rb[0] - pad, rb[1] - pad, rb[2] + pad, rb[3] + pad)
                if any(_seg_hits_box(p, q, grown) for p, q in leaders):
                    continue
                seg = None
                if r > it["lead"]:
                    # exit point of the ray from the centre towards the anchor
                    tx = (w / 2 + 0.05) / abs(ux) if abs(ux) > 1e-9 else 1e9
                    ty = (h / 2 + 0.05) / abs(uy) if abs(uy) > 1e-9 else 1e9
                    te = min(tx, ty)
                    B = (cx - te * ux, cy - te * uy)
                    A = (ax + 0.05 * ux, ay + 0.05 * uy)
                    L = math.hypot(B[0] - A[0], B[1] - A[1])
                    ok = L > 0.05
                    n = max(2, int(L / 0.015))
                    for q in range(n + 1):
                        t = q / n
                        x = A[0] + (B[0] - A[0]) * t
                        y = A[1] + (B[1] - A[1]) * t
                        if math.hypot(x - ax, y - ay) < it["skip"]:
                            continue
                        if pix_stroke(x, y):
                            ok = False
                            break
                    if not ok:
                        continue
                    if any(_seg_hits_box(A, B, (pb[0] - pad, pb[1] - pad,
                                                pb[2] + pad, pb[3] + pad))
                           for (pb, _, _) in placed):
                        continue
                    if any(_segs_cross(A, B, p, q) for p, q in leaders):
                        continue
                    seg = (A, B)
                placed.append((rb, cb, it["text"]))
                if seg:
                    leaders.append(seg)
                    out_lead.append("  \\draw[PSlate!60,line width=0.3pt] "
                                    "(%.3f,%.3f) -- (%.3f,%.3f);\n"
                                    % (seg[0][0], seg[0][1], seg[1][0],
                                       seg[1][1]))
                out_node.append(self._node(it, cx, cy))
                done = True
                break
            if not done:
                fail("%s: no clear position for label %r"
                     % (self.name, it["text"]))

        # the checkfigs estimate, over every text node of the plate
        cfs = [p[1] for p in placed]
        for i, a in enumerate(cfs):
            for b in cfs[i + 1:]:
                if _meet(a, b):
                    fail("%s: checkfigs boxes meet" % self.name)

        tex = head + body + "".join(out_lead) + "".join(out_node) + TAIL
        path = os.path.join(HERE, self.name + ".tex")
        with open(path, "w") as f:
            f.write(tex)
        allx = [p[0][0] for p in placed] + [p[0][2] for p in placed] + [bx0, bx1]
        ally = [p[0][1] for p in placed] + [p[0][3] for p in placed] + [by0, by1]
        print("%-16s %2d labels (%d with leaders), about %.1f x %.1f cm"
              % (self.name, len(placed), len(leaders),
                 max(allx) - min(allx), max(ally) - min(ally)))
        return tex


def compile_plate(name):
    """pdflatex, the 200 dpi PNG, and the cleanup, in the figures folder."""
    r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                        "-halt-on-error", name + ".tex"], cwd=HERE,
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stdout.write(r.stdout[-3000:])
        raise SystemExit("pdflatex failed on %s" % name)
    subprocess.run(["pdftoppm", "-png", "-r", "200", "-singlefile",
                    name + ".pdf", name], cwd=HERE, check=True)
    for ext in (".aux", ".log"):
        try:
            os.remove(os.path.join(HERE, name + ext))
        except OSError:
            pass


# ---------------------------------------------------------------- 2D plots
class Axes2D:
    """A rectangular plot frame at (x0, y0) of size w x h cm showing the data
    window xr x yr; ticks and tick labels are fixed labels of the plate."""

    def __init__(self, pl, x0, y0, w, h, xr, yr, ylog=False):
        self.pl, self.x0, self.y0, self.w, self.h = pl, x0, y0, w, h
        self.xr, self.yr, self.ylog = xr, yr, ylog

    def X(self, x):
        return self.x0 + self.w * (x - self.xr[0]) / (self.xr[1] - self.xr[0])

    def Y(self, y):
        if self.ylog:
            y = math.log10(y)
        return self.y0 + self.h * (y - self.yr[0]) / (self.yr[1] - self.yr[0])

    def P(self, x, y):
        return (self.X(x), self.Y(y))

    def frame(self, xticks, yticks, xfmt=None, yfmt=None, grid=True,
              font=r"\footnotesize"):
        pl = self.pl
        x0, y0, x1, y1 = self.x0, self.y0, self.x0 + self.w, self.y0 + self.h
        if grid:
            for t in yticks:
                y = self.Y(t)
                pl.add("  \\draw[PRule!45,line width=0.25pt] (%.3f,%.3f) -- "
                       "(%.3f,%.3f);\n" % (x0, y, x1, y))
        pl.add("  \\draw[PSlate,line width=0.45pt] (%.3f,%.3f) -- (%.3f,%.3f) "
               "-- (%.3f,%.3f);\n" % (x0, y1, x0, y0, x1, y0))
        for t in xticks:
            x = self.X(t)
            pl.add("  \\draw[PSlate,line width=0.45pt] (%.3f,%.3f) -- "
                   "(%.3f,%.3f);\n" % (x, y0, x, y0 - 0.08))
            txt = (xfmt or (lambda v: "$%g$" % v))(t)
            if txt:
                pl.put(x, y0 - 0.19, txt, color="PSlate", font=font,
                       anchor="n")
        for t in yticks:
            y = self.Y(t)
            pl.add("  \\draw[PSlate,line width=0.45pt] (%.3f,%.3f) -- "
                   "(%.3f,%.3f);\n" % (x0, y, x0 - 0.08, y))
            txt = (yfmt or (lambda v: "$%g$" % v))(t)
            if txt:
                pl.put(x0 - 0.19, y, txt, color="PSlate", font=font,
                       anchor="e")


# ---------------------------------------------------------------- 3D bits
def proj(cam, p):
    return cam.project(p)[0]


def ground(sc, x0, x1, y0, y1, nx, ny, z=0.0, op=0.10):
    sc.surface(lambda u, v: (u, v, z), (x0, x1), (y0, y1), nx, ny,
               base="PSlate", opacity=op, ambient=0.74, diffuse=0.16)
    for k in range(nx + 1):
        x = x0 + (x1 - x0) * k / nx
        sc.polyline([(x, y0, z), (x, y1, z)], "PRule!55,line width=0.2pt",
                    priority=1)
    for k in range(ny + 1):
        y = y0 + (y1 - y0) * k / ny
        sc.polyline([(x0, y, z), (x1, y, z)], "PRule!55,line width=0.2pt",
                    priority=1)


def wall(sc, x0, x1, y, z0, z1, levels, hs):
    """A back wall at depth y with gridlines at the given levels."""
    sc.surface(lambda u, v: (u, y, v), (x0, x1), (z0, z1), 1, 1,
               base="PSlate", opacity=0.06, ambient=0.80, diffuse=0.10)
    for v in levels:
        sc.polyline([(x0, y, v * hs), (x1, y, v * hs)],
                    "PRule!80,line width=0.25pt", priority=1)
    sc.polyline([(x0, y, z0), (x0, y, z1)], "PSlate!70,line width=0.4pt",
                priority=1)


# ------------------------------------------------------- bar charts in 3D
# The bar plates (fig_ladder, fig_moduli) are drawn in explicit layers
# rather than through the depth sort of render3d: first the frame (floor,
# back wall, side wall and their gridlines), then the prisms from the far
# one to the near one, each with back-face culling, so that a gridline can
# never be drawn across a bar.  The prisms fill the whole depth of the
# frame: their back faces lie in the back wall and their front faces in the
# plane of the scale, so the top of a prism meets the gridline of its
# height on the wall and the tick of its height on the scale.

class Oblique:
    """A parallel oblique projection: x to the right and z up at true scale,
    y receding at the angle `ang` (degrees) and foreshortened by `k`.  The
    front faces of the prisms are then true rectangles and every horizontal
    line of the frame is horizontal, so a height can be read off exactly.
    `toward` is the direction from the scene to the viewer, used to cull
    the faces turned away."""

    def __init__(self, ang=38.0, k=0.55, scale=1.0, origin=(0.0, 0.0)):
        a = math.radians(ang)
        self.cx, self.cy = k * math.cos(a), k * math.sin(a)
        self.scale = scale
        self.origin = origin
        self.toward = (self.cx, -1.0, self.cy)

    def project(self, p):
        s = self.scale
        return ((s * (p[0] + self.cx * p[1]) + self.origin[0],
                 s * (p[2] + self.cy * p[1]) + self.origin[1]), p[1])


def pp(cam, p):
    x, y = cam.project(p)[0]
    return "(%.4f,%.4f)" % (x, y)


def tk_poly(cam, pts, style):
    return "  \\path[%s] %s -- cycle;\n" % (style, " -- ".join(pp(cam, p)
                                                               for p in pts))


def tk_line(cam, pts, style):
    return "  \\draw[%s] %s;\n" % (style, " -- ".join(pp(cam, p) for p in pts))


def tk_line2(pts, style):
    return "  \\draw[%s] %s;\n" % (style, " -- ".join("(%.4f,%.4f)" % p
                                                       for p in pts))


# the flat shading of a prism: front face, top face (lit), side face (shade)
SHADE = {"dark": ("{0}!80", "{0}!56", "{0}!80!white!80!black",
                  "{0}!55!black", "0.4pt"),
         "light": ("{0}!24", "{0}!13", "{0}!24!white!90!black",
                   "{0}!75!black", "0.3pt")}


def prism(cam, box, col, tone, top=True):
    """The visible faces of the box (x0, x1, y0, y1, z0, z1), flat shaded
    and outlined; top=False leaves out the top face, when another prism is
    stacked on it."""
    x0, x1, y0, y1, z0, z1 = box
    front, lit, side, edge, lw = [s.format(col) if "{" in s else s
                                  for s in SHADE[tone]]
    faces = [((0, -1, 0), [(x0, y0, z0), (x1, y0, z0), (x1, y0, z1),
                           (x0, y0, z1)], front),
             ((0, 1, 0), [(x0, y1, z0), (x1, y1, z0), (x1, y1, z1),
                          (x0, y1, z1)], front),
             ((-1, 0, 0), [(x0, y0, z0), (x0, y1, z0), (x0, y1, z1),
                           (x0, y0, z1)], side),
             ((1, 0, 0), [(x1, y0, z0), (x1, y1, z0), (x1, y1, z1),
                          (x1, y0, z1)], side),
             ((0, 0, 1), [(x0, y0, z1), (x1, y0, z1), (x1, y1, z1),
                          (x0, y1, z1)], lit)]
    out = []
    for n, pts, fill in faces:
        if n[2] == 1 and not top:
            continue
        p = pts[0]
        if hasattr(cam, "toward"):
            t = cam.toward
        else:
            t = [cam.eye[i] - p[i] for i in range(3)]
        if sum(n[i] * t[i] for i in range(3)) <= 1e-9:
            continue
        out.append(tk_poly(cam, pts, "fill=%s,draw=%s,line width=%s"
                           % (fill, edge, lw)))
    return "".join(out)


def brace2(x, y0, y1, amp=0.14, side=1):
    """A vertical curly brace at screen abscissa x from y0 to y1 (y0 < y1),
    its tip pointing to the right (side=1) or the left (side=-1)."""
    a = amp * side
    h = 0.5 * amp
    ym = 0.5 * (y0 + y1)

    def P(dx, y):
        return "(%.4f,%.4f)" % (x + dx, y)
    return ("  \\draw[PSlate,line width=0.5pt] %s .. controls %s and %s .. %s"
            " -- %s .. controls %s and %s .. %s .. controls %s and %s .. %s"
            " -- %s .. controls %s and %s .. %s;\n"
            % (P(0, y0), P(0.3 * a, y0), P(0.5 * a, y0 + 0.2 * h),
               P(0.5 * a, y0 + h),
               P(0.5 * a, ym - h), P(0.5 * a, ym - 0.2 * h), P(0.7 * a, ym),
               P(a, ym), P(0.7 * a, ym), P(0.5 * a, ym + 0.2 * h),
               P(0.5 * a, ym + h),
               P(0.5 * a, y1 - h), P(0.5 * a, y1 - 0.2 * h), P(0.3 * a, y1),
               P(0, y1)))


def bar_frame(cam, xl, xr, dep, ztop, levels, hs, tick=0.14):
    """Floor, back wall (y = dep) and left wall (x = xl) of a bar chart
    whose prisms stand on the floor 0 <= y <= dep, with the gridlines of
    the given levels on both walls, the scale on the front edge of the
    left wall, and its ticks.  Returns the TikZ and the tick ends."""
    out = []
    out.append(tk_poly(cam, [(xl, 0, 0), (xr, 0, 0), (xr, dep, 0),
                             (xl, dep, 0)], "fill=PSlate!9"))
    out.append(tk_poly(cam, [(xl, dep, 0), (xr, dep, 0), (xr, dep, ztop),
                             (xl, dep, ztop)], "fill=PSlate!4"))
    out.append(tk_poly(cam, [(xl, 0, 0), (xl, dep, 0), (xl, dep, ztop),
                             (xl, 0, ztop)], "fill=PSlate!7"))
    for v in levels:
        z = v * hs
        out.append(tk_line(cam, [(xl, 0, z), (xl, dep, z), (xr, dep, z)],
                           "PRule!85,line width=0.3pt"))
    # the outline of the frame
    out.append(tk_line(cam, [(xl, 0, ztop), (xl, dep, ztop), (xr, dep, ztop),
                             (xr, dep, 0)], "PSlate!45,line width=0.35pt"))
    out.append(tk_line(cam, [(xl, dep, 0), (xl, dep, ztop)],
                       "PSlate!45,line width=0.35pt"))
    out.append(tk_line(cam, [(xl, dep, 0), (xr, dep, 0)],
                       "PSlate!60,line width=0.4pt"))
    out.append(tk_line(cam, [(xl, 0, 0), (xr, 0, 0), (xr, dep, 0)],
                       "PSlate!80,line width=0.45pt"))
    out.append(tk_line(cam, [(xl, 0, 0), (xl, 0, ztop)],
                       "PSlate,line width=0.5pt"))
    ends = []
    for v in levels:
        z = v * hs
        out.append(tk_line(cam, [(xl, 0, z), (xl - tick, 0, z)],
                           "PSlate,line width=0.5pt"))
        ends.append((v, proj(cam, (xl - tick, 0, z))))
    return "".join(out), ends


# ------------------------------------------------------------------ ladder
LADDER_COL = {0: "PTeal", 1: "POchre", 2: "PBlue", 3: "PIndigo", 4: "PClay"}


PALETTE_RGB = {"PInk": (26, 32, 44), "PBlue": (37, 82, 139),
               "PTeal": (23, 127, 125), "POchre": (193, 138, 44),
               "PClay": (178, 74, 58), "PIndigo": (58, 64, 140)}


def ink_on(col, mix=0.80):
    """The text colour for a number on a tile filled with col!80: white or
    PInk, whichever has the larger WCAG contrast against the fill."""
    def lum(rgb):
        c = []
        for v in rgb:
            v /= 255.0
            c.append(v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4)
        return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
    fill = tuple(mix * a + (1 - mix) * 255 for a in PALETTE_RGB[col])
    lf, lw, li = lum(fill), 1.0, lum(PALETTE_RGB["PInk"])
    white = (lw + 0.05) / (lf + 0.05)
    ink = (lf + 0.05) / (li + 0.05)
    return "white" if white >= ink else "PInk"


def bracket(x0, x1, y, up=0.10):
    """A horizontal bracket from x0 to x1 at height y, ends turned up."""
    return ("  \\draw[PSlate,line width=0.5pt] (%.4f,%.4f) -- (%.4f,%.4f) -- "
            "(%.4f,%.4f) -- (%.4f,%.4f);\n"
            % (x0, y + up, x0, y, x1, y, x1, y + up))


def fig_ladder():
    """The Betti numbers of an abelian fourfold as prisms stacked from the
    pieces L^i P^j of the Lefschetz decomposition, the hard Lefschetz arcs,
    and under the prisms the same decomposition as a table whose rows are
    the sl_2 strings."""
    cam = Oblique(ang=36.0, k=0.62, scale=1.0)
    pl = Plate("fig_ladder", "make_diagrams.py",
               "The Lefschetz decomposition of the cohomology of an abelian "
               "fourfold, with the hard Lefschetz arcs.")
    Hs = 3.7 / 70.0
    SP, Wd, DEP = 1.50, 0.78, 0.62
    X = [0.62 + SP * k for k in range(9)]
    XL, XR = 0.0, X[-1] + Wd / 2
    b = [comb(8, k) for k in range(9)]
    prim = [b[j] - (b[j - 2] if j >= 2 else 0) for j in range(5)]
    assert prim == [1, 8, 27, 48, 42]
    levels = list(range(0, 71, 10))
    frame, ends = bar_frame(cam, XL, XR, DEP, 70 * Hs, levels, Hs)
    pl.add(frame)
    for k in range(9):
        x0, x1 = X[k] - Wd / 2, X[k] + Wd / 2
        js = list(range(k % 2, min(k, 8 - k) + 1, 2))
        z = 0.0
        for j in js:
            hgt = prim[j] * Hs
            pl.add(prism(cam, (x0, x1, 0.0, DEP, z, z + hgt), LADDER_COL[j],
                         "dark" if j == k else "light", top=(j == js[-1])))
            z += hgt
    # the arcs L^{4-k}: H^k -> H^{8-k}, nested half ellipses from the centre
    # of one top face to the centre of the other (b_k = b_{8-k}, so both
    # ends are at one height); each clears every prism it passes over
    apex = []
    tops = [111.0, 101.5, 92.0, 82.5]
    for k in range(4):
        pa = proj(cam, (X[k], DEP / 2, b[k] * Hs))
        pb = proj(cam, (X[8 - k], DEP / 2, b[8 - k] * Hs))
        assert abs(pa[1] - pb[1]) < 1e-9
        top = proj(cam, (0, DEP / 2, tops[k] * Hs))[1]
        xm, A, B = 0.5 * (pa[0] + pb[0]), 0.5 * (pb[0] - pa[0]), top - pa[1]
        pts = [(xm - A * math.cos(math.pi * i / 180.0),
                pa[1] + B * math.sin(math.pi * i / 180.0))
               for i in range(181)]
        for kk in range(k + 1, 8 - k):
            for yy in (0.0, DEP):
                for xx in (X[kk] - Wd / 2, X[kk] + Wd / 2):
                    cx, cy = proj(cam, (xx, yy, b[kk] * Hs))
                    u = (cx - xm) / A
                    assert abs(u) < 1 and pa[1] + B * math.sqrt(1 - u * u) \
                        > cy + 0.12, ("arc", k, kk)
        pl.add("  \\draw[PBlue!75!black,line width=0.8pt,%s] %s;\n"
               % (TIP, " -- ".join("(%.4f,%.4f)" % q for q in pts)))
        pl.add("  \\node[circle,fill=PInk,inner sep=0.9pt] at (%.4f,%.4f) {};\n"
               % pa)
        apex.append((xm, top))
    for k in range(4):
        pl.put(apex[k][0], apex[k][1] + 0.235, r"$L^{%d}$" % (4 - k),
               color="PBlue!75!black")

    # the scale
    for v, (x, y) in ends:
        pl.put(x - 0.07, y, r"$%d$" % v, color="PSlate", font=r"\footnotesize",
               anchor="e")
    xs, ys = ends[-1][1]
    pl.put(xs - 0.07, ys + 0.42, r"$\dim_{\QQ}$", color="PSlate",
           font=r"\footnotesize", anchor="e")

    # the table: the degrees, the sl_2 strings as rows, the Betti numbers
    cols = [proj(cam, (x, 0, 0))[0] for x in X]
    y = proj(cam, (XL, 0, 0))[1] - 0.40
    for k, x in enumerate(cols):
        pl.put(x, y, r"$H^{%d}$" % k)
    xh = cols[0] - 0.62
    tw, th, rp = Wd, 0.32, 0.40
    for r, j in enumerate([4, 3, 2, 1, 0]):
        yr = y - 0.52 - rp * r
        col = LADDER_COL[j]
        pl.put(xh, yr, r"$L^{i}P^{%d}$" % j, color="%s!70!black" % col,
               anchor="e")
        for k in range(j, 9 - j, 2):
            dark = (k == j)
            pl.add("  \\path[fill=%s,draw=%s,line width=%s] (%.4f,%.4f) "
                   "rectangle (%.4f,%.4f);\n"
                   % ("%s!80" % col if dark else "%s!24" % col,
                      "%s!55!black" % col if dark else "%s!75!black" % col,
                      "0.4pt" if dark else "0.3pt",
                      cols[k] - tw / 2, yr - th / 2, cols[k] + tw / 2,
                      yr + th / 2))
            pl.add("  \\node[text=%s,font=\\footnotesize,inner sep=0pt] at "
                   "(%.4f,%.4f) {$%d$};\n"
                   % (ink_on(col) if dark else "%s!60!black" % col, cols[k], yr,
                      prim[j]))
    yb = y - 0.52 - rp * 5 - 0.12
    pl.add(tk_line2([(xh - 1.05, yb + 0.30), (cols[-1] + tw / 2 + 0.05,
                                               yb + 0.30)],
                    "PRule,line width=0.4pt"))
    pl.put(xh, yb - 0.04, r"$\binom{8}{k}$", anchor="e")
    for k, x in enumerate(cols):
        pl.put(x, yb - 0.04, r"$%d$" % b[k])
    # where restriction to a hypersurface stands, degree by degree
    yq = yb - 0.50
    pad = tw / 2 + 0.10
    pl.add(bracket(cols[0] - pad, cols[3] + pad, yq))
    pl.add(bracket(cols[4] - pad, cols[4] + pad, yq))
    pl.add(bracket(cols[5] - pad, cols[8] + pad, yq))
    pl.put(0.5 * (cols[0] + cols[3]), yq - 0.12,
           r"$j^{*}$ injective", anchor="n")
    pl.put(cols[4], yq - 0.12, r"$j^{*}P^{4}=0$", anchor="n")
    pl.put(0.5 * (cols[5] + cols[8]), yq - 0.12,
           r"$H^{k}=L^{k-4}H^{8-k}$", anchor="n")
    pl.build()
    compile_plate("fig_ladder")


# ------------------------------------------------------------------ moduli
def fig_moduli():
    """dim A_{2n} = n(2n+1) as a prism, split into dim D_{n,n} = n^2 below
    and the codimension n(n+1) above, for n = 1, ..., 6."""
    cam = Oblique(ang=36.0, k=0.62, scale=1.42)
    pl = Plate("fig_moduli", "make_diagrams.py",
               "The Weil family inside the moduli of principally polarised "
               "abelian 2n-folds: n^2 against n(2n+1), for n up to six.")
    Hs = 3.55 / 80.0              # height of one dimension
    SP, Wd = 1.02, 0.58           # spacing and width of the prisms
    DEP = 0.58                    # depth of the frame = depth of a prism
    X = [SP * (n - 1) + 0.62 for n in range(1, 7)]
    XL, XR = 0.0, X[-1] + Wd / 2       # the frame ends at the last prism
    levels = list(range(0, 81, 10))
    frame, ends = bar_frame(cam, XL, XR, DEP, 80 * Hs, levels, Hs)
    pl.add(frame)
    # the prisms, far to near; each fills the depth 0 <= y <= DEP
    for i in range(6):
        n = i + 1
        d, g = n * n, n * (n + 1)
        x0, x1 = X[i] - Wd / 2, X[i] + Wd / 2
        pl.add(prism(cam, (x0, x1, 0.0, DEP, 0.0, d * Hs), "PBlue", "dark",
                     top=False))
        pl.add(prism(cam, (x0, x1, 0.0, DEP, d * Hs, (d + g) * Hs), "PClay",
                     "light"))

    # the scale
    for v, (x, y) in ends:
        pl.put(x - 0.07, y, r"$%d$" % v, color="PSlate", font=r"\footnotesize",
               anchor="e")
    xs, ys = ends[-1][1]
    pl.put(xs - 0.07, ys + 0.42, r"$\dim_{\CC}$", color="PSlate",
           font=r"\footnotesize", anchor="e")

    # braces on the last prism: its two parts and its whole height
    x0, x1 = X[5] - Wd / 2, X[5] + Wd / 2
    right = max(proj(cam, (x1, yy, 0))[0] for yy in (0.0, DEP))
    bx = right + 0.12
    zb = [proj(cam, (x1, DEP, z * Hs))[1] for z in (0, 36, 78)]
    pl.add(brace2(bx, zb[0] + 0.02, zb[1] - 0.03))
    pl.add(brace2(bx, zb[1] + 0.03, zb[2] - 0.02))
    pl.put(bx + 0.28, 0.5 * (zb[0] + zb[1]), r"$\dim\cD_{n,n}$", anchor="w",
           color="PBlue")
    pl.put(bx + 0.28, 0.5 * (zb[1] + zb[2]), r"codimension",
           anchor="w", color="PClay!85!black")
    xt, yt = proj(cam, (x1, DEP, 78 * Hs))
    pl.add(tk_line2([(xt + 0.06, yt), (bx + 0.17, yt)],
                    "PSlate,line width=0.5pt"))
    pl.put(bx + 0.28, yt, r"$\dim\cA_{2n}$", anchor="w")

    # the table under the prisms: n, n^2, n(n+1), n(2n+1)
    cols = [proj(cam, (x, 0, 0))[0] for x in X]
    yfront = min(proj(cam, (x, 0, 0))[1] for x in (XL, XR))
    rows = [(r"$n$", "PInk", lambda n: n),
            (r"$n^{2}$", "PBlue", lambda n: n * n),
            (r"$n(n+1)$", "PClay!85!black", lambda n: n * (n + 1)),
            (r"$n(2n+1)$", "PInk", lambda n: n * (2 * n + 1))]
    xh = proj(cam, (XL, 0, 0))[0] - 0.30
    for r, (head, col, f) in enumerate(rows):
        y = yfront - 0.42 - 0.44 * r - (0.10 if r else 0.0)
        pl.put(xh, y, head, color=col, anchor="e")
        for n, x in zip(range(1, 7), cols):
            pl.put(x, y, r"$%d$" % f(n), color=col)
    yr = yfront - 0.42 - 0.24
    pl.add(tk_line2([(xh - 1.25, yr), (cols[-1] + 0.35, yr)],
                    "PRule,line width=0.4pt"))
    pl.build()
    compile_plate("fig_moduli")


# --------------------------------------------------------------- signature
def fig_signature():
    """The saddle z = pq over the triangle p, q >= 0, p + q <= 12; the
    curves p + q = 2n with the signatures (p, q) on them; the ridge p = q
    with the heights n^2; a key for the two kinds of points."""
    tgt = (1.85, 1.85, 1.05)
    cam = Camera(eye=orbit_eye(tgt, 34.0, -112.0, 21.0), target=tgt,
                 focal=34.0, scale=2.0)
    sc = Scene(cam)
    pl = Plate("fig_signature", "make_diagrams.py",
               "The signatures (p,q) of an imaginary quadratic action on the "
               "saddle z = pq, with the Weil ridge p = q.")
    S = 0.36          # lattice spacing
    Hs = 0.068        # height per unit of pq
    N = 12

    def pt(p, q, z=None):
        return (p * S, q * S, (p * q if z is None else z) * Hs)

    # the saddle z = pq over the triangle p, q >= 0, p + q <= 12
    sc.surface(lambda s, lam: pt(lam * s, (1 - lam) * s), (0.0, float(N)),
               (0.0, 1.0), 24, 24, base="PSlate", opacity=0.20,
               ambient=0.66, diffuse=0.30)
    for a, b in (((0, 0), (N + 1.4, 0)), ((0, 0), (0, N + 1.4))):
        sc.polyline([pt(a[0], a[1], 0), pt(b[0], b[1], 0)],
                    "PSlate,line width=0.5pt," + TIP, priority=1)
    for i in range(2, N + 1, 2):
        sc.polyline([pt(i, 0, 0), pt(i, -0.40, 0)],
                    "PSlate,line width=0.45pt", priority=1)
        sc.polyline([pt(0, i, 0), pt(-0.40, i, 0)],
                    "PSlate,line width=0.45pt", priority=1)
    # the curves p + q = 2n on the saddle, with their signatures
    for m in range(1, 7):
        s = 2 * m
        sc.curve(lambda t, s=s: pt(t, s - t), (0.0, float(s)), 14 * m,
                 "PInk!75,line width=0.6pt", priority=2, chunk=2)
        for p in range(0, s + 1):
            if p != s - p:
                sc.dot3(pt(p, s - p), "circle,draw=PInk!80,fill=white,"
                        "line width=0.45pt,inner sep=1.05pt", priority=5)
    # the ridge p = q, where the Weil line consists of Hodge classes
    sc.curve(lambda t: pt(t, t), (0.0, 6.0), 60, "PClay,line width=1.5pt",
             priority=4, chunk=2)
    sc.polyline([pt(0, 0, 0), pt(6, 6, 0)],
                "PClay!60,line width=0.5pt,dash pattern=on 2pt off 1.5pt",
                priority=2)
    for n in range(1, 7):
        sc.polyline([pt(n, n, 0), pt(n, n)],
                    "PClay!60,line width=0.4pt,dash pattern=on 1pt off 1.2pt",
                    priority=3)
        sc.dot3(pt(n, n), "circle,fill=PClay,draw=white,line width=0.6pt,"
                "inner sep=1.9pt", priority=6)
    pl.add(soften(sc.emit()))

    for i in range(2, N + 1, 2):
        x, y = proj(cam, pt(i, -0.40, 0))
        pl.put(x + 0.05, y - 0.20, r"$%d$" % i, color="PSlate",
               font=r"\footnotesize")
    for n in range(1, 7):
        pl.label(proj(cam, pt(n, n)), r"$%d$" % (n * n), color="PClay",
                 font=r"\footnotesize", dirs=[180, 160, 200], rmax=1.0,
                 lead=0.5)
    pl.label(proj(cam, pt(N + 1.4, 0, 0)), r"$p$", color="PSlate",
             dirs=[0, 30], rmax=0.4)
    pl.label(proj(cam, pt(0, N + 1.4, 0)), r"$q$", color="PSlate",
             dirs=[90, 120, 150], rmax=0.4)
    for m in range(1, 7):
        x, y = proj(cam, pt(-0.40, 2 * m, 0))
        pl.label((x, y), r"$p+q=%d$" % (2 * m), color="PInk",
                 font=r"\footnotesize", dirs=[180, 200, 160], rmin=0.06,
                 rmax=0.8, lead=0.3)
    pl.label(proj(cam, pt(5.45, 5.45)), r"$p=q$", color="PClay",
             dirs=[0, -20, 20], rmin=0.15, rmax=1.2, skip=0.12, penalty=3.0)
    pl.label(proj(cam, pt(9.0, 1.5)), r"height $pq$", color="PSlate!80!black",
             dirs=[-10, 0, -30, 20], rmin=0.2, rmax=3.0, skip=0.10)

    # the key, under the plate on the right, below the tick labels
    bx0, by0, bx1, by1 = ink_bbox("".join(pl.parts))
    ytick = min(it["y"] for it in pl.fixed) - 0.16
    xk = bx1 - 7.10
    yk = ytick - 0.36
    pl.add("  \\node[circle,fill=PClay,draw=white,line width=0.6pt,"
           "inner sep=1.9pt] at (%.3f,%.3f) {};\n" % (xk, yk))
    pl.put(xk + 0.22, yk, r"$p=q=n$: $\HW(A)$ consists of Hodge classes",
           font=r"\footnotesize", anchor="w")
    pl.add("  \\node[circle,draw=PInk!80,fill=white,line width=0.45pt,"
           "inner sep=1.05pt] at (%.3f,%.3f) {};\n" % (xk, yk - 0.42))
    pl.put(xk + 0.22, yk - 0.42,
           r"$p\neq q$: $\HW(A)$ of type $\{(p,q),(q,p)\}$, no Hodge class",
           font=r"\footnotesize", anchor="w")
    pl.build()
    compile_plate("fig_signature")


if __name__ == "__main__":
    which = sys.argv[1:] or ["ladder", "moduli", "signature"]
    if "ladder" in which:
        fig_ladder()
    if "moduli" in which:
        fig_moduli()
    if "signature" in which:
        fig_signature()
