#!/usr/bin/env python3
"""
make_plates.py

Three plates computed from the equations of the paper, and the label placer
that the plates of make_properness.py and make_support.py share.

  fig_quadric    Theorem thm:plane at n = 2 and d = 2.  (a) A real affine
                 section of the spinor quadric in the chart a = 1 of the
                 points a u_t + b v_t + x n_1 + y n_2, where n_1, n_2 span a
                 negative definite plane orthogonal to P_t, normalised by
                 <n_i, n_j> = -d t^2 delta_ij.  The quadric is then
                 d (x^2 + y^2) - b^2 = d, a hyperboloid of one sheet, drawn
                 cut open with both rulings; the rational line P(P_t) is its
                 axis x = y = 0, which it never meets in a real point, and
                 the level circle through the rational point u_t + b v_t has
                 d rho^2 = b^2 + d = N(b + s).  (b) The complex points of the
                 same line as a Riemann sphere in the coordinate b / sqrt(d):
                 its real points form the equator, which carries the
                 rational points, and the two points [e^{+-st}] = [u_t +- s
                 v_t], b = +-sqrt(-d), are the poles, exchanged by complex
                 conjugation, the reflection in the equatorial plane.

  fig_lagsweep   Proposition prop:lagrangian.  (a) The bounded domain as a
                 ball, and a pencil of leaves through a common axis, the leaf
                 of slope lambda being the disc cut from the ball by the plane
                 z = lambda y.  Leaves of rational slope and height at most
                 two are drawn heavy; the leaf through the chosen point P has
                 slope sqrt 2 and is drawn dashed.  A dial at the end of the
                 axis carries the slope: every rational slope of height at
                 most eight is a tick whose length decreases with the height.
                 (b) The dimensions n^2 of D_{n,n}, n(n+1)/2 of a leaf and
                 n(n-1)/2 of its codimension, for n = 1, ..., 6.

  fig_fibres     Lemma lem:annihilator at n = 3.  (a) The basis
                 u_i ^ u_j, u_i ^ v_j, v_i ^ v_j of H^{0,2} = wedge^2 H^{0,1},
                 as the cells above the diagonal of a 6 x 6 array, sorted
                 into the three blocks of dimensions C(3,2), 9, C(3,2); the
                 mixed block is the kernel of multiplication by omega, and
                 the other two blocks go injectively to the two summands
                 named.  (b) The three dimensions C(n,2), n^2, C(n,2) for
                 n = 2, ..., 6, computed here.

The placer (class Plate): every label is measured by TeX, and put at the
nearest position around its anchor at which its box meets no other label,
no stroke and no fill of the figure, joined to the anchor by a leader that
crosses no other label and no other leader.  The crude box estimate of
checkfigs.py is imposed as well, so both checks pass by construction; the
finished figure is then tested again by Fig.check.

Run:  python3 -B make_plates.py        (from the figures directory)
"""
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from render3d import Camera, Scene, addv, smul, sub, unit, cross, dot, norm
from make_frontier import (Fig, measure, seg_hits_rect, poly_hits_rect,
                           rects_meet, circle_pts, bezier)
import checkfigs

SS, FS, SM = r"\scriptsize", r"\footnotesize", r"\small"
STIP = r"-{Stealth[length=4pt,width=3.2pt]}"
COORD = re.compile(r"\(\s*(-?\d+(?:\.\d*)?)\s*,\s*(-?\d+(?:\.\d*)?)\s*\)")

HEAD = r"""%% {name}.tex   (generated by {gen}; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=6pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc,patterns,decorations.pathreplacing}}
\input{{palette}}
{preamble}\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"


# ====================================================== geometry helpers
def seg_cross(p, q, r, s):
    """True if the closed segments pq and rs meet."""
    def orient(a, b, c):
        v = (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])
        return 0 if abs(v) < 1e-12 else (1 if v > 0 else -1)
    o1, o2 = orient(p, q, r), orient(p, q, s)
    o3, o4 = orient(r, s, p), orient(r, s, q)
    if o1 != o2 and o3 != o4:
        return True
    return False


def shift_tikz(s, dx, dy):
    """Translate every coordinate pair of a TikZ fragment."""
    return COORD.sub(lambda m: "(%.4f,%.4f)" % (float(m.group(1)) + dx,
                                                float(m.group(2)) + dy), s)


def extent(s):
    xs, ys = [], []
    for a, b in COORD.findall(s):
        xs.append(float(a))
        ys.append(float(b))
    return min(xs), min(ys), max(xs), max(ys)


class Grid:
    """A spatial hash of strokes and fills, for fast exact tests."""

    def __init__(self, cell=0.35):
        self.cell = cell
        self.bins = {}

    def _keys(self, bb):
        c = self.cell
        for i in range(int(math.floor(bb[0] / c)),
                       int(math.floor(bb[2] / c)) + 1):
            for j in range(int(math.floor(bb[1] / c)),
                           int(math.floor(bb[3] / c)) + 1):
                yield (i, j)

    def add(self, item, bb):
        for k in self._keys(bb):
            self.bins.setdefault(k, []).append(item)

    def query(self, bb):
        seen, out = set(), []
        for k in self._keys(bb):
            for it in self.bins.get(k, ()):
                if id(it) not in seen:
                    seen.add(id(it))
                    out.append(it)
        return out


ANCHOR_OF = {"W": "west", "E": "east", "N": "north", "S": "south",
             "C": None}


class Plate(Fig):
    """Fig with a placer for labels with leaders.  request() queues a label;
    solve() places every queued label in order."""

    def __init__(self, name, blurb, gen, preamble=""):
        Fig.__init__(self, name, blurb, pad=0.05)
        self.gen = gen
        self.preamble = preamble
        self.requests = []
        self.dots = []             # (x, y, r): marked points, kept clear
        self.frame = None          # optional (x0, y0, x1, y1) for labels

    # -- marked points -----------------------------------------------------
    def mark(self, x, y, r=0.055, fill="PInk", draw="white", lw=0.5,
             tag="dot"):
        self.raw(r"  \filldraw[fill=%s,draw=%s,line width=%.2fpt] "
                 r"(%.3f,%.3f) circle (%.3f);" % (fill, draw, lw, x, y, r))
        self.polys.append((circle_pts(x, y, r + 0.01), tag))
        self.dots.append((x, y, r))

    def hollow(self, x, y, r=0.06, draw="PInk", lw=0.8, tag="dot",
               style=""):
        self.raw(r"  \filldraw[fill=white,draw=%s,line width=%.2fpt%s] "
                 r"(%.3f,%.3f) circle (%.3f);" % (draw, lw, style, x, y, r))
        self.polys.append((circle_pts(x, y, r + 0.01), tag))
        self.dots.append((x, y, r))

    # -- queued labels -------------------------------------------------------
    def request(self, anchor, text, color="PInk", size=SM, tag=None,
                allow=(), prefer=None, spread=180.0, rmin=0.16, rmax=3.2,
                sides="WENS", leader="PSlate!80", clear=0.0, lw=0.4,
                region=None, weight=1.0):
        """anchor: the point (in figure cm) the label names.  prefer: the
        preferred direction in degrees; spread: how far from it to look.
        clear: the radius of the marked point at the anchor, so the leader
        starts on its rim."""
        if tag is None:
            tag = "L%d" % len(self.requests)
        self.requests.append(dict(anchor=anchor, text=text, color=color,
                                  size=size, tag=tag, allow=set(allow),
                                  prefer=prefer, spread=spread, rmin=rmin,
                                  rmax=rmax, sides=sides, leader=leader,
                                  clear=clear, lw=lw, region=region,
                                  weight=weight))
        return tag

    @staticmethod
    def opts(color, size, side):
        o = "text=%s,inner sep=1pt,align=center,font=%s" % (color, size)
        a = ANCHOR_OF[side]
        if a:
            o += ",anchor=%s" % a
        return o

    def _grid(self):
        G = Grid()
        for p, q, tag in self.segs:
            G.add(("s", p, q, tag), (min(p[0], q[0]), min(p[1], q[1]),
                                     max(p[0], q[0]), max(p[1], q[1])))
        for pts, tag in self.polys:
            xs = [a for a, b in pts]
            ys = [b for a, b in pts]
            G.add(("p", pts, tag), (min(xs), min(ys), max(xs), max(ys)))
        return G

    def solve(self, verbose=False):
        if not self.requests:
            return
        # boxes of every text, anchored at the centre, in one run of TeX
        specs = [(self.opts(r["color"], r["size"], "C"), r["text"])
                 for r in self.requests]
        fixed = [(l["opts"], l["text"]) for l in self.labels]
        self.premeasure(specs + fixed)
        for l in self.labels:
            b = self._cache[(l["opts"], l["text"])]
            l["box"] = (l["x"] + b[0], l["y"] + b[1], l["x"] + b[2],
                        l["y"] + b[3])
        G = self._grid()
        placed = [dict(box=l["box"], crude=self._crude(l["opts"], l["x"],
                                                       l["y"], l["text"]))
                  for l in self.labels]
        leaders = []
        for r in self.requests:
            best = self._place(r, G, placed, leaders)
            if best is None:
                if os.environ.get("PLATE_DEBUG"):
                    print("   UNPLACED", r["text"])
                    continue
                raise SystemExit("%s: no place for label %r"
                                 % (self.name, r["text"]))
            score, (x, y), side, box, lead = best
            if lead is not None:
                self.path(lead, r["leader"], lw=r["lw"], tag=r["tag"])
                p, q = lead
                G.add(("s", p, q, r["tag"]),
                      (min(p[0], q[0]), min(p[1], q[1]),
                       max(p[0], q[0]), max(p[1], q[1])))
                leaders.append((p, q, r["tag"]))
            opts = self.opts(r["color"], r["size"], side)
            self.node(x, y, r["text"], opts, tag=r["tag"],
                      allow=r["allow"])
            G.add(("p", [(box[0], box[1]), (box[2], box[1]),
                         (box[2], box[3]), (box[0], box[3])], "label"), box)
            placed.append(dict(box=box, crude=self._crude(opts, x, y,
                                                          r["text"])))
            if verbose:
                print("   placed %-40s score %.2f" % (r["text"][:40], score))

    @staticmethod
    def _crude(opts, x, y, text):
        b = checkfigs.box(opts, x, y, text)
        return b[:4]

    def _place(self, r, G, placed, leaders):
        w0 = self._cache[(self.opts(r["color"], r["size"], "C"), r["text"])]
        W, H = w0[2] - w0[0], w0[3] - w0[1]
        ax, ay = r["anchor"]
        P = self.pad + 0.02
        best = None
        radii = [r["rmin"]] + [x for x in (0.30, 0.42, 0.55, 0.70, 0.85,
                                            1.0, 1.2, 1.4, 1.65, 1.9, 2.2,
                                            2.5, 2.85, 3.2, 3.6, 4.0)
                               if r["rmin"] < x <= r["rmax"]]
        for rad in radii:
            for k in range(48):
                th = 7.5 * k
                if r["prefer"] is not None:
                    dev = abs((th - r["prefer"] + 180.0) % 360.0 - 180.0)
                    if dev > r["spread"]:
                        continue
                else:
                    dev = 0.0
                c, s = math.cos(math.radians(th)), math.sin(math.radians(th))
                ex, ey = ax + rad * c, ay + rad * s
                if abs(c) >= 0.5:
                    side = "W" if c > 0 else "E"
                else:
                    side = "S" if s > 0 else "N"
                if side not in r["sides"]:
                    continue
                if side == "W":
                    box = (ex, ey - H / 2, ex + W, ey + H / 2)
                elif side == "E":
                    box = (ex - W, ey - H / 2, ex, ey + H / 2)
                elif side == "S":
                    box = (ex - W / 2, ey, ex + W / 2, ey + H)
                else:
                    box = (ex - W / 2, ey - H, ex + W / 2, ey)
                if r["region"] is not None:
                    R = r["region"]
                    if (box[0] < R[0] or box[1] < R[1] or box[2] > R[2]
                            or box[3] > R[3]):
                        continue
                pbox = (box[0] - P, box[1] - P, box[2] + P, box[3] + P)
                if any(rects_meet(pbox, q["box"]) for q in placed):
                    continue
                opts = self.opts(r["color"], r["size"], side)
                cb = self._crude(opts, ex, ey, r["text"])
                if any(rects_meet(cb, q["crude"]) for q in placed):
                    continue
                if any(math.hypot(min(max(dx, pbox[0]), pbox[2]) - dx,
                                  min(max(dy, pbox[1]), pbox[3]) - dy)
                       < dr + 0.04 for dx, dy, dr in self.dots):
                    continue
                bad = False
                for it in G.query(pbox):
                    if it[0] == "s":
                        if it[3] in r["allow"] or it[3] == r["tag"]:
                            continue
                        if seg_hits_rect(it[1], it[2], pbox):
                            bad = True
                            break
                    else:
                        if it[2] in r["allow"] or it[2] == "bg":
                            continue
                        if poly_hits_rect(it[1], pbox):
                            bad = True
                            break
                if bad:
                    continue
                # the leader, from the rim of the anchor to the label
                lead = None
                cross_pen = 0.0
                if rad > 0.26:
                    st = (ax + (r["clear"] + 0.035) * c,
                          ay + (r["clear"] + 0.035) * s)
                    en = (ex - 0.035 * c, ey - 0.035 * s)
                    lead = (st, en)
                    lb = (min(st[0], en[0]), min(st[1], en[1]),
                          max(st[0], en[0]), max(st[1], en[1]))
                    for q in placed:
                        if seg_hits_rect(st, en, q["box"]):
                            bad = True
                            break
                    if bad:
                        continue
                    if any(seg_cross(st, en, p, q) for p, q, t in leaders):
                        continue
                    n = 0
                    for it in G.query(lb):
                        if it[0] == "s" and it[3] != "label" and \
                                seg_cross(st, en, it[1], it[2]):
                            n += 1
                    cross_pen = 0.05 * n
                score = r["weight"] * rad + 0.004 * dev + cross_pen
                if best is None or score < best[0]:
                    best = (score, (ex, ey), side, box, lead)
            if best is not None and best[0] < rad * r["weight"] * 0.8:
                break
        return best

    # -- output ----------------------------------------------------------------
    def write(self):
        bad = self.check(verbose=True)
        if bad and not os.environ.get("PLATE_DEBUG"):
            raise SystemExit("%s: %d problems" % (self.name, len(bad)))
        # the crude estimate of checkfigs.py as well
        boxes = [checkfigs.box(l["opts"], l["x"], l["y"], l["text"])
                 for l in self.labels
                 if checkfigs._plain(l["text"]).strip()]
        hits = [(a[4], b[4]) for i, a in enumerate(boxes)
                for b in boxes[i + 1:] if rects_meet(a[:4], b[:4])]
        if hits and not os.environ.get("PLATE_DEBUG"):
            raise SystemExit("%s: checkfigs estimate overlaps %s"
                             % (self.name, hits))
        path = os.path.join(HERE, self.name + ".tex")
        with open(path, "w") as f:
            f.write(HEAD.format(name=self.name, gen=self.gen,
                                blurb=self.blurb, preamble=self.preamble))
            f.write(self.tikz())
            f.write(TAIL)
        print("wrote %s: %d labels" % (path, len(self.labels)))


def panel_letter(F, x, y, letter):
    F.text(x, y, r"\textup{(%s)}" % letter, "PInk", SM, anchor="north west",
           tag="letter")


# ====================================================== render helpers
import render3d as _r3


class Mesh:
    """A parametric surface rendered through Scene.surface, with the depth of
    each of its facets kept, so that a curve lying on the surface can be
    sorted exactly after the facet it lies on."""

    def __init__(self, sc, f, urange, vrange, nu, nv, keep_uv=None, **kw):
        self.sc, self.f = sc, f
        self.u0, self.u1 = urange
        self.v0, self.v1 = vrange
        self.nu = int(round(nu * _r3.DETAIL)) if nu > 1 else nu
        self.nv = int(round(nv * _r3.DETAIL)) if nv > 1 else nv
        self.keep_uv = keep_uv
        cull = None
        if keep_uv is not None:
            du = (self.u1 - self.u0) / self.nu
            dv = (self.v1 - self.v0) / self.nv

            def cull(P, _k=[0]):
                # Scene.surface visits (i, j) in order
                i, j = divmod(_k[0], self.nv)
                _k[0] += 1
                return keep_uv(self.u0 + (i + 0.5) * du,
                               self.v0 + (j + 0.5) * dv)
        sc.surface(f, urange, vrange, nu, nv, cull=cull, **kw)

    def ij(self, u, v):
        i = int((u - self.u0) / (self.u1 - self.u0) * self.nu)
        j = int((v - self.v0) / (self.v1 - self.v0) * self.nv)
        return min(max(i, 0), self.nu - 1), min(max(j, 0), self.nv - 1)

    def depth(self, u, v):
        i, j = self.ij(u, v)
        us = [self.u0 + (self.u1 - self.u0) * (i + a) / self.nu
              for a in (0, 1)]
        vs = [self.v0 + (self.v1 - self.v0) * (j + b) / self.nv
              for b in (0, 1)]
        ds = [self.sc.cam.project(self.f(uu, vv))[1] for uu in us
              for vv in vs]
        return sum(ds) / 4.0

    def present(self, u, v):
        if self.keep_uv is None:
            return True
        i, j = self.ij(u, v)
        du = (self.u1 - self.u0) / self.nu
        dv = (self.v1 - self.v0) / self.nv
        return self.keep_uv(self.u0 + (i + 0.5) * du,
                            self.v0 + (j + 0.5) * dv)

    def curve(self, uv, trange, n, style, priority=1):
        """uv(t) -> (u, v); the curve f(uv(t)), piece by piece, each piece
        sorted just after the facet under its midpoint, and dropped where
        the facet is cut away."""
        t0, t1 = trange
        ps = [uv(t0 + (t1 - t0) * k / n) for k in range(n + 1)]
        run = []
        for k in range(n):
            (ua, va), (ub, vb) = ps[k], ps[k + 1]
            um, vm = (ua + ub) / 2, (va + vb) / 2
            if not self.present(um, vm):
                continue
            a, b = self.f(ua, va), self.f(ub, vb)
            (pa, _), (pb, _) = self.sc.cam.project(a), self.sc.cam.project(b)
            self.sc.add(self.depth(um, vm) - 1e-4,
                        "  \\draw[%s] (%.4f,%.4f) -- (%.4f,%.4f);\n"
                        % (style, pa[0], pa[1], pb[0], pb[1]), priority)


def silhouette_sphere(cam, centre, R, n=240):
    """The projected outline of a sphere under a perspective camera."""
    e = sub(cam.eye, centre)
    ne = norm(e)
    u = unit(e)
    h = R * R / ne
    rr = math.sqrt(max(0.0, R * R - h * h))
    b1 = unit(cross(u, (0.0, 0.0, 1.0)))
    b2 = cross(u, b1)
    out = []
    for k in range(n + 1):
        t = 2 * math.pi * k / n
        p = tuple(centre[i] + h * u[i] + rr * (math.cos(t) * b1[i]
                                               + math.sin(t) * b2[i])
                  for i in range(3))
        out.append(cam.project(p)[0])
    return out


def seal(body, lw=0.25):
    """Stroke every opaque facet in its own colour, so that the hairline
    seams between adjacent facets do not show in a raster of the page."""
    return re.sub(r"\\path\[draw=none,fill=([^\],]+)\]",
                  lambda m: "\\path[draw=%s,line width=%.2fpt,fill=%s]"
                  % (m.group(1), lw, m.group(1)), body)


def visible_runs(pts, hidden):
    """Split a sampled curve into its maximal runs of visible samples."""
    runs, cur = [], []
    for p in pts:
        if not hidden(p):
            cur.append(p)
        else:
            if len(cur) > 1:
                runs.append(cur)
            cur = []
    if len(cur) > 1:
        runs.append(cur)
    return runs


def ray_hits_quadric(eye, p, coef, accept):
    """Does the open segment from eye to p meet the quadric
    c0 x^2 + c1 y^2 + c2 z^2 + c3 = 0 at a point q with accept(q)?"""
    w = sub(p, eye)
    c0, c1, c2, c3 = coef
    A = c0 * w[0] ** 2 + c1 * w[1] ** 2 + c2 * w[2] ** 2
    B = 2 * (c0 * eye[0] * w[0] + c1 * eye[1] * w[1] + c2 * eye[2] * w[2])
    C = c0 * eye[0] ** 2 + c1 * eye[1] ** 2 + c2 * eye[2] ** 2 + c3
    if abs(A) < 1e-14:
        roots = [] if abs(B) < 1e-14 else [-C / B]
    else:
        disc = B * B - 4 * A * C
        if disc < 0:
            return False
        r = math.sqrt(disc)
        roots = [(-B - r) / (2 * A), (-B + r) / (2 * A)]
    for t in roots:
        if 1e-6 < t < 1 - 2e-5:
            q = addv(eye, smul(t, w))
            if accept(q):
                return True
    return False


# ============================================================ fig_quadric
D_Q = 2                      # d, so K = Q(sqrt(-2)), as in fig_moment
B_Q = 2.35                   # the section is drawn for |b| <= B_Q


def fig_quadric():
    F = Plate("fig_quadric",
              "The spinor quadric at n = 2, d = 2 in the chart a = 1: the "
              "rational line P(P_t) is the axis, and its complex points form "
              "a sphere whose poles are [e^{+-st}].", "make_plates.py")
    d = float(D_Q)
    sd = math.sqrt(d)

    def rho(b):
        return math.sqrt(1.0 + b * b / d)

    # the equation, checked on the rulings and on the axis
    for t in (0.3, 1.9):
        for sg in (1, -1):
            for l in (-1.2, 0.4):
                x = math.cos(t) - l * math.sin(t)
                y = math.sin(t) + l * math.cos(t)
                b = sg * sd * l
                assert abs(d * (x * x + y * y) - b * b - d) < 1e-12
    # on the axis x = y = 0 the equation is b^2 = -d: no real point, and
    # the two complex points b = +-sqrt(-d) = +-s are u_t +- s v_t

    # ---------------------------------------------------------- panel (a)
    az, el, dist = math.radians(-64.0), math.radians(17.0), 15.0
    tgt = (0.0, 0.0, 0.05)
    eye = (dist * math.cos(el) * math.cos(az),
           dist * math.cos(el) * math.sin(az),
           tgt[2] + dist * math.sin(el))
    cam = Camera(eye=eye, target=tgt, focal=dist, scale=1.30)
    sc = Scene(cam, light=(0.35, -0.80, 0.72))
    # the cuts fall on grid lines of the mesh (144 facets round the waist)
    CUTF, CUTB = math.radians(47.5), math.radians(30.0)

    def wrap(a):
        return (a + math.pi) % (2 * math.pi) - math.pi

    def keep_uv(u, v):
        dv = wrap(u - az)
        return abs(dv) > CUTF and abs(wrap(dv - math.pi)) > CUTB

    def quad(u, v):
        return (rho(v) * math.cos(u), rho(v) * math.sin(u), v)

    M = Mesh(sc, quad, (az, az + 2 * math.pi), (-B_Q, B_Q), 96, 30,
             keep_uv=keep_uv, base="PBlue", ambient=0.62, diffuse=0.34)
    # the level circles through the rational points b = 0, +-1, +-2 are
    # dashed where the surface is cut away behind the axis
    for b in (-2, -1, 0, 1, 2):
        arc = [quad(az + math.pi + CUTB * (2 * k / 40 - 1), float(b))
               for k in range(41)]
        sc.polyline(arc, "PInk!70,line width=0.45pt,dash pattern=on 1.6pt "
                    "off 1.3pt", 2)
    # the axis: the real points of P(P_t) in the chart a = 1
    AX0, AX1 = -B_Q - 0.45, B_Q + 0.85
    n = 60
    for k in range(n):
        p = (0.0, 0.0, AX0 + (AX1 - AX0) * k / n)
        q = (0.0, 0.0, AX0 + (AX1 - AX0) * (k + 1) / n)
        st = "PMag,line width=1.25pt"
        if k == n - 1:
            st += "," + STIP
        sc.polyline([p, q], st, priority=3)
    # a radius of the level circle b = 2
    rr2 = rho(2.0)
    ua = az + math.pi - CUTB * 0.55
    sc.polyline([(0, 0, 2.0), (rr2 * math.cos(ua), rr2 * math.sin(ua), 2.0)],
                "PInk,line width=0.6pt", 4)
    body = seal(sc.emit())
    x0, y0, x1, y1 = extent(body)
    dx, dy = -x0 + 0.4, -y0 + 0.30
    body = shift_tikz(body, dx, dy)

    def P2(p):
        (x, y), _ = cam.project(p)
        return (x + dx, y + dy)

    def tagger(st):
        if "PMag" in st:
            return "axis"
        if "PTeal" in st or "PAmber" in st:
            return "ruling"
        if "PInk" in st:
            return "level"
        return "quadric"
    F.scene(body, tagger=tagger)
    XA1, YA0, YA1 = x1 + dx, y0 + dy, y1 + dy

    # curves on the surface, drawn over it where the surface does not hide
    # them: visibility by intersecting the ray to the eye with the quadric
    def on_kept(q):
        return abs(q[2]) <= B_Q and keep_uv(math.atan2(q[1], q[0]), q[2])

    def hidden(p):
        u = math.atan2(p[1], p[0])
        if not keep_uv(u, p[2]):
            return True
        return ray_hits_quadric(eye, p, (d, d, -1.0, -d), on_kept)

    def draw_on(pts, style, lw, tag):
        for run in visible_runs(pts, hidden):
            F.path([P2(p) for p in run], style, lw=lw, tag=tag)
    NR = 20
    lam = B_Q / sd
    for k in range(NR):
        t = az + 2 * math.pi * (k + 0.5) / NR
        for sg, col in ((+1, "PTeal"), (-1, "PAmber")):
            pts = [(math.cos(t) - l * math.sin(t), math.sin(t)
                    + l * math.cos(t), sg * sd * l)
                   for l in [-lam + 2 * lam * j / 160 for j in range(161)]]
            draw_on(pts, col, 0.5, "ruling")
    for b in (-2, -1, 0, 1, 2):
        pts = [quad(az + 2 * math.pi * j / 480, float(b)) for j in range(481)]
        draw_on(pts, "PInk", 0.95 if b == 0 else 0.65, "level")
    for b in (-B_Q + 1e-6, B_Q - 1e-6):
        pts = [quad(az + 2 * math.pi * j / 480, b) for j in range(481)]
        draw_on(pts, "PBlue!75!black", 0.75, "rim")
    eps = 2e-4
    for u in (az + CUTF + eps, az + math.pi - CUTB - eps,
              az + math.pi + CUTB + eps, az + 2 * math.pi - CUTF - eps):
        pts = [quad(u, -B_Q + 2 * B_Q * j / 160) for j in range(161)]
        draw_on(pts, "PBlue!75!black", 0.75, "rim")
    # the rational points on the axis, and their names
    for b in (-2, -1, 0, 1, 2):
        q = P2((0.0, 0.0, float(b)))
        F.mark(q[0], q[1], r=0.05 if b else 0.062, fill="PMag", lw=0.45,
               tag="axis")
    F.request(P2((0.0, 0.0, AX1)), r"$\PP(P_{t})(\RR)$", "PMag", SM,
              prefer=0, spread=60, allow=("axis",))
    for b in (-2, -1, 0, 1, 2):
        F.request(P2((0.0, 0.0, float(b))), r"$%d$" % b if b >= 0 else
                  r"$-%d$" % -b, "PMag", FS, clear=0.05, prefer=180,
                  spread=40, rmin=0.2, rmax=0.26, sides="E",
                  allow=("axis",))
    F.request(P2((0.0, 0.0, AX1 - 0.25)), r"$b$", "PMag", SM, prefer=180,
              spread=20, rmin=0.2, rmax=0.26, sides="E", allow=("axis",))
    mid = (0.5 * rr2 * math.cos(ua), 0.5 * rr2 * math.sin(ua), 2.0)
    F.request(P2(mid), r"$\rho$", "PInk", FS, prefer=90, spread=40,
              rmax=0.6, allow=("level",))
    F.request(P2(quad(az + CUTF + 0.25, 2.0)),
              r"$d\rho^{2}=\Nm_{K/\QQ}(b+s)$", "PInk", FS, prefer=0,
              spread=60)
    F.request(P2(quad(az + math.pi * 0.55, B_Q)),
              r"$Q:\ d(x^{2}+y^{2})-b^{2}=d$", "PBlue!70!black", SM,
              prefer=60, spread=60)

    # ---------------------------------------------------------- panel (b)
    # the Riemann sphere of P(P_t)(C), in the coordinate beta = b / sqrt(d)
    RS = 1.0
    az2, el2 = math.radians(-58.0), math.radians(24.0)
    GAM = az2 - math.pi / 2

    def sph(beta):
        """beta in C  ->  the unit sphere: Im beta > 0 up, the real line on
        the equator, b = 0 facing the eye and b = infinity behind."""
        m = abs(beta) ** 2
        X = 2 * beta.real / (m + 1)
        Y = 2 * beta.imag / (m + 1)
        Z = (m - 1) / (m + 1)
        cg, sg = math.cos(GAM), math.sin(GAM)
        return (RS * (X * cg + Z * sg), RS * (X * sg - Z * cg), RS * Y)
    # the poles are b = +-s: beta = +-i
    assert abs(sph(complex(0, 1))[2] - RS) < 1e-12
    eye2 = (dist * math.cos(el2) * math.cos(az2),
            dist * math.cos(el2) * math.sin(az2), dist * math.sin(el2))
    cam2 = Camera(eye=eye2, target=(0, 0, 0), focal=dist, scale=1.80)
    sc2 = Scene(cam2, light=(0.35, -0.80, 0.72))

    def ball(u, v):
        return (RS * math.cos(v) * math.cos(u), RS * math.cos(v) * math.sin(u),
                RS * math.sin(v))
    S = Mesh(sc2, ball, (0, 2 * math.pi), (-math.pi / 2, math.pi / 2), 64, 34,
             base="PSlate", ambient=0.72, diffuse=0.28, twosided=False)

    def facing(p):
        return dot(sub(cam2.eye, p), p) > 0.0
    body2 = seal(sc2.emit())
    sx0, sy0, sx1, sy1 = extent(body2)
    OX = XA1 + 2.6
    ddx = OX - sx0
    ddy = (YA0 + YA1) / 2 - (sy0 + sy1) / 2 + 0.10

    def P3(p):
        (x, y), _ = cam2.project(p)
        return (x + ddx, y + ddy)
    F.scene(shift_tikz(body2, ddx, ddy), tag="sphere")
    F.path([(x + ddx, y + ddy) for x, y in silhouette_sphere(cam2, (0, 0, 0),
                                                           RS)],
           "PSlate", lw=0.6, tag="sphere")
    # the circles |beta - i| = k |beta + i| (latitudes) and the circles
    # through +-i (meridians), where they face the eye
    def grid(pts):
        for run in visible_runs(pts, lambda p: not facing(p)):
            F.path([P3(p) for p in run], "PSlate!60", lw=0.3, tag="grid")
    for lat in (-60, -30, 30, 60):
        v = math.radians(lat)
        grid([ball(2 * math.pi * k / 240, v) for k in range(241)])
    for lon in range(0, 360, 30):
        u = math.radians(lon)
        grid([ball(u, -math.pi / 2 + math.pi * k / 120) for k in range(121)])
    # the equator: the real points; front solid, back dashed, as two paths
    eq = [ball(GAM + math.pi / 2 + 2 * math.pi * k / 360, 0.0)
          for k in range(361)]
    runs, cur, vis = [], [], None
    for p in eq:
        f = facing(p)
        if vis is None or f == vis:
            cur.append(p)
        else:
            runs.append((vis, cur))
            cur = [cur[-1], p]
        vis = f
    runs.append((vis, cur))
    for f, pts in runs:
        F.path([P3(p) for p in pts],
               "PMag,line width=1.25pt" if f else
               "PMag!55,dash pattern=on 1.8pt off 1.5pt",
               lw=1.25 if f else 0.6, tag="equator")
    # rational points on the equator: every b = p/q with max(|p|, q) <= 3
    for q in range(1, 4):
        for p in range(-3, 4):
            if math.gcd(p, q) != 1:
                continue
            pt = sph(complex(p / q / sd, 0.0))
            if not facing(pt):
                continue
            x, y = P3(pt)
            big = (q == 1 and abs(p) <= 1)
            F.mark(x, y, r=0.05 if big else 0.034, fill="PMag", lw=0.35,
                   tag="equator")
    # the two poles, b = +-s
    N_ = P3(sph(complex(0, 1)))
    S_ = P3(sph(complex(0, -1)))
    F.hollow(N_[0], N_[1], r=0.065, draw="PClay", lw=1.0, tag="pole")
    F.hollow(S_[0], S_[1], r=0.065, draw="PClay", lw=0.9, tag="pole",
             style=",dash pattern=on 1.2pt off 0.9pt")
    F.request(N_, r"$[e^{st}]=[u_{t}+s\,v_{t}]$", "PClay", SM, clear=0.07,
              prefer=90, spread=60)
    F.request(S_, r"$[e^{-st}]=[u_{t}-s\,v_{t}]$", "PClay", SM, clear=0.07,
              prefer=270, spread=60)
    F.request(P3(sph(complex(0.0, 0.0))), r"$[u_{t}]$", "PMag", FS,
              clear=0.05, prefer=270, spread=70)
    F.request(P3(sph(complex(1.0 / sd, 0.0))), r"$[u_{t}+v_{t}]$", "PMag", FS,
              clear=0.05, prefer=300, spread=70)
    F.request(P3(sph(complex(-1.0 / sd, 0.0))), r"$[u_{t}-v_{t}]$", "PMag",
              FS, clear=0.05, prefer=240, spread=70)
    lft = min(eq, key=lambda p: P3(p)[0])
    F.request(P3(lft), r"$\PP(P_{t})(\RR)$", "PMag", SM, prefer=180,
              spread=40)
    F.solve()
    F.text(0.05, YA1 + 0.10, r"\textup{(a)}", "PInk", SM,
           anchor="north west", tag="letter")
    F.text(OX - 0.45, YA1 + 0.10, r"\textup{(b)}", "PInk", SM,
           anchor="north west", tag="letter")
    return F


# ============================================================ fig_lagsweep
def slopes(H):
    """The rational slopes p/q of height max(|p|, q) <= H, with their
    heights, and the slope infinity = 1/0 of height one."""
    out = {}
    for q in range(0, H + 1):
        for p in range(-H, H + 1):
            if (p, q) == (0, 0) or math.gcd(p, q) != 1:
                continue
            if q == 0 and p != 1:
                continue
            lam = math.inf if q == 0 else p / q
            h = max(abs(p), q)
            if lam not in out or out[lam][0] > h:
                out[lam] = (h, p, q)
    return out


def fig_lagsweep():
    F = Plate("fig_lagsweep",
              "The quaternionic loci as a pencil of leaves through a common "
              "axis, the slope dial of the pencil with its rational points, "
              "and the dimensions n^2, n(n+1)/2, n(n-1)/2.", "make_plates.py")
    # ---------------------------------------------------------- panel (a)
    az, el, dist = math.radians(-58.0), math.radians(21.0), 16.0
    eye = (dist * math.cos(el) * math.cos(az),
           dist * math.cos(el) * math.sin(az), dist * math.sin(el))
    cam = Camera(eye=eye, target=(0, 0, 0), focal=dist, scale=2.45)
    R = 1.0

    def Pr(p):
        return cam.project(p)[0]
    sil = silhouette_sphere(cam, (0, 0, 0), R, 240)
    x0 = min(p[0] for p in sil)
    y0 = min(p[1] for p in sil)
    dx, dy = -x0 + 1.25, -y0 + 0.45

    def P2(p):
        q = Pr(p)
        return (q[0] + dx, q[1] + dy)

    def e2of(th):
        return (0.0, math.cos(th), math.sin(th))

    def leaf_pts(th, n=180):
        e2 = e2of(th)
        return [addv(smul(R * math.cos(2 * math.pi * k / n), (1.0, 0, 0)),
                     smul(R * math.sin(2 * math.pi * k / n), e2))
                for k in range(n + 1)]
    silp = [(p[0] + dx, p[1] + dy) for p in sil]
    C0 = P2((0, 0, 0))
    rad = (max(p[0] for p in silp) - min(p[0] for p in silp)) / 2
    # the ball, a faint shaded sphere
    F.raw(r"  \shade[ball color=WBlue!70!white,opacity=0.40] (%.3f,%.3f) "
          r"circle (%.3f);" % (C0[0], C0[1], rad))
    F.polys.append((silp, "ball"))
    # the leaves of slope 0, 1, -1, infinity, and the leaf through P
    lamP = math.sqrt(2.0)
    base = [(0.0, "0"), (1.0, "1"), (-1.0, "-1"), (math.inf, r"\infty")]
    for lam, txt in base:
        th = math.pi / 2 if lam == math.inf else math.atan(lam)
        pts = [P2(x) for x in leaf_pts(th)]
        F.fill(pts, "PTeal,fill opacity=0.08", tag="leaf")
        F.path(pts, "PTeal", lw=0.95, tag="leaf")
    thP = math.atan(lamP)
    ptsP = [P2(x) for x in leaf_pts(thP)]
    F.fill(ptsP, "PClay,fill opacity=0.10", tag="leafP")
    F.path(ptsP, "PClay,dash pattern=on 2.6pt off 1.6pt", lw=0.95,
           tag="leafP")
    F.path(silp, "PSlate", lw=0.75, tag="ball")
    A0, A1 = P2((-R, 0, 0)), P2((R, 0, 0))
    F.path([A0, A1], "PInk", lw=1.3, tag="axis")
    F.mark(A0[0], A0[1], r=0.045, fill="PInk", tag="axis")
    F.mark(A1[0], A1[1], r=0.045, fill="PInk", tag="axis")
    # the point P on its leaf
    Pp = addv(smul(0.30, (1.0, 0, 0)), smul(-0.62, e2of(thP)))
    assert abs(Pp[2] - lamP * Pp[1]) < 1e-12 and norm(Pp) < R
    PP = P2(Pp)
    F.mark(PP[0], PP[1], r=0.06, fill="PClay", tag="P")
    XB = max(p[0] for p in silp)
    YB0, YB1 = min(p[1] for p in silp), max(p[1] for p in silp)

    # ---------------------------------------------------------- panel (b)
    # the slope dial: P^1(R), lambda -> angle 2 arctan(lambda); a tick for
    # each rational slope of height at most 8, of length 0.34 / height
    cx, cy, rd = XB + 3.05, YB1 - 0.98, 1.06
    ring = circle_pts(cx, cy, rd, 180)
    F.path(ring + [ring[0]], "PSlate", lw=0.6, tag="dial")
    S8 = slopes(8)
    assert len(S8) == 2 * sum(1 for p in range(1, 9) for q in range(1, 9)
                              if math.gcd(p, q) == 1) + 2
    for lam, (h, p, q) in S8.items():
        a = math.pi if lam == math.inf else 2 * math.atan(lam)
        L = 0.28 / h
        c, s_ = math.cos(a), math.sin(a)
        F.path([(cx + rd * c, cy + rd * s_), (cx + (rd - L) * c,
                                              cy + (rd - L) * s_)],
               "PTeal" if h <= 2 else "PTeal!65", lw=0.8 if h <= 2 else 0.4,
               tag="tick")
    aP = 2 * math.atan(lamP)
    c, s_ = math.cos(aP), math.sin(aP)
    F.path([(cx + rd * c, cy + rd * s_),
            (cx + (rd - 0.36) * c, cy + (rd - 0.36) * s_)], "PClay", lw=1.1,
           tag="tickP")
    F.mark(cx + rd * c, cy + rd * s_, r=0.05, fill="PClay", tag="tickP")
    F.text(cx, cy, r"$\lambda\in\PP^{1}(\RR)$", "PInk", FS, tag="dialname")

    # ---------------------------------------------------------- panel (c)
    bx0, by1 = XB + 1.55, YB0 + 1.62
    unit_ = 0.092
    rowh = 0.40
    for n in range(1, 7):
        y = by1 - (n - 1) * rowh
        a, b = n * (n + 1) // 2, n * (n - 1) // 2
        assert a + b == n * n
        F.rect(bx0, y - 0.11, bx0 + a * unit_, y + 0.11, "PTeal!70",
               tag="bar")
        if b:
            F.rect(bx0 + a * unit_, y - 0.11, bx0 + (a + b) * unit_,
                   y + 0.11, "PClay!70", tag="bar")
        F.text(bx0 - 0.12, y, r"$%d$" % n, "PInk", FS, anchor="east",
               tag="rowname")
        F.text(bx0 + n * n * unit_ + 0.10, y, r"$%d=%d+%d$" % (n * n, a, b),
               "PInk", FS, anchor="west", tag="rowval")
    F.text(bx0 - 0.12, by1 + 0.45, r"$n$", "PInk", FS, anchor="east",
           tag="rowname")
    F.text(bx0, by1 + 0.45, r"$n^{2}=\textcolor{PTeal!80!black}"
           r"{\binom{n+1}{2}}+\textcolor{PClay}{\binom{n}{2}}$",
           "PInk", FS, anchor="west", tag="rowname")

    # ---------------------------------------------------------- labels
    for lam, txt in base:
        th = math.pi / 2 if lam == math.inf else math.atan(lam)
        e2 = e2of(th)
        tip = max([smul(sg, e2) for sg in (1, -1)],
                  key=lambda c: dot(c, unit(eye)))
        F.request(P2(tip), r"$\lambda=%s$" % txt, "PTeal!80!black", SM,
                  region=(0, -9, XB + 0.9, 99))
    F.request(PP, r"$P$", "PClay", SM, clear=0.06,
              region=(0, -9, XB + 0.9, 99))
    tipP = max([smul(sg, e2of(thP)) for sg in (1, -1)],
               key=lambda c: -dot(c, unit(eye)) + 2 * c[2])
    F.request(P2(tipP), r"$\lambda=\sqrt{2}$", "PClay", SM,
              region=(0, -9, XB + 0.9, 99))
    F.request(A1, r"axis", "PInk", FS, clear=0.045,
              region=(0, -9, XB + 0.9, 99))
    F.request(P2(unit((0.0, -0.8, 0.9))), r"$\cD_{n,n}$", "PSlate", SM,
              region=(0, -9, XB + 0.9, 99))
    for lam, txt in ((0.0, "0"), (1.0, "1"), (math.inf, r"\infty"),
                     (-1.0, "-1"), (2.0, "2"), (-2.0, "-2"),
                     (0.5, r"\tfrac{1}{2}"), (-0.5, r"-\tfrac{1}{2}")):
        a = math.pi if lam == math.inf else 2 * math.atan(lam)
        c, s_ = math.cos(a), math.sin(a)
        F.request((cx + rd * c, cy + rd * s_), r"$%s$" % txt,
                  "PTeal!80!black", FS, prefer=math.degrees(a) % 360,
                  spread=30, rmin=0.14, rmax=0.3)
    F.request((cx + rd * math.cos(aP), cy + rd * math.sin(aP)),
              r"$\sqrt{2}$", "PClay", FS, clear=0.05,
              prefer=math.degrees(aP), spread=40, rmin=0.14, rmax=0.55)
    F.solve()
    top = max(YB1, cy + rd + 0.45)
    F.text(0.05, top, r"\textup{(a)}", "PInk", SM, anchor="north west",
           tag="letter")
    F.text(cx - rd - 0.85, top, r"\textup{(b)}", "PInk", SM,
           anchor="north west", tag="letter")
    F.text(bx0 - 0.62, by1 + 0.92, r"\textup{(c)}", "PInk", SM,
           anchor="west", tag="letter")
    return F


# ============================================================== fig_fibres
def fig_fibres():
    F = Plate("fig_fibres",
              "Lemma lem:annihilator at n = 3: the basis of wedge^2 H^{0,1} "
              "in three blocks, the mixed block the kernel of multiplication "
              "by omega; and the three dimensions for n = 2, ..., 6.",
              "make_plates.py")
    n = 3
    N = 2 * n
    c = 0.60
    X0, Y0 = 1.30, 7.50
    names = [r"u_{%d}" % (k + 1) for k in range(n)] + \
            [r"v_{%d}" % (k + 1) for k in range(n)]
    COL = {"++": "PIndigo", "+-": "PAmber", "--": "PMag"}

    def block(i, j):
        if j < n:
            return "++"
        if i < n:
            return "+-"
        return "--"
    count = {"++": 0, "+-": 0, "--": 0}
    for i in range(N):
        for j in range(N):
            x, y = X0 + j * c, Y0 - (i + 1) * c
            if i < j:
                b = block(i, j)
                count[b] += 1
                F.rect(x, y, x + c, y + c, "%s!%d" % (COL[b], 30 if b != "+-"
                                                      else 40),
                       tag=b, draw="white", lw=0.8)
            else:
                F.rect(x, y, x + c, y + c, "WSlate!55", tag="lower",
                       draw="white", lw=0.8)
    assert count == {"++": math.comb(n, 2), "+-": n * n,
                     "--": math.comb(n, 2)}
    # the outlines of the three blocks
    def outline(cells, col):
        edges = {}
        for i, j in cells:
            x, y = X0 + j * c, Y0 - (i + 1) * c
            for e in (((x, y), (x + c, y)), ((x + c, y), (x + c, y + c)),
                      ((x, y + c), (x + c, y + c)), ((x, y), (x, y + c))):
                k = tuple(sorted((round(a[0], 6), round(a[1], 6))
                                 for a in e))
                edges[k] = edges.get(k, 0) + 1
        for (p, q), m in edges.items():
            if m == 1:
                F.path([p, q], col, lw=1.1, tag="outline")
    for b in COL:
        outline([(i, j) for i in range(N) for j in range(N)
                 if i < j and block(i, j) == b], COL[b])
    # row and column names
    for k in range(N):
        F.text(X0 + (k + 0.5) * c, Y0 + 0.17, r"$%s$" % names[k], "PInk", FS,
               anchor="south", tag="names")
        F.text(X0 - 0.10, Y0 - (k + 0.5) * c, r"$%s$" % names[k], "PInk", FS,
               anchor="east", tag="names")
    # braces for V_+^{0,1} and V_-^{0,1}
    def hbrace(xa, xb, y, text, col):
        F.raw(r"  \draw[%s,line width=0.6pt,decorate,decoration={brace,"
              r"amplitude=3.2pt}] (%.3f,%.3f) -- (%.3f,%.3f);"
              % (col, xa, y, xb, y))
        F.segs.append(((xa, y), (xb, y + 0.13), "brace"))
        F.text((xa + xb) / 2, y + 0.19, text, col, FS, anchor="south",
               tag="bracename")

    def vbrace(x, ya, yb, text, col, side="L"):
        if side == "L":
            F.raw(r"  \draw[%s,line width=0.6pt,decorate,decoration={brace,"
                  r"amplitude=3.2pt}] (%.3f,%.3f) -- (%.3f,%.3f);"
                  % (col, x, ya, x, yb))
            F.segs.append(((x - 0.13, ya), (x, yb), "brace"))
            F.text(x - 0.19, (ya + yb) / 2, text, col, FS, anchor="east",
                   tag="bracename")
        else:
            F.raw(r"  \draw[%s,line width=0.6pt,decorate,decoration={brace,"
                  r"amplitude=3.2pt,mirror}] (%.3f,%.3f) -- (%.3f,%.3f);"
                  % (col, x, ya, x, yb))
            F.segs.append(((x, ya), (x + 0.13, yb), "brace"))
            F.text(x + 0.19, (ya + yb) / 2, text, col, FS, anchor="west",
                   tag="bracename")
    yb = Y0 + 0.52
    hbrace(X0 + 0.03, X0 + n * c - 0.03, yb, r"$V_{+}^{0,1}$", "PInk")
    hbrace(X0 + n * c + 0.03, X0 + N * c - 0.03, yb, r"$V_{-}^{0,1}$",
           "PInk")
    xb = X0 - 0.62
    vbrace(xb, Y0 - n * c + 0.03, Y0 - 0.03, r"$V_{+}^{0,1}$", "PInk")
    vbrace(xb, Y0 - N * c + 0.03, Y0 - n * c - 0.03, r"$V_{-}^{0,1}$",
           "PInk")
    # the dimensions, inside the blocks
    F.text(X0 + 2.5 * c, Y0 - 0.5 * c, r"$3$", "PIndigo!80!black", SM,
           allow=("++",), tag="dim")
    F.text(X0 + 4.5 * c, Y0 - 1.5 * c, r"$9$", "PAmber!70!black", SM,
           allow=("+-",), tag="dim")
    F.text(X0 + 5.5 * c, Y0 - 3.5 * c, r"$3$", "PMag!80!black", SM,
           allow=("--",), tag="dim")
    # the kernel of multiplication by omega: a brace on the right
    vbrace(X0 + N * c + 0.10, Y0 - n * c + 0.03, Y0 - 0.03,
           r"$\ker(\,\cdot\,\omega)$", "PAmber!80!black", side="R")
    YA0 = Y0 - N * c

    # ---------------------------------------------------------- panel (b)
    rows = list(range(2, 7))
    unit_ = 0.075
    rh = 0.42
    bx0 = 1.00
    by1 = YA0 - 1.30
    for k, m in enumerate(rows):
        y = by1 - k * rh
        a, b = math.comb(m, 2), m * m
        assert 2 * a + b == math.comb(2 * m, 2)
        x = bx0
        for v, col in ((a, "PIndigo!45"), (b, "PAmber!55"), (a, "PMag!40")):
            F.rect(x, y - 0.12, x + v * unit_, y + 0.12, col, tag="bar",
                   draw="white", lw=0.5)
            x += v * unit_
        F.text(bx0 - 0.12, y, r"$%d$" % m, "PInk", FS, anchor="east",
               tag="rowname")
        F.text(x + 0.10, y, r"$%d$" % math.comb(2 * m, 2), "PInk", FS,
               anchor="west", tag="rowval")
        F.text(bx0 + (a + b / 2) * unit_, y, r"$%d$" % b,
               "PAmber!40!black", FS, allow=("bar",), tag="inbar") \
            if b * unit_ > 0.28 else None
    F.text(bx0 - 0.12, by1 + 0.46, r"$n$", "PInk", FS, anchor="east",
           tag="rowname")
    F.text(bx0, by1 + 0.46,
           r"$\binom{2n}{2}=\textcolor{PIndigo}{\binom{n}{2}}"
           r"+\textcolor{PAmber!85!black}{n^{2}}"
           r"+\textcolor{PMag}{\binom{n}{2}}$", "PInk", FS, anchor="west",
           tag="rowname")
    F.text(0.0, Y0 + 1.20, r"\textup{(a)}", "PInk", SM, anchor="north west",
           tag="letter")
    F.text(0.0, by1 + 1.02, r"\textup{(b)}", "PInk", SM,
           anchor="north west", tag="letter")
    return F


def main(which=None):
    figs = {"fig_quadric": fig_quadric, "fig_lagsweep": fig_lagsweep,
            "fig_fibres": fig_fibres}
    for name, fn in figs.items():
        if which and name not in which:
            continue
        F = fn()
        F.write()


if __name__ == "__main__":
    main(sys.argv[1:])
