#!/usr/bin/env python3
"""
t2_split_model.py  (round 12, track T2)

Split model over Q of the Mumford representation: V = V1 (x) V2 (x) V3,
V_k = Q^2, G = SL(2)^3 acting factorwise, psi = eps (x) eps (x) eps.

Checks (exact integer / rational arithmetic unless a rank is taken mod p,
in which case the direction of the bound is stated and matched by an exact
bound in the other direction):

 (1) Casimir identity on V_k (x) V_k: sum_i x_i (x) x^i = P - 1/2 I for the
     trace form tr(xy) of sl(2) (P = swap).  Hence the partial swap s_k of
     the k-th tensor factor on V (x) V is Cas_k + 1/2, where Cas_k is the
     Casimir tensor of the k-th factor acting on V (x) V.
 (2) s_1, s_2, s_3 are G-equivariant commuting involutions of V (x) V, with
     s1 s2 s3 = full swap; the eight idempotents e_A = prod_{k in A}(1+s_k)/2
     prod_{k not in A}(1-s_k)/2 have ranks 1 (A empty: line of theta),
     9,9,9 (|A|=2: U_ij in wedge^2 V), 3,3,3 (|A|=1: T_k in Sym^2 V) and 27
     (A = {1,2,3}: Sym^2 V_1 Sym^2 V_2 Sym^2 V_3).
 (3) dim End_G(V (x) V) = 8.  Lower bound 8: the e_A are independent (exact).
     Upper bound 8: nullity of the linear system [X, g] = 0 computed mod a
     prime p is >= nullity over Q, and equals 8.
 (4) Lie algebra of the stabiliser in gl(V) of the Hodge classes of X x X in
     degrees 2 and 4 (psi, and the projectors onto theta, U_12, U_13, U_23
     in End(wedge^2 V)): h = {X : X^T psi + psi X = 0, [X(x)1+1(x)X, e_A] = 0
     for |A| even}.  dim h = 9 = dim g.  Lower bound: g satisfies the
     equations (exact).  Upper bound: nullity mod p = 9.
 (5) The algebra generated by the partial swaps s_k^{(i,i+1)} on V^{(x)3}
     has dimension 125 = dim End_G(V^{(x)3}).  Upper bound 125: the algebra
     lies in End_G(V^{(x)3}) = (x)_k End_SL2(V_k^{(x)3}), of dimension
     (1 + 2^2)^3 = 125 by Schur-Weyl (not recomputed here).  Lower bound: rank
     mod p of the spanning words (integer matrices), which is <= rank over Q.
"""
import sys
import numpy as np
from fractions import Fraction as Fr
from itertools import product

P = 1000003  # prime for modular ranks
PASS, FAIL = [], []


def check(name, cond):
    (PASS if cond else FAIL).append(name)
    print(("PASS " if cond else "FAIL ") + name)


def kron(*ms):
    out = np.array([[1]], dtype=object)
    for m in ms:
        out = np.kron(out, np.array(m, dtype=object))
    return out


I2 = [[1, 0], [0, 1]]
E = [[0, 1], [0, 0]]
F_ = [[0, 0], [1, 0]]
H = [[1, 0], [0, -1]]
EPS = [[0, 1], [-1, 0]]
I8 = kron(I2, I2, I2)


def in_factor(x, k):
    ms = [I2, I2, I2]
    ms[k] = x
    return kron(*ms)


g = [in_factor(x, k) for k in range(3) for x in (E, F_, H)]
psi = kron(EPS, EPS, EPS)

# (0) g preserves psi
check("g lies in sp(V,psi)", all(((x.T.dot(psi) + psi.dot(x)) == 0).all() for x in g))

# (1) Casimir identity on Q^2 (x) Q^2 with the trace form: dual of E is F, of F is E, of H is H/2
Pm = np.zeros((4, 4), dtype=object)
for a in range(2):
    for b in range(2):
        Pm[2 * b + a, 2 * a + b] = 1
cas2 = kron(E, F_) + kron(F_, E) + kron(H, H) * Fr(1, 2)
check("Casimir(sl2, trace form) = P - I/2 on V_k(x)V_k",
      ((cas2 - (Pm - np.eye(4, dtype=object) * Fr(1, 2))) == 0).all())

# operators on V (x) V; index (v, w) -> 8*v + w, v = 4*a1 + 2*a2 + a3
def partial_swap(k):
    S = np.zeros((64, 64), dtype=object)
    for v in range(8):
        for w in range(8):
            av = [(v >> 2) & 1, (v >> 1) & 1, v & 1]
            aw = [(w >> 2) & 1, (w >> 1) & 1, w & 1]
            av2, aw2 = av[:], aw[:]
            av2[k], aw2[k] = aw[k], av[k]
            v2 = 4 * av2[0] + 2 * av2[1] + av2[2]
            w2 = 4 * aw2[0] + 2 * aw2[1] + aw2[2]
            S[8 * v2 + w2, 8 * v + w] = 1
    return S


s = [partial_swap(k) for k in range(3)]
I64 = np.eye(64, dtype=object)


def rho2(x):
    return np.kron(x, I8) + np.kron(I8, x)


def cas_k(k):
    xs = [in_factor(E, k), in_factor(F_, k), in_factor(H, k)]
    duals = [in_factor(F_, k), in_factor(E, k), in_factor(H, k) * Fr(1, 2)]
    return sum(np.kron(a, b) for a, b in zip(xs, duals))


for k in range(3):
    check(f"s_{k+1} = Cas_{k+1} + 1/2 on V(x)V",
          ((s[k] - (cas_k(k) + I64 * Fr(1, 2))) == 0).all())
check("s_k are G-equivariant", all(((sk.dot(rho2(x)) - rho2(x).dot(sk)) == 0).all() for sk in s for x in g))
check("s_k involutions, commuting", all(((sk.dot(sk) - I64) == 0).all() for sk in s)
      and all(((s[i].dot(s[j]) - s[j].dot(s[i])) == 0).all() for i in range(3) for j in range(3)))
full_swap = partial_swap(0).dot(partial_swap(1)).dot(partial_swap(2))
Pfull = np.zeros((64, 64), dtype=object)
for v in range(8):
    for w in range(8):
        Pfull[8 * w + v, 8 * v + w] = 1
check("s1 s2 s3 = full swap", ((full_swap - Pfull) == 0).all())


def idem(A):
    if A in _IDEM:
        return _IDEM[A]
    M = I64.copy()
    for k in range(3):
        M = M.dot((I64 + s[k]) * Fr(1, 2) if k in A else (I64 - s[k]) * Fr(1, 2))
    _IDEM[A] = M
    return M


def rank_exact(M):
    M = [list(map(Fr, row)) for row in M]
    rows, cols = len(M), len(M[0])
    r = 0
    for c in range(cols):
        piv = None
        for i in range(r, rows):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        inv = 1 / M[r][c]
        M[r] = [x * inv for x in M[r]]
        for i in range(rows):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        r += 1
    return r


_IDEM = {}
subsets = [tuple(A) for n in range(4) for A in __import__("itertools").combinations(range(3), n)]
ranks = {}
for A in subsets:
    eA = idem(A)
    ranks[A] = int(sum(eA[i, i] for i in range(64)))  # trace = rank for idempotent
check("idempotent ranks: {}:1, pairs:9, singletons:3, {1,2,3}:27",
      ranks[()] == 1 and all(ranks[A] == 9 for A in subsets if len(A) == 2)
      and all(ranks[A] == 3 for A in subsets if len(A) == 1) and ranks[(0, 1, 2)] == 27)
check("|A| even lie in wedge^2 (full swap = -1), |A| odd in Sym^2",
      all(((Pfull.dot(idem(A)) - (idem(A) if len(A) % 2 else -idem(A))) == 0).all() for A in subsets))
# Hodge types: H^{1,0} = V1 V2 V3^{1,0}; the cocharacter acts on V_3 only; on wedge^2 V3 trivially,
# on S^2 V3 with weights 2,0,-2.  So e_A with 3 in A carries a (2,0) part: U_13,U_23,T_3,SSS.
exact_idems = np.array([idem(A).reshape(-1) for A in subsets], dtype=object)
check("the eight e_A are linearly independent over Q (exact)", rank_exact(exact_idems) == 8)


# ---------- modular nullity helpers
def rank_mod(M, p=P):
    M = np.array(M, dtype=np.int64) % p
    rows, cols = M.shape
    r = 0
    for c in range(cols):
        if r == rows:
            break
        nz = np.nonzero(M[r:, c])[0]
        if len(nz) == 0:
            continue
        piv = r + nz[0]
        if piv != r:
            M[[r, piv]] = M[[piv, r]]
        inv = pow(int(M[r, c]), p - 2, p)
        M[r] = (M[r] * inv) % p
        col = M[:, c].copy()
        col[r] = 0
        nzr = np.nonzero(col)[0]
        if len(nzr):
            M[nzr] = (M[nzr] - np.outer(col[nzr], M[r])) % p
        r += 1
    return r


def to_mod(M):
    """rational object matrix -> int matrix mod P"""
    out = np.zeros(M.shape, dtype=np.int64)
    for idx, x in np.ndenumerate(M):
        x = Fr(x)
        out[idx] = (x.numerator % P) * pow(x.denominator % P, P - 2, P) % P
    return out


# (3) commutant of g on V(x)V: unknown X (64x64); equations X rho2(x) - rho2(x) X = 0
def commutant_nullity(ops, n):
    blocks = []
    In = np.eye(n, dtype=np.int64)
    for A in ops:
        Am = to_mod(A)
        # vec(XA - AX) = (A^T (x) I - I (x) A) vec(X)  (column-major vec)
        blocks.append((np.kron(Am.T, In) - np.kron(In, Am)) % P)
    M = np.vstack(blocks)
    return n * n - rank_mod(M)


nul = commutant_nullity([rho2(x) for x in g], 64)
check(f"dim End_G(V(x)V) = 8 (nullity mod p = {nul} >= rational nullity >= 8)", nul == 8)

# (4) stabiliser Lie algebra of the Hodge classes of X x X in degrees 2 and 4
# unknown X in gl(V) (64 unknowns).  Conditions: X^T psi + psi X = 0 and
# [rho2(X), e_A] = 0 for |A| even (A = (), (0,1), (0,2), (1,2)).
idem_mod = {A: to_mod(idem(A)) for A in [(), (0, 1), (0, 2), (1, 2)]}
psi_mod = to_mod(psi)
I8m = np.eye(8, dtype=np.int64)
cols = []
for i in range(8):
    for j in range(8):
        Eij = np.zeros((8, 8), dtype=np.int64)
        Eij[i, j] = 1
        parts = [((Eij.T.dot(psi_mod) + psi_mod.dot(Eij)) % P).reshape(-1)]
        R = (np.kron(Eij, I8m) + np.kron(I8m, Eij)) % P
        for A, eA in idem_mod.items():
            parts.append(((R.dot(eA) - eA.dot(R)) % P).reshape(-1))
        cols.append(np.concatenate(parts))
Msys = np.array(cols, dtype=np.int64).T % P
nul_h = 64 - rank_mod(Msys)
check("g satisfies the stabiliser equations (exact)",
      all(((x.T.dot(psi) + psi.dot(x)) == 0).all() and
          all(((rho2(x).dot(idem(A)) - idem(A).dot(rho2(x))) == 0).all() for A in [(), (0, 1), (0, 2), (1, 2)])
          for x in g))
check(f"stabiliser Lie algebra of Hdg(XxX) in degrees <= 4 has dim 9 = dim g (nullity mod p = {nul_h})",
      nul_h == 9)

# (5) algebra generated by partial swaps on V^{(x)3}: dimension 125
def partial_swap3(k, pos):
    """swap the k-th factor between tensor positions pos, pos+1 of V^{(x)3} (dim 512)"""
    S = np.zeros((512, 512), dtype=np.int64)
    for idx in range(512):
        vs = [(idx >> 6) & 7, (idx >> 3) & 7, idx & 7]
        bits = [[(v >> 2) & 1, (v >> 1) & 1, v & 1] for v in vs]
        b2 = [b[:] for b in bits]
        b2[pos][k], b2[pos + 1][k] = bits[pos + 1][k], bits[pos][k]
        vs2 = [4 * b[0] + 2 * b[1] + b[2] for b in b2]
        S[64 * vs2[0] + 8 * vs2[1] + vs2[2], idx] = 1
    return S


gens = [partial_swap3(k, pos) for k in range(3) for pos in range(2)]


def algebra_dim(gens, n, cap):
    """dimension of the unital algebra generated, mod P (lower bound for the rational dim)"""
    basis_vecs = []
    echelon = []  # list of (pivot, row)
    def reduce(v):
        v = v % P
        for piv, row in echelon:
            if v[piv]:
                v = (v - v[piv] * row) % P
        return v
    def add(M):
        v = reduce(M.reshape(-1).copy())
        nz = np.nonzero(v)[0]
        if len(nz) == 0:
            return False
        piv = nz[0]
        v = (v * pow(int(v[piv]), P - 2, P)) % P
        # keep echelon rows reduced w.r.t. the new pivot for correctness of later reductions
        for t, (pv, row) in enumerate(echelon):
            if row[piv]:
                echelon[t] = (pv, (row - row[piv] * v) % P)
        echelon.append((piv, v))
        basis_vecs.append(M % P)
        return True
    add(np.eye(n, dtype=np.int64))
    frontier = [basis_vecs[0]]
    while frontier and len(basis_vecs) < cap:
        new = []
        for B in frontier:
            for Gm in gens:
                C = (Gm.dot(B)) % P
                if add(C):
                    new.append(basis_vecs[-1])
        frontier = new
    return len(basis_vecs)


d3 = algebra_dim(gens, 512, 200)
check(f"algebra generated by partial swaps on V^(x)3 has dim 125 (= 5^3, Schur-Weyl) [got {d3}]", d3 == 125)
I8i = np.eye(8, dtype=np.int64)
g3 = [np.kron(np.kron(x, I8i), I8i) + np.kron(np.kron(I8i, x), I8i) + np.kron(np.kron(I8i, I8i), x) for x in
      [xx.astype(np.int64) for xx in g]]
check("partial swaps on V^(x)3 commute with G", all(((S.dot(x) - x.dot(S)) == 0).all() for S in gens for x in g3))

print(f"\n{len(PASS)} checks passed, {len(FAIL)} failed")
sys.exit(1 if FAIL else 0)
