#!/usr/bin/env python3
"""Exact checks of the smooth-support statements folded into the working note.

The setting is a principally polarised abelian fourfold (X, Theta), a
squarefree d > 0 and the secant plane
    u = sum_k (-d)^k Theta^(2k)/(2k)!,   v = sum_k (-d)^k Theta^(2k+1)/(2k+1)!,
so that a u + b v is the Chern character of a secant object with rank a and
c_1 = b Theta.  A class xi in Q[Theta]/(Theta^5) is written by its
coefficients a_i(xi) of Theta^i/i!, and its binomial moments m_k(xi) are
defined by a_i = sum_k S(i,k) k! m_k.  Lambda is the subgroup generated by the
classes e^{j Theta} of the line bundles O(j Theta).

Everything is exact (sympy rationals).  Each check prints one line.
"""
import itertools
import math
import random
import sys

import sympy as sp

PASSED = []
FAILED = []


def check(name, ok):
    (PASSED if ok else FAILED).append(name)
    print(("ok   " if ok else "FAIL ") + name)


T, a, b, d, y, N = sp.symbols("Theta a b d y N")


def trunc(expr, var=T, deg=4):
    expr = sp.expand(expr)
    return sum(expr.coeff(var, i) * var**i for i in range(deg + 1))


def coeffs(xi):
    """a_i(xi): coefficient of Theta^i/i!."""
    xi = sp.expand(xi)
    return [sp.simplify(xi.coeff(T, i) * sp.factorial(i)) for i in range(5)]


def moments(xi):
    """Binomial moments from a_i = sum_k S(i,k) k! m_k."""
    A = coeffs(xi)
    m = []
    for k in range(5):
        rest = sum(sp.functions.combinatorial.numbers.stirling(k, j) * sp.factorial(j) * m[j]
                   for j in range(k))
        m.append(sp.simplify((A[k] - rest) / sp.factorial(k)))
    return m


def expT(j):
    return sum((j * T)**i / sp.factorial(i) for i in range(5))


u = sum((-d)**k * T**(2 * k) / sp.factorial(2 * k) for k in range(3))
v = sum((-d)**k * T**(2 * k + 1) / sp.factorial(2 * k + 1) for k in range(2))
u, v = trunc(u), trunc(v)

# ---------------------------------------------------------------------------
# (S1) the moments of a line bundle are binomial coefficients, and the
#      moments determine membership in Lambda.
ok = all(moments(expT(j)) == [sp.binomial(j, k) for k in range(5)] for j in range(-6, 7))
check("S1a m_k(e^{j Theta}) = binom(j,k) for -6 <= j <= 6", ok)

rng = random.Random(25)
ok = True
for _ in range(200):
    cs = {j: rng.randint(-5, 5) for j in range(-4, 5)}
    xi = sum(c * expT(j) for j, c in cs.items())
    ok &= all(sp.Rational(x).q == 1 for x in moments(xi))
check("S1b 200 random integer combinations of line bundles have integral moments", ok)

# converse: an integral moment vector is realised by sum_{j=0}^4 c_j e^{j Theta}
ok = True
for _ in range(100):
    target = [rng.randint(-9, 9) for _ in range(5)]
    M = sp.Matrix(5, 5, lambda k, j: sp.binomial(j, k))
    c = M.solve(sp.Matrix(target))
    ok &= all(x.q == 1 for x in c) and M.det() == 1
    xi = sum(c[j] * expT(j) for j in range(5))
    ok &= moments(xi) == target
check("S1c the moment map is unimodular on e^{0..4 Theta}: Lambda = integral moments", ok)

# ---------------------------------------------------------------------------
# (S2) the closed formula for the moments of the secant plane
m_sec = moments(a * u + b * v)
closed = [a, b, -(a * d + b) / 2, (3 * a * d + 2 * b - b * d) / 6,
          (a * d**2 - 11 * a * d + 6 * b * d - 6 * b) / 24]
check("S2 m(a u + b v) = (a, b, -(ad+b)/2, (3ad+2b-bd)/6, (ad^2-11ad+6bd-6b)/24)",
      all(sp.simplify(x - y_) == 0 for x, y_ in zip(m_sec, closed)))

# (S3) at (a,b) = (1,3): m = (1,3,-(d+3)/2,1,(d+9)(d-2)/24); membership iff d = 15,23 mod 24
m13 = [sp.factor(x.subs({a: 1, b: 3})) for x in m_sec]
ok = m13[3] == 1 and sp.simplify(m13[4] - (d + 9) * (d - 2) / 24) == 0
check("S3a m(u + 3v) = (1, 3, -(d+3)/2, 1, (d+9)(d-2)/24)", ok)
ok = True
for dd in range(1, 2400):
    integral = all(sp.Rational(x.subs(d, dd)).q == 1 for x in m13)
    ok &= integral == (dd % 24 in (15, 23))
check("S3b u + 3v in Lambda iff d = 15 or 23 mod 24 (every d < 2400)", ok)

# (S4) the witness d = 3, (a,b) = (1,1): moments (1,1,-2,4/3,-1/2), least multiple 6
m11 = [x.subs({a: 1, b: 1, d: 3}) for x in m_sec]
least = next(k for k in range(1, 100) if all(sp.Rational(k * x).q == 1 for x in m11))
check("S4 d=3, (a,b)=(1,1): moments (1,1,-2,4/3,-1/2), least multiple in Lambda is 6",
      m11 == [1, 1, -2, sp.Rational(4, 3), sp.Rational(-1, 2)] and least == 6)

# (S5) the fourth-moment defect at d = 1,3,5,7
defects = [sp.Rational(m13[4].subs(d, dd)) % 1 for dd in (1, 3, 5, 7)]
check("S5 defect of m_4(u+3v) mod Z at d=1,3,5,7 is 7/12, 1/2, 3/4, 1/3 (= -5/12, 1/2, 3/4, 1/3)",
      defects == [sp.Rational(7, 12), sp.Rational(1, 2), sp.Rational(3, 4), sp.Rational(1, 3)])

# (S6) a point, and Markman's normalisation count (d+9)(2d-1)
pt = T**4 / 24
check("S6a m(point) = (0,0,0,0,1/24)", moments(pt) == [0, 0, 0, 0, sp.Rational(1, 24)])
check("S6b (d+9)(d-2) + (d+9)(2d-1) = 3(d+9)(d-1) = 0 mod 24 for odd d < 2000",
      all((dd + 9) * (dd - 2) + (dd + 9) * (2 * dd - 1) == 3 * (dd + 9) * (dd - 1)
          and (3 * (dd + 9) * (dd - 1)) % 24 == 0 for dd in range(1, 2000, 2)))

# ---------------------------------------------------------------------------
# (S7) a smooth support: ch(O_S) = 1 - e^{-b Theta}(u + b v), by GRR
#      ch(O_S) = [S] - iota_*K_S/2 + (2 K_S^2 - c_2(N))/12 pt, c_2(N) = [S]^2.
def smooth_invariants(bb):
    chO = trunc(1 - trunc(expT(-bb) * (u + bb * v)))
    NN = sp.simplify(chO.coeff(T, 2))                  # [S] = N Theta^2
    iK = sp.simplify(-2 * chO.coeff(T, 3))             # iota_* K_S = iK Theta^3
    top = sp.simplify(chO.coeff(T, 4) * 24)            # ch_4 in units of pt
    S2 = 24 * NN**2                                    # [S]^2
    K2 = sp.expand(6 * top + S2 / 2)                   # (2K^2 - S2)/12 = top
    e = sp.expand(K2 - S2)                             # c_2(T_S) = c_1(N)^2 - c_2(N)
    Klam = 24 * iK                                     # K_S . lambda
    lam2 = 24 * NN                                     # lambda^2
    chi = sp.expand((K2 + e) / 12)                     # Noether
    return dict(chO=chO, N=NN, iK=iK, S2=S2, K2=K2, e=e, Klam=Klam, lam2=lam2, chi=chi)


I3 = smooth_invariants(3)
Nd = (d + 9) / 2
ok = (sp.simplify(I3["N"] - Nd) == 0 and sp.simplify(I3["iK"] - 4 * Nd) == 0)
check("S7a b=3: [S] = N Theta^2 with N = (d+9)/2 and iota_*K_S = 4N Theta^3", ok)
sub = {d: 2 * N - 9}
K2N = sp.expand(I3["K2"].subs(sub))
eN = sp.expand(I3["e"].subs(sub))
chiN = sp.expand(I3["chi"].subs(sub))
ok = (sp.expand(K2N - 12 * N * (36 - N)) == 0 and sp.expand(eN - 12 * N * (36 - 3 * N)) == 0
      and sp.expand(chiN - 4 * N * (18 - N)) == 0)
check("S7b K_S^2 = 12N(36-N), e(S) = 12N(36-3N), chi(O_S) = 4N(18-N)", ok)
table = {1: (5, 260, 1860, 1260, 480, 120), 3: (6, 288, 2160, 1296, 576, 144),
         5: (7, 308, 2436, 1260, 672, 168), 7: (8, 320, 2688, 1152, 768, 192)}
ok = all((I3["N"].subs(d, dd), I3["chi"].subs(d, dd), I3["K2"].subs(d, dd), I3["e"].subs(d, dd),
          I3["Klam"].subs(d, dd), I3["lam2"].subs(d, dd)) == row for dd, row in table.items())
check("S7c the four rows of the paper's table of smooth invariants are reproduced", ok)
mO = [sp.expand(x.subs(sub)) for x in moments(I3["chO"])]
ok = mO[:4] == [0, 0, N, -3 * N] and sp.expand(mO[4] - (N * (47 - 2 * N) / 12 + 3 * N)) == 0
check("S7d m(O_S) = (0, 0, N, -3N, N(47-2N)/12 + 3N)", ok)
check("S7e N(47-2N)/12 is not an integer for N = 5,6,7,8",
      all(sp.Rational(n * (47 - 2 * n), 12).q != 1 for n in (5, 6, 7, 8)))

# (S8) Lagrangian test: [S]^2 = e(S) iff 5N = 36 at b=3; in general iff N = 4b^2/5
ok = sp.solve(sp.Eq(24 * N**2, eN), N) == [0, sp.Rational(36, 5)]
check("S8a b=3: [S]^2 = e(S) only at N = 0 or 36/5, never at an integer N >= 1", ok)
bs = sp.symbols("bs", positive=True)
Ib = smooth_invariants(bs)
sol = sp.solve(sp.Eq(Ib["S2"], Ib["e"]), d)
Nsol = [sp.simplify(Ib["N"].subs(d, s)) for s in sol]
ok = (sp.Rational(3, 5) * bs**2 in sol
      and sp.simplify(Ib["N"].subs(d, sp.Rational(3, 5) * bs**2) - sp.Rational(4, 5) * bs**2) == 0)
first = next(bb for bb in range(1, 50) if (3 * bb * bb) % 5 == 0)
check("S8b general b: [S]^2 = e(S) at d = 3b^2/5, N = 4b^2/5; first integral case b=5, d=15",
      ok and first == 5 and sp.Rational(3 * 25, 5) == 15)

# (S9) delta = K_S - 4 lambda: iota_* delta = 0 and delta^2 = -12N(N-4); general b
d2 = sp.expand((I3["K2"] - 8 * I3["Klam"] + 16 * I3["lam2"]).subs(sub))
ok = sp.expand(d2 + 12 * N * (N - 4)) == 0 and sp.simplify(I3["iK"] - 4 * I3["N"]) == 0
check("S9a b=3: iota_*(K_S - 4 lambda) = 0 and (K_S - 4 lambda)^2 = -12N(N-4)", ok)
c = sp.simplify(Ib["iK"] / Ib["N"])
dsq = sp.simplify(Ib["K2"] - 2 * c * Ib["Klam"] + c**2 * Ib["lam2"])
Nb = sp.symbols("Nb")
dsqN = sp.simplify(dsq.subs(d, 2 * Nb - bs**2))
ok = (sp.simplify(c - sp.Rational(4, 3) * bs) == 0
      and sp.simplify(dsqN - sp.Rational(4, 3) * Nb * (4 * bs**2 - 9 * Nb)) == 0)
check("S9b general b: iota_*K_S = (4b/3) N Theta^3, (K_S - (4b/3) lambda)^2 = (4N/3)(4b^2 - 9N)", ok)

# (S10) Bloch's map: h^1(N) >= 8 - 2 chi(O_S) + 24 N^2
bounds = [8 - 2 * 4 * n * (18 - n) + 24 * n * n for n in (5, 6, 7, 8)]
# Hirzebruch-Riemann-Roch on S for rank 2 with c_1 = K_S: with KK = K_S^2 and
# chiO = chi(O_S) = td_2, chi(E) = [ (2 + c_1 + (c_1^2 - 2c_2)/2)(1 - K/2 + td_2) ]_2
KK, chiO, c2 = sp.symbols("KK chiO c2")
chiE = 2 * chiO + (-sp.Rational(1, 2)) * KK + (KK - 2 * c2) / 2
check("S10a chi(N_S) = 2 chi(O_S) - c_2(N) for rank 2 with c_1 = K_S (Riemann-Roch)",
      sp.expand(chiE - (2 * chiO - c2)) == 0)
check("S10b h^1(N) >= 88, 296, 568, 904 for N = 5, 6, 7, 8", bounds == [88, 296, 568, 904])
check("S10c dim H^1(T_X) = 16, polarised directions 10, annihilator 6 = dim Theta u H^{0,2}",
      4 * 4 == 16 and 4 * 5 // 2 == 10 and 16 - 10 == math.comb(4, 2))
gcds = [math.gcd(24 * n * n, 12 * n * (36 - 3 * n)) for n in (5, 6, 7, 8)]
check("S10d gcd([S]^2, e(S)) = 60, 432, 84, 384", gcds == [60, 432, 84, 384])

# ---------------------------------------------------------------------------
# (S11) the split Hilbert-Burch candidates of the paper's table satisfy the
#       power sums, at d = 23 and 15, which are 23 and 15 mod 24.
cands = [(23, (-11, -6, 0, 2, 7), (-10, -9, 5, 6)),
         (23, (-8, -4, -3, -2, 1, 6), (-7, -6, -6, 4, 5)),
         (15, (-8, -4, -4, -1, -1, 1, 4), (-7, -6, -6, 0, 3, 3))]
ok = True
hits = []
for dd, E0, E1 in cands:
    p = [e + 3 for e in E0]
    q = [f + 3 for f in E1]
    ck = [1, 3, -dd, -3 * dd, dd * dd]
    good = all(sum(x**k for x in p) - sum(x**k for x in q) == ck[k] for k in range(5))
    hits.append(good)
check("S11a the table's first candidates at r=4,5 (d=23) and r=6 (d=15) have the right power sums",
      hits[0] and hits[1] and hits[2])
# a small exhaustive search at r=2, 3 reproduces the paper's "no solution"
# there; by (S3b) any solution at any rank has d = 15 or 23 mod 24.
found = set()
for r in (2, 3):
    box = range(-6, 7)
    for p in itertools.combinations_with_replacement(box, r + 1):
        s1p = sum(p)
        for q in itertools.combinations_with_replacement(box, r):
            if s1p - sum(q) != 3:
                continue
            s2 = sum(x * x for x in p) - sum(x * x for x in q)
            dd = -s2
            if dd <= 0:
                continue
            if (sum(x**3 for x in p) - sum(x**3 for x in q) == -3 * dd
                    and sum(x**4 for x in p) - sum(x**4 for x in q) == dd * dd):
                found.add(dd)
check("S11b no split power-sum solution at r=2,3 with twists in [-6,6], for any d > 0",
      found == set())

print()
print(f"{len(PASSED)} checks passed, {len(FAILED)} failed")
sys.exit(1 if FAILED else 0)
