import Mathlib

/-!
# Slices of functions on a finite commutative group

`SIAt Ks f x` says that the restriction of `f` to the coset `x * ⟨Ks⟩` is a sum of functions,
the `K`-th of which is invariant under the subgroup `K`.  It is stated through iterated
differences, which is how it is used.
-/

open Finset

noncomputable section

namespace FermatHodge

open Classical

set_option linter.unusedSectionVars false

variable {G : Type*} [CommGroup G] [Fintype G]

/-- The subgroup generated by a list of subgroups. -/
def lspan : List (Subgroup G) → Subgroup G
  | [] => ⊥
  | K :: Ks => K ⊔ lspan Ks

@[simp] lemma lspan_nil : lspan ([] : List (Subgroup G)) = ⊥ := rfl
@[simp] lemma lspan_cons (K : Subgroup G) (Ks : List (Subgroup G)) :
    lspan (K :: Ks) = K ⊔ lspan Ks := rfl

lemma le_lspan_of_mem {K : Subgroup G} : ∀ {Ks : List (Subgroup G)}, K ∈ Ks → K ≤ lspan Ks
  | [], h => by simp at h
  | L :: Ls, h => by
      rcases List.mem_cons.mp h with rfl | h
      · exact le_sup_left
      · exact (le_lspan_of_mem h).trans le_sup_right

/-- The coset `x * lspan Ks`, as a finset. -/
def cosetF (Ks : List (Subgroup G)) (x : G) : Finset G :=
  univ.filter (fun z => x⁻¹ * z ∈ lspan Ks)

@[simp] lemma mem_cosetF {Ks : List (Subgroup G)} {x z : G} :
    z ∈ cosetF Ks x ↔ x⁻¹ * z ∈ lspan Ks := by
  simp [cosetF]

lemma self_mem_cosetF (Ks : List (Subgroup G)) (x : G) : x ∈ cosetF Ks x := by
  simp [one_mem]

lemma cosetF_nil (x : G) : cosetF [] x = {x} := by
  ext z; simp [inv_mul_eq_one, eq_comm]

lemma mem_cosetF_cons_of {K : Subgroup G} {Ks : List (Subgroup G)} {x c z : G} (hc : c ∈ K)
    (hz : z ∈ cosetF Ks (x * c)) : z ∈ cosetF (K :: Ks) x := by
  rw [mem_cosetF] at *
  have : x⁻¹ * z = c * ((x * c)⁻¹ * z) := by group
  rw [this, lspan_cons]; exact Subgroup.mul_mem_sup hc hz

lemma mul_mem_cosetF_cons {K : Subgroup G} {Ks : List (Subgroup G)} {x z k : G} (hk : k ∈ K)
    (hz : z ∈ cosetF (K :: Ks) x) : z * k ∈ cosetF (K :: Ks) x := by
  rw [mem_cosetF, lspan_cons] at *
  have : x⁻¹ * (z * k) = (x⁻¹ * z) * k := by group
  rw [this]
  exact (K ⊔ lspan Ks).mul_mem hz (Subgroup.mem_sup_left hk)

lemma mem_cosetF_cons {K : Subgroup G} {Ks : List (Subgroup G)} {x z : G} :
    z ∈ cosetF (K :: Ks) x ↔ ∃ c ∈ K, z ∈ cosetF Ks (x * c) := by
  constructor
  · intro hz
    rw [mem_cosetF, lspan_cons, Subgroup.mem_sup] at hz
    obtain ⟨c, hc, d, hd, h⟩ := hz
    refine ⟨c, hc, ?_⟩
    rw [mem_cosetF]
    have hz : z = x * (c * d) := by rw [h]; group
    have : (x * c)⁻¹ * z = d := by rw [hz]; group
    rw [this]; exact hd
  · rintro ⟨c, hc, hz⟩; exact mem_cosetF_cons_of hc hz

lemma mem_cosetF_of_mem_lspan {Ks : List (Subgroup G)} {y w k : G} (hw : w ∈ cosetF Ks y)
    (hk : k ∈ lspan Ks) : w * k ∈ cosetF Ks y := by
  rw [mem_cosetF] at *
  have : y⁻¹ * (w * k) = (y⁻¹ * w) * k := by group
  rw [this]; exact (lspan Ks).mul_mem hw hk

lemma cosetF_eq_of_mem {Ks : List (Subgroup G)} {x y : G} (hy : y ∈ cosetF Ks x) :
    cosetF Ks y = cosetF Ks x := by
  ext z
  rw [mem_cosetF, mem_cosetF] at *
  constructor
  · intro h
    have : x⁻¹ * z = (x⁻¹ * y) * (y⁻¹ * z) := by group
    rw [this]; exact (lspan Ks).mul_mem hy h
  · intro h
    have : y⁻¹ * z = (x⁻¹ * y)⁻¹ * (x⁻¹ * z) := by group
    rw [this]; exact (lspan Ks).mul_mem ((lspan Ks).inv_mem hy) h

lemma cosetF_disjoint {K : Subgroup G} {Ks : List (Subgroup G)} (hI : K ⊓ lspan Ks = ⊥)
    {x c c' : G} (hc : c ∈ K) (hc' : c' ∈ K) (hne : c ≠ c') :
    Disjoint (cosetF Ks (x * c)) (cosetF Ks (x * c')) := by
  rw [Finset.disjoint_left]
  intro z hz hz'
  rw [mem_cosetF] at hz hz'
  have h1 : c⁻¹ * c' ∈ lspan Ks := by
    have : c⁻¹ * c' = ((x * c)⁻¹ * z) * ((x * c')⁻¹ * z)⁻¹ := by group
    rw [this]; exact (lspan Ks).mul_mem hz ((lspan Ks).inv_mem hz')
  have h2 : c⁻¹ * c' ∈ K := K.mul_mem (K.inv_mem hc) hc'
  have h3 : c⁻¹ * c' ∈ K ⊓ lspan Ks := ⟨h2, h1⟩
  rw [hI, Subgroup.mem_bot, inv_mul_eq_one] at h3
  exact hne h3

/-- A subgroup as a finset. -/
def Kf (K : Subgroup G) : Finset G := univ.filter (· ∈ K)

@[simp] lemma mem_Kf {K : Subgroup G} {c : G} : c ∈ Kf K ↔ c ∈ K := by simp [Kf]

lemma card_Kf (K : Subgroup G) : ((Kf K).card : ℕ) = Nat.card K := by
  rw [Nat.card_eq_fintype_card, Kf, Fintype.card_subtype]

lemma cosetF_cons_eq {K : Subgroup G} {Ks : List (Subgroup G)} (x : G) :
    cosetF (K :: Ks) x = (Kf K).biUnion (fun c => cosetF Ks (x * c)) := by
  ext z; rw [mem_biUnion, mem_cosetF_cons]; simp only [mem_Kf]

lemma sum_cosetF_cons {K : Subgroup G} {Ks : List (Subgroup G)} (hI : K ⊓ lspan Ks = ⊥)
    (x : G) {M : Type*} [AddCommMonoid M] (φ : G → M) :
    ∑ z ∈ cosetF (K :: Ks) x, φ z = ∑ c ∈ Kf K, ∑ z ∈ cosetF Ks (x * c), φ z := by
  rw [cosetF_cons_eq, Finset.sum_biUnion]
  intro c hc c' hc' hne
  exact cosetF_disjoint hI (by simpa using hc) (by simpa using hc') hne

lemma mul_mem_cosetF {Ks : List (Subgroup G)} {y z : G} (k : G) (hz : z ∈ cosetF Ks y) :
    z * k ∈ cosetF Ks (y * k) := by
  rw [mem_cosetF] at *
  have : (y * k)⁻¹ * (z * k) = y⁻¹ * z := by
    rw [mul_inv_rev, mul_comm z k, mul_comm k⁻¹ y⁻¹]; group
  rw [this]; exact hz

lemma sum_cosetF_mul (Ks : List (Subgroup G)) (y k : G) {M : Type*} [AddCommMonoid M]
    (φ : G → M) :
    ∑ z ∈ cosetF Ks y, φ (z * k) = ∑ z ∈ cosetF Ks (y * k), φ z := by
  apply Finset.sum_nbij (· * k)
  · intro z hz; exact mul_mem_cosetF k hz
  · intro a _ b _ h; exact mul_right_cancel h
  · intro w hw
    refine ⟨w * k⁻¹, ?_, by simp⟩
    have := mul_mem_cosetF (Ks := Ks) k⁻¹ (Finset.mem_coe.mp hw)
    rw [mul_inv_cancel_right] at this
    exact Finset.mem_coe.mpr this
  · intro z _; rfl

/-- Iterated differences along the subgroups of `Ks` vanish on the coset of `x`. -/
def SIAt : List (Subgroup G) → (G → ℤ) → G → Prop
  | [], f, x => f x = 0
  | K :: Ks, f, x => ∀ c ∈ K, ∀ k ∈ K, SIAt Ks (fun z => f z - f (z * k)) (x * c)

/-- The subgroups in the list are independent. -/
def Indep : List (Subgroup G) → Prop
  | [] => True
  | K :: Ks => K ⊓ lspan Ks = ⊥ ∧ Indep Ks

lemma SIAt_congr : ∀ (Ks : List (Subgroup G)) (f g : G → ℤ) (x : G),
    (∀ z ∈ cosetF Ks x, f z = g z) → SIAt Ks f x → SIAt Ks g x
  | [], f, g, x, h, hf => by
      simp only [SIAt] at *; rw [← h x (self_mem_cosetF _ _)]; exact hf
  | K :: Ks, f, g, x, h, hf => by
      intro c hc k hk
      refine SIAt_congr Ks _ _ (x * c) ?_ (hf c hc k hk)
      intro z hz
      have hz1 := mem_cosetF_cons_of hc hz
      have hz2 := mul_mem_cosetF_cons hk hz1
      simp only [h z hz1, h (z * k) hz2]

lemma SIAt_zero : ∀ (Ks : List (Subgroup G)) (x : G), SIAt Ks (fun _ => 0) x
  | [], x => by simp [SIAt]
  | K :: Ks, x => by
      intro c _ k _
      exact SIAt_congr Ks (fun _ => 0) _ _ (fun z _ => by simp) (SIAt_zero Ks _)

lemma SIAt_of_zero (Ks : List (Subgroup G)) (f : G → ℤ) (x : G)
    (h : ∀ z ∈ cosetF Ks x, f z = 0) : SIAt Ks f x :=
  SIAt_congr Ks (fun _ => 0) f x (fun z hz => (h z hz).symm) (SIAt_zero Ks x)

/-- The `ℓ¹` mass of `f` on the coset of `x`. -/
def mass (Ks : List (Subgroup G)) (f : G → ℤ) (x : G) : ℤ := ∑ z ∈ cosetF Ks x, |f z|

lemma mass_nonneg (Ks : List (Subgroup G)) (f : G → ℤ) (x : G) : 0 ≤ mass Ks f x :=
  Finset.sum_nonneg (fun _ _ => abs_nonneg _)

lemma mass_cons {K : Subgroup G} {Ks : List (Subgroup G)} (hI : K ⊓ lspan Ks = ⊥)
    (f : G → ℤ) (x : G) : mass (K :: Ks) f x = ∑ c ∈ Kf K, mass Ks f (x * c) :=
  sum_cosetF_cons hI x _

lemma eq_zero_of_mass_eq_zero {Ks : List (Subgroup G)} {f : G → ℤ} {x : G}
    (h : mass Ks f x = 0) : ∀ z ∈ cosetF Ks x, f z = 0 := fun z hz =>
  abs_eq_zero.mp ((Finset.sum_eq_zero_iff_of_nonneg (fun _ _ => abs_nonneg _)).mp h z hz)

lemma abs_le_mass {Ks : List (Subgroup G)} {f : G → ℤ} {x z : G} (hz : z ∈ cosetF Ks x) :
    |f z| ≤ mass Ks f x :=
  Finset.single_le_sum (f := fun z => |f z|) (fun _ _ => abs_nonneg _) hz

lemma card_line {K' : Subgroup G} {Ks : List (Subgroup G)} (hK : K' ≤ lspan Ks) {y w : G}
    (hw : w ∈ cosetF Ks y) :
    ((cosetF Ks y).filter (fun z => w⁻¹ * z ∈ K')).card = Nat.card K' := by
  rw [← card_Kf]
  refine Finset.card_nbij (fun z => w⁻¹ * z) ?_ ?_ ?_
  · intro z hz
    have h2 : w⁻¹ * z ∈ K' := by simp_all
    simpa using h2
  · intro a _ b _ h; simpa using h
  · intro k hk
    have hk' : k ∈ K' := by simp_all
    refine ⟨w * k, ?_, by simp⟩
    have h3 : w * k ∈ (cosetF Ks y).filter (fun z => w⁻¹ * z ∈ K') :=
      Finset.mem_filter.mpr ⟨mem_cosetF_of_mem_lspan hw (hK hk'), by simpa using hk'⟩
    exact Finset.mem_coe.mpr h3

lemma mass_line {K' : Subgroup G} {Ks : List (Subgroup G)} (hK : K' ≤ lspan Ks) {y w : G}
    (hw : w ∈ cosetF Ks y) {σ : ℤ} (hσ : σ = 1 ∨ σ = -1) :
    ∑ z ∈ cosetF Ks y, |(if w⁻¹ * z ∈ K' then σ else 0 : ℤ)| = Nat.card K' := by
  have : ∀ z, |(if w⁻¹ * z ∈ K' then σ else 0 : ℤ)| = if w⁻¹ * z ∈ K' then 1 else 0 := by
    intro z; split_ifs <;> rcases hσ with rfl | rfl <;> simp
  simp only [this]
  rw [Finset.sum_boole, card_line hK hw]

end FermatHodge
