#!/usr/bin/env python3
"""
v2_lattice.py -- independent recomputation of the T4 lattice claims.
Lambda = Z-span of v(p,q) = (p^k q^(8-k))_{k=0..8} over ALL (p,q) in a box
(values of the degree-8 binary form [B_(p,q)] = sum_k p^k q^(8-k) C_k in the
coordinates C_k).  Index in Z^9 via sympy Smith normal form of a generating set
reduced by flint HNF (two libraries), stability in the box size, and
Lambda cap (Q w1 + Q w2) where w1 + delta w2 = P(1,-delta) in C_k-coordinates.
"""
import sys
from fractions import Fraction as Fr
from math import gcd
import flint
from sympy import Matrix
from sympy.matrices.normalforms import smith_normal_form
from sympy import ZZ


def lattice(H):
    vecs = [[p ** k * q ** (8 - k) for k in range(9)]
            for p in range(-H, H + 1) for q in range(-H, H + 1)]
    M = flint.fmpz_mat(vecs).hnf()
    rows = [[int(M[i, j]) for j in range(9)] for i in range(M.nrows())
            if any(M[i, j] != 0 for j in range(9))]
    return rows


for H in (6, 8, 10):
    rows = lattice(H)
    snf = smith_normal_form(Matrix(rows), domain=ZZ)
    diag = [int(snf[i, i]) for i in range(min(snf.shape))]
    idx = 1
    for x in diag:
        idx *= abs(x)
    print("H=%d: rank %d, Smith invariants %s, index %d" % (H, len(rows), diag, idx))

rows = lattice(10)
B = flint.fmpq_mat(rows)
Binv = B.inv()
for d in (1, 2, 3):
    w1 = [0] * 9
    w2 = [0] * 9
    for k in range(9):
        m = 8 - k
        # (-delta)^m = (-1)^m delta^m, delta^2 = -d
        c = (-1) ** m * (-d) ** (m // 2)
        if m % 2 == 0:
            w1[k] = c
        else:
            w2[k] = c
    a1 = flint.fmpq_mat([w1]) * Binv
    a2 = flint.fmpq_mat([w2]) * Binv
    A1 = [Fr(int(a1[0, j].p), int(a1[0, j].q)) for j in range(9)]
    A2 = [Fr(int(a2[0, j].p), int(a2[0, j].q)) for j in range(9)]
    # lattice L = {(x,y) in Q^2 : x A1 + y A2 in Z^9}.  Brute force a basis:
    # L contains N Z^2 for N = lcm of denominators; search the finite quotient.
    N = 1
    for z in A1 + A2:
        N = N * z.denominator // gcd(N, z.denominator)
    # (x,y) = (i/N', j/N') ... use exact: find all (x,y) in [0,1)^2 * scale? Use HNF on dual:
    # L = dual of lattice generated by columns (A1_j, A2_j) and Z^2.
    cols = [[int(A1[j] * N), int(A2[j] * N)] for j in range(9)] + [[N, 0], [0, N]]
    Hc = flint.fmpz_mat(cols).hnf()
    G = [[Fr(int(Hc[i, j]), N) for j in range(2)] for i in range(2)]
    det = G[0][0] * G[1][1] - G[0][1] * G[1][0]
    inv = [[G[1][1] / det, -G[0][1] / det], [-G[1][0] / det, G[0][0] / det]]
    dual = [[inv[j][i] for j in range(2)] for i in range(2)]
    # dual basis rows: vectors v with <v, g_i> integral; v = rows of (G^{-1})^T
    basis = [[str(dual[0][0]), str(dual[0][1])], [str(dual[1][0]), str(dual[1][1])]]
    # express in W = 24 w: divide by 24
    basisW = [[str(Fr(x) / 24) for x in r] for r in basis]
    # sanity: check each basis vector lies in Lambda
    ok = True
    for r in basis:
        v = [Fr(r[0]) * w1[k] + Fr(r[1]) * w2[k] for k in range(9)]
        a = flint.fmpq_mat([[flint.fmpq(x.numerator, x.denominator) for x in v]]) * Binv
        ok &= all(a[0, j].q == 1 for j in range(9))
    print("d=%d: Lambda cap Weil plane basis (x,y) in w-coords: %s ; in W=24w coords: %s ; members check %s"
          % (d, basis, basisW, ok))
