#!/usr/bin/env python3
"""
make_support.py

One plate for the support theorem of the semiregularity criterion.

  fig_support    the geometry of the proof, in one scene.  A sheet D stands
                 for a component of the support of codimension less than n,
                 which the theorem says must exist.  A curve Z above it stands
                 for a component of codimension at least two.  At a point p of
                 Z two translation directions are drawn, theta in T_+ and
                 theta' in T_-, together with the slice S that they span; S is
                 transverse to Z, so the restriction of E to S has finite
                 length cohomology, and its Euler characteristic is the
                 multiplicity m_Z(E).  The parallelogram spanned by theta and
                 theta' in S is the bivector whose product of jet classes the
                 lemma detects.  To the right, a torus with a marked point
                 carries the same complex, where the semiregularity map sees
                 that product as the Euler characteristic times the class of a
                 point contracted with a ^ b.  At the front, three parallel
                 lines are cosets of an abelian subvariety B tangent to T_+:
                 the only components of codimension at least two on which the
                 multiplicity may be nonzero.

The scene is schematic in the dimensions (a fourfold is drawn as space), and
exact in the incidences: S is spanned by the two drawn directions, it meets Z
in the one point p, and the normal projections of theta and theta' are
independent, which is the hypothesis under which the lemma applies.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render3d import Camera, Scene, sub, cross, unit, dot
from place import Placer

HEAD = r"""%% {name}.tex   (generated by make_support.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"


def write(name, blurb, sc, P):
    body = sc.emit()
    bad = P.check(body, sc.cam)
    if bad:
        raise SystemExit("placement failure in %s: %s" % (name, bad))
    labels = P.emit(body, sc.cam)
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, name + ".tex"), "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(labels)
        f.write(TAIL)
    print("%-18s %2d labels, clear of the ink and of each other"
          % (name, len(P.items)))


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def mul(t, a):
    return (t * a[0], t * a[1], t * a[2])


def sheet(x, y):
    return -1.25 + 0.20 * math.sin(0.9 * x) * math.cos(0.8 * y)


def gamma(t):
    return (-2.5 + 4.4 * t, 0.75 * math.sin(3.0 * t) - 0.35,
            0.30 + 0.50 * math.sin(2.4 * t))


def dgamma(t, h=1e-5):
    return mul(1.0 / (2 * h), sub(gamma(t + h), gamma(t - h)))


def fig_support():
    cam = Camera(eye=(6.8, -9.6, 5.6), target=(0.55, 0.05, -0.15),
                 focal=10.0, scale=2.45)
    sc, P = Scene(cam), Placer()

    # the sheet D: a component of codimension less than n
    sc.surface(lambda x, y: (x, y, sheet(x, y)), (-3.4, 3.1), (-2.3, 2.3),
               30, 22, base="PSlate", opacity=0.30, ambient=0.60,
               diffuse=0.34)
    for k in range(9):
        y = -2.3 + 4.6 * k / 8
        sc.curve(lambda x, y=y: (x, y, sheet(x, y)), (-3.4, 3.1), 40,
                 "PSlate!55,line width=0.18pt", priority=1, chunk=4)
    for k in range(11):
        x = -3.4 + 6.5 * k / 10
        sc.curve(lambda y, x=x: (x, y, sheet(x, y)), (-2.3, 2.3), 30,
                 "PSlate!55,line width=0.18pt", priority=1, chunk=4)

    # the curve Z: a component of codimension at least two
    sc.curve(gamma, (0.0, 1.0), 120, "PClay,line width=1.9pt", priority=3,
             chunk=2)
    # its shadow on D
    sc.curve(lambda t: (gamma(t)[0], gamma(t)[1],
                        sheet(gamma(t)[0], gamma(t)[1]) + 0.01),
             (0.0, 1.0), 80, "PClay!35,line width=0.6pt,"
             "dash pattern=on 1.2pt off 1.4pt", priority=2, chunk=2)

    # the point p, the tangent of Z, and a normal frame
    t0 = 0.47
    p = gamma(t0)
    tang = unit(dgamma(t0))
    n1 = unit(cross(tang, (0.0, 0.0, 1.0)))
    n2 = unit(cross(tang, n1))
    # theta in T_+ and theta' in T_-: chosen so that the slice they span
    # faces the viewer, and transverse to Z because the tangent of Z is not
    # in it
    view = unit(sub((0.55, 0.05, -0.15), (6.8, -9.6, 5.6)))
    e1 = unit(cross(view, (0.0, 0.0, 1.0)))
    e2 = unit(cross(view, e1))
    th = unit(add(add(mul(0.86, e1), mul(0.28, e2)), mul(0.42, view)))
    thp = unit(add(add(mul(-0.22, e1), mul(0.90, e2)), mul(-0.38, view)))
    assert abs(dot(tang, unit(cross(th, thp)))) > 0.3

    # the slice S through p spanned by theta and theta'
    R = 1.05
    sc.surface(lambda r, a: add(p, add(mul(r * math.cos(a), th),
                                       mul(r * math.sin(a), thp))),
               (0.0, R), (0.0, 2 * math.pi), 6, 28, base="PBlue",
               opacity=0.30, ambient=0.64, diffuse=0.30)
    sc.curve(lambda a: add(p, add(mul(R * math.cos(a), th),
                                  mul(R * math.sin(a), thp))),
             (0.0, 2 * math.pi), 60, "PBlue!70,line width=0.5pt", priority=2,
             chunk=3)

    # the parallelogram theta ^ theta' in S
    s = 0.70
    q0, q1, q2 = p, add(p, mul(s, th)), add(add(p, mul(s, th)), mul(s, thp))
    q3 = add(p, mul(s, thp))
    lift = mul(-0.02, view)
    sc.surface(lambda u, v: add(add(p, lift), add(mul(u, th), mul(v, thp))),
               (0.0, s), (0.0, s), 4, 4, base="PAmber", opacity=0.85,
               ambient=0.50, diffuse=0.42)
    for k in range(1, 5):
        w = s * k / 5
        sc.polyline([add(add(p, lift), mul(w, th)),
                     add(add(add(p, lift), mul(w, th)), mul(s, thp))],
                    "PAmber!70!black,line width=0.2pt", priority=4)
    sc.polyline([q0, q1, q2, q3, q0], "PAmber!90!black,line width=0.45pt",
                priority=4)

    # the two directions, and the tangent line of Z
    sc.arrow([p, add(p, mul(1.05, th))], "PBlue,line width=1.35pt", priority=6)
    sc.arrow([p, add(p, mul(1.05, thp))], "PMag,line width=1.35pt",
             priority=6)
    sc.polyline([add(p, mul(-0.8, tang)), add(p, mul(0.8, tang))],
                "PClay!70,line width=0.55pt,dash pattern=on 2pt off 1.5pt",
                priority=5)
    sc.dot3(p, "circle,fill=PInk,draw=white,line width=0.6pt,inner sep=1.9pt",
            priority=7)

    # cosets of an abelian subvariety B tangent to T_+, at the front right
    eB = unit((0.35, 1.0, 0.22))
    for k, x in enumerate((1.35, 1.95, 2.55)):
        base = (x, -1.55, -0.55 + 0.05 * k)
        a, b = add(base, mul(-0.2, eB)), add(base, mul(2.3, eB))
        sc.polyline([a, b], "PTeal,line width=1.6pt", priority=3)
        sc.polyline([(a[0], a[1], sheet(a[0], a[1]) + 0.01),
                     (b[0], b[1], sheet(b[0], b[1]) + 0.01)],
                    "PTeal!35,line width=0.5pt,dash pattern=on 1pt off 1.3pt",
                    priority=2)
    coset_anchor = add((2.55, -1.55, -0.45), mul(2.3, eB))

    # the torus T with a marked point, at the far right
    C = (4.6, 1.35, 0.35)
    Rt, rt = 0.78, 0.30

    def torus(u, v):
        return (C[0] + (Rt + rt * math.cos(v)) * math.cos(u),
                C[1] + (Rt + rt * math.cos(v)) * math.sin(u),
                C[2] + rt * math.sin(v))
    sc.surface(torus, (0.0, 2 * math.pi), (0.0, 2 * math.pi), 36, 16,
               base="PViolet", opacity=0.78, ambient=0.40, diffuse=0.52)
    tpt = torus(-1.25, 1.35)
    sc.dot3(tpt, "circle,fill=PInk,draw=white,line width=0.6pt,inner sep=1.7pt",
            priority=7)
    du = unit(sub(torus(-1.20, 1.35), torus(-1.30, 1.35)))
    dv = unit(sub(torus(-1.25, 1.40), torus(-1.25, 1.30)))
    sc.arrow([tpt, add(tpt, mul(0.42, du))], "PBlue,line width=1.0pt",
             priority=8)
    sc.arrow([tpt, add(tpt, mul(0.42, dv))], "PMag,line width=1.0pt",
             priority=8)
    # a transplant arrow from the slice to the torus
    mid = (2.9, 1.9, 1.6)
    sc.arrow([add(p, mul(0.2, thp)), mid, add(tpt, (-0.12, 0.0, 0.10))],
             "PInk!60,line width=0.6pt,dash pattern=on 2pt off 1.6pt",
             priority=5)

    P.add((-3.4, 2.3, sheet(-3.4, 2.3)),
          r"a component of codimension $<n$", "text=PSlate", side="L")
    P.add(gamma(0.02), r"$Z$, codimension $\ge 2$, multiplicity $m_{Z}(E)$",
          "text=PClay", side="L")
    P.add(p, r"$p$, a smooth point of $Z$", "text=PInk", side="L")
    P.add(add(p, mul(1.05, th)), r"$\theta\in T_{+}$", "text=PBlue", side="L")
    P.add(add(p, mul(1.05, thp)), r"$\theta'\in T_{-}$", "text=PMag",
          side="L")
    P.add(add(add(p, mul(-R, th)), mul(0.3 * R, thp)),
          r"the slice $S$: $\chi(E|_{S})=m_{Z}(E)$", "text=PBlue", side="L")
    P.add(add(add(p, mul(0.5 * s, th)), mul(0.5 * s, thp)),
          r"$\theta\wedge\theta'$, independent modulo $T_{p}Z$",
          "text=PAmber", side="R")
    P.add(mid, r"the same complex, carried to a torus", "text=PInk",
          side="R")
    P.add(torus(0.6, 0.0),
          r"$\sigma(A_{a}A_{b})=\chi\,(a\wedge b)\lrcorner[\mathrm{pt}]\ne0$",
          "text=PViolet", side="R")
    P.add(coset_anchor, r"cosets of $B$, $T_{0}B\supseteq T_{+}$", "text=PTeal",
          side="R")
    P.add((1.35, -1.55, -0.55),
          r"the only places $m_{Z}\ne0$ is allowed", "text=PTeal", side="R")

    write("fig_support",
          "The support theorem for the semiregularity criterion: a component "
          "of low codimension, a component Z, the slice S at p, the bivector, "
          "the torus, and the cosets of B.",
          sc, P)


if __name__ == "__main__":
    fig_support()
