#!/usr/bin/env python3
"""
make_round11.py

Three plates for the results added in round eleven.

  fig_descent     the web of Weil families for an imaginary quadratic field K
                  and a quartic CM field F containing it, one cell for each
                  dimension n and each of the two kinds of discriminant, grass
                  where the Weil classes are known to be algebraic and clay
                  where they are not.  The indigo arrows are the descent lemma
                  of prop:descent(i), from the trivial discriminant in
                  dimension n+1 to every discriminant in dimension n; the teal
                  arrows are the scalar extension of prop:descent(ii), from F
                  down to K.  The bracket marks the split families of the
                  field of higher degree, the only place where the propagation
                  statement is needed on the route of the paper.

  fig_hankel      the number that the polarised criterion asks of one complex,
                  r = (4 + rho) n^2 - 2n, against n for the four Hankel ranks
                  rho = 0, 1, 2, 3 (thm:p2primenumber), with the values
                  checked exactly over Q(i) for n <= 10 marked, and the seven
                  values that occur at n = 2.

  fig_kahlersign  the exceptional ratio at n = 2: for the class
                  gamma = omega + c theta^2 with R = c^2 int theta^4 /
                  int omega^2, the infimum over the Kaehler cone of
                  int gamma kappa^2 / (|c| sigma_2(h) int theta^4 / 6) is
                  m(R) = 1 - sqrt(3 / (4R)), from the identity of
                  rem:p2primeexceptional; it is negative exactly for R < 3/4,
                  which is where the Hodge locus jumps and the stabiliser
                  becomes so(4,3).

Every label is written as  \\node[...] at (x,y) {...};  so that checkfigs.py
can read it back and test it for overlaps.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_frontier import box, arrow, line, label, dot, TIP  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))

HEAD = r"""%% {name}.tex   (generated by make_round11.py; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc,decorations.pathreplacing}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk]
"""
TAIL = r"""\end{tikzpicture}
\end{document}
"""


# ------------------------------------------------------------------ descent
def descent():
    out = []
    rows = {1: 0.0, 2: 1.15, 3: 2.30, 4: 3.45, 5: 4.60}
    kx = {"triv": 1.0, "other": 3.3}
    fx = {"triv": 8.2, "other": 10.5}
    known_k = {(1, "triv"), (1, "other"), (2, "triv"), (2, "other"),
               (3, "triv")}
    known_f = {(1, "triv"), (1, "other")}
    text_k = {(1, "triv"): "divisors", (1, "other"): "divisors",
              (2, "triv"): "Markman", (2, "other"): "Markman",
              (3, "triv"): "Markman"}
    text_f = {(1, "triv"): "divisors", (1, "other"): "divisors"}
    w, h = 1.75, 0.62

    def cell(x, y, known, text):
        fill, draw = ("WTeal", "PGrass") if known else ("WClay", "PClay")
        return box(x, y, text, fill, draw, w=w, h=h, lw=0.7,
                   font=r"\scriptsize")

    for n, y in rows.items():
        for col in ("triv", "other"):
            out.append(cell(kx[col], y, (n, col) in known_k,
                            text_k.get((n, col), "open")))
            out.append(cell(fx[col], y, (n, col) in known_f,
                            text_f.get((n, col), "open")))
        out.append(label(-0.45, y, r"$n=%d$" % n, "PInk", anchor="east"))
    # descent: from (n+1, trivial) to (n, both)
    for n in (1, 2, 3, 4):
        y0, y1 = rows[n + 1] - h / 2 - 0.02, rows[n] + h / 2 + 0.02
        for base in (kx, fx):
            out.append(arrow((base["triv"] - 0.25, y0),
                             (base["triv"] - 0.25, y1), "PIndigo", lw=0.9))
            out.append(arrow((base["triv"] + 0.45, y0),
                             (base["other"] - 0.55, y1), "PIndigo", lw=0.9))
    # scalar extension: from F to K in every row
    for n, y in rows.items():
        out.append(arrow((fx["triv"] - w / 2 - 0.05, y + 0.12),
                         (kx["other"] + w / 2 + 0.05, y + 0.12), "PTeal",
                         lw=0.8, style=",dash pattern=on 3pt off 1.5pt"))
    # headers
    out.append(label(2.15, 5.80, r"$K=\QQ(\sqrt{-d})$", "PInk",
                     size=r"\small"))
    out.append(label(9.35, 5.80, r"$F\supset K$, a quartic CM field", "PInk",
                     size=r"\small"))
    for base in (kx, fx):
        out.append(label(base["triv"], 5.32, r"$\delta_{0}$", "PSlate"))
        out.append(label(base["other"], 5.32, r"$\delta\neq\delta_{0}$",
                         "PSlate"))
    # the split families of F: the one open premise of the route
    out.append(r"  \draw[PClay,line width=1.1pt,rounded corners=4pt,"
               r"dash pattern=on 4pt off 2pt] (%.2f,%.2f) rectangle (%.2f,%.2f);"
               % (fx["triv"] - w / 2 - 0.12, rows[2] - h / 2 - 0.12,
                  fx["triv"] + w / 2 + 0.12, rows[5] + h / 2 + 0.12) + "\n")
    out.append(label(fx["triv"] + 1.15, -0.62, r"dashed frame: (P2) for the "
                     r"split families of $F$, the one open premise of the "
                     r"route", "PClay", size=r"\tiny"))
    # legend
    y = -1.05
    out.append(box(0.55, y, r"known", "WTeal", "PGrass", w=1.2, h=0.45,
                   font=r"\scriptsize"))
    out.append(box(2.15, y, r"open", "WClay", "PClay", w=1.2, h=0.45,
                   font=r"\scriptsize"))
    out.append(arrow((3.35, y), (4.15, y), "PIndigo", lw=0.9))
    out.append(label(4.30, y, r"descent, (i):"
                     r" $\mathbf{W}(n+1,\delta_{0})\Rightarrow"
                     r"\mathbf{W}(n,\delta)$", "PInk", anchor="west"))
    y = -1.65
    out.append(arrow((3.35, y), (4.15, y), "PTeal", lw=0.8,
                     style=",dash pattern=on 3pt off 1.5pt"))
    out.append(label(4.30, y, r"scalar extension, (ii):"
                     r" $\mathbf{W}(F,n,\iota\delta)\Rightarrow"
                     r"\mathbf{W}(K,n,\delta)$", "PInk", anchor="west"))
    return "".join(out)


# ------------------------------------------------------------------- hankel
def hankel():
    out = []
    H = 5.0 / 700.0
    dx = 1.0
    X = lambda n: (n - 2) * dx
    cols = {0: "PSlate", 1: "PTeal", 2: "POchre", 3: "PClay"}
    for v in range(100, 701, 100):
        out.append(line([(-0.3, v * H), (8.3, v * H)], "PRule!60", lw=0.3))
        out.append(label(-0.45, v * H, r"$%d$" % v, "PSlate", anchor="east",
                         size=r"\tiny"))
    out.append(line([(-0.3, 0.0), (8.3, 0.0)], "PInk", lw=0.6))
    out.append(line([(-0.3, 0.0), (-0.3, 5.15)], "PInk", lw=0.6))
    for n in range(2, 11):
        out.append(line([(X(n), 0.0), (X(n), -0.08)], "PInk", lw=0.5))
        out.append(label(X(n), -0.32, r"$%d$" % n, "PInk"))
    out.append(label(4.0, -0.80, r"half the dimension $n$ of the abelian "
                     r"$2n$-fold", "PInk"))
    out.append(label(-1.35, 2.5, r"$r(\gamma)=\dim\mathrm{Ext}^{2}(E,E)$"
                     r" asked for", "PInk", extra=",rotate=90"))
    for rho in (0, 1, 2, 3):
        pts = []
        steps = 64
        for i in range(steps + 1):
            n = 2 + 8.0 * i / steps
            pts.append((X(n), ((4 + rho) * n * n - 2 * n) * H))
        out.append(line(pts, cols[rho], lw=1.0))
        for n in range(3, 11):
            out.append(dot(X(n), ((4 + rho) * n * n - 2 * n) * H, cols[rho],
                           r=1.5))
        v10 = (4 + rho) * 100 - 20
        out.append(label(8.45, v10 * H, r"$\rho=%d$: $%d$" % (rho, v10),
                         cols[rho], anchor="west"))
    # the general shape at small n
    for n, v in ((3, 57), (4, 104)):
        out.append(label(X(n) - 0.30, v * H + 0.30, r"$%d$" % v, "PClay",
                         size=r"\tiny"))
    out.append(dot(X(2), 24 * H, "PClay", r=1.5, hollow=True))
    out.append(label(3.95, 5.60, r"$(4+\rho)\,n^{2}-2n$, exact over $\QQ(i)$ "
                     r"for $n\le10$", "PInk"))
    out.append(label(3.05, 4.45, r"at $n=2$: $r\in\{12,16,18,20,22,23,24\}$,"
                     r"\\$24$ for a general shape", "PClay", size=r"\tiny"))
    out.append(label(3.05, 3.70, r"pure form $\rho=0$: $2n(2n-1)$,\\"
                     r"never met: the Weil tori obstruction", "PSlate", size=r"\tiny"))
    return "".join(out)


# --------------------------------------------------------------- kahlersign
def kahlersign():
    out = []
    sx, sy = 2.0, 2.0
    X = lambda R: R * sx
    Y = lambda m: m * sy
    out.append(r"  \fill[WClay] (%.2f,%.2f) rectangle (%.2f,%.2f);"
               % (X(0.15), Y(-1.30), X(0.75), Y(1.05)) + "\n")
    out.append(r"  \fill[WTeal] (%.2f,%.2f) rectangle (%.2f,%.2f);"
               % (X(0.75), Y(-1.30), X(4.0), Y(1.05)) + "\n")
    for m in (-1.0, -0.5, 0.5, 1.0):
        out.append(line([(X(0.0), Y(m)), (X(4.0), Y(m))], "PRule!60", lw=0.3))
        out.append(label(X(0.0) - 0.15, Y(m), r"$%g$" % m, "PSlate",
                         anchor="east", size=r"\tiny"))
    out.append(line([(X(0.0), Y(0.0)), (X(4.1), Y(0.0))], "PInk", lw=0.6))
    out.append(label(X(0.0) - 0.15, Y(0.0), r"$0$", "PSlate", anchor="east",
                     size=r"\tiny"))
    out.append(line([(X(0.0), Y(-1.30)), (X(0.0), Y(1.05))], "PInk", lw=0.6))
    for R in (1, 2, 3, 4):
        out.append(line([(X(R), Y(-1.30)), (X(R), Y(-1.36))], "PInk", lw=0.5))
        out.append(label(X(R), Y(-1.30) - 0.30, r"$%d$" % R, "PInk"))
    pts = []
    steps = 160
    for i in range(steps + 1):
        R = 0.2 + (4.0 - 0.2) * i / steps
        pts.append((X(R), Y(1.0 - math.sqrt(3.0 / (4.0 * R)))))
    out.append(line(pts, "PIndigo", lw=1.2))
    out.append(line([(X(0.75), Y(-1.30)), (X(0.75), Y(1.05))], "PMag", lw=0.7,
                    style=",dash pattern=on 3pt off 2pt"))
    out.append(dot(X(0.75), Y(0.0), "PMag", r=2.0))
    out.append(line([(X(3.0), Y(-1.30)), (X(3.0), Y(0.5))], "POchre", lw=0.6,
                    style=",dash pattern=on 2pt off 2pt"))
    out.append(dot(X(3.0), Y(0.5), "POchre", r=1.8))
    out.append(label(X(2.35), Y(-1.30) - 0.85, r"the ratio $R=c^{2}\!\int"
                     r"\theta^{4}\big/\!\int\omega^{2}$ at $n=2$", "PInk"))
    out.append(label(-1.10, Y(-0.10), r"$m(R)=\inf_{\kappa}\,\frac{6\int"
                     r"\gamma\kappa^{2}}{|c|\,\sigma_{2}\int\theta^{4}}$",
                     "PInk", extra=",rotate=90"))
    out.append(label(X(2.1), Y(1.30), r"$m(R)=1-\sqrt{3/(4R)}$: the sign of"
                     r" $\int\gamma\kappa^{2}$ is constant on the K\"ahler cone"
                     r" exactly for $R\ge3/4$", "PIndigo"))
    out.append(label(X(0.75) + 0.12, Y(-0.55), r"$R=3/4$:\\Hodge locus of"
                     r" dim.\ $5$,\\stabiliser $\mathfrak{so}(4,3)$,"
                     r"\\$r(\gamma)=23$", "PMag", anchor="west",
                     size=r"\tiny"))
    out.append(label(X(3.0) + 0.12, Y(-0.55), r"$R=3$:\\$r(\gamma)=22$,"
                     r"\\annihilator\\of dim.\ $6$", "POchre",
                     anchor="west", size=r"\tiny"))
    out.append(label(X(0.45), Y(-1.05), r"sign\\changes", "PClay",
                     size=r"\tiny"))
    return "".join(out)


def write(name, blurb, body):
    path = os.path.join(HERE, name + ".tex")
    with open(path, "w") as f:
        f.write(HEAD.format(name=name, blurb=blurb))
        f.write(body)
        f.write(TAIL)
    print("wrote", path)


if __name__ == "__main__":
    write("fig_descent",
          "The web of Weil families linked by descent and scalar extension.",
          descent())
    write("fig_hankel",
          "The number that the polarised criterion asks of one complex.",
          hankel())
    write("fig_kahlersign",
          "The sign of int gamma kappa^2 on the Kaehler cone at n = 2.",
          kahlersign())
