#!/usr/bin/env python3
"""
make_core.py

The figures of the sections on the explicit Weil classes, the character
grading, the divisor obstruction and the annihilator, each drawn from the
data the paper computes.

  fig_weilcube      the 2^{2n} = 16 monomials w^(T) at n = 2 as the vertices
                    of the 4-cube under the linear projection e_j -> (a_j, 1),
                    a = (-9, -1, 3, 7)/4, so that the height of w^(T) is |T|,
                    the edges of one direction x_j -> y_j are parallel, and the
                    middle row is evenly spaced; each vertex is the monomial
                    itself, in the colour of its class, and each level carries
                    its class and the one coefficient of eq:n2omega1-2, all
                    read off the product d^{-2} prod (d x_j + delta y_j)
  fig_hodgespike    dim Hdg^k(A) over k and n = 2, 3, 4 (thm:hdgcount): one
                    class eta^k in every degree 0 <= k <= 2n, the strip of
                    each row marking that range, and the two dimensions of the
                    Weil line stacked on it at k = n; the view is turned so
                    that each row falls between the bars of the row in front
  fig_charactergrid the K^x-grading of H^*(A,C) at n = 3 on the grid of pairs
                    (r,s), with the summands of H^{2n} raised to their true
                    dimensions C(6,r)C(6,6-r), each named by its character and
                    dimension in the free cell in front of it; the Weil line at
                    the two ends of the antidiagonal, Nm(tau)^3 and eta^3 in
                    the middle, and eta^k on the diagonal of the norm
                    characters; the view is chosen by casting rays so that no
                    bar hides another bar or the name of a diagonal cell
  fig_chernline     the Weil line W(A) as the plane of omega_1, omega_2 at
                    n = 2, K = Q(sqrt(-2)), with the orbit tau^{4k} omega_1 of
                    omega_1 under the powers of tau = 1 + sqrt(-2)/4, acting
                    through the rational matrix of tau^4 (thm:explicitgens
                    (iv)), on its logarithmic spiral, the level curve Nm = 1
                    of the norm form, and the transverse axis Q eta^2 with the
                    orbit Nm(tau)^{2k} eta^2
  fig_annihilator   H^{0,2} = wedge^2 H^{0,1} at n = 3 as the strict upper
                    triangle of the 6 x 6 array on u_1, u_2, u_3, v_1, v_2, v_3,
                    every product e_i ^ e_j in its cell, the three blocks of
                    lem:annihilator outlined, and beside each block what
                    z -> z.omega does to it
  fig_witness       the values c(tau)^n = (tau/conj tau)^n, n = 0..12, on the
                    unit circle for bad and good witnesses at d = 1 and d = 3,
                    stacked over n as a helix; the characters tau^{2n} and
                    Nm^n agree at tau exactly where the helix meets the line
                    c^n = 1 (lem:charsdiffer, rem:witness)

Every label is written as  \\node[lbl,...] at (x,y) {...};  so that
checkfigs.py can read it back.  In addition each figure is audited against its
own raster before it is written: the exact box of every label is read from
TeX, the drawing without its labels is rasterised, and a label is rejected if
any ink lies under it, if it meets another label, or if a leader line crosses
ink, another label or another leader.
"""
import itertools
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from render3d import Camera, sub, addv, smul, dot, cross, unit, norm  # noqa

import numpy as np

PT = 72.27 / 2.54            # TeX points per centimetre
BORDER = 8.0                 # the standalone border, in pt

HEAD = r"""%% {name}.tex   (generated by {gen}; do not edit by hand)
%% {blurb}
\documentclass[tikz,border=8pt]{{standalone}}
\usepackage{{amsmath,amssymb}}
\usetikzlibrary{{arrows.meta,calc,decorations.pathreplacing}}
\input{{palette}}
\begin{{document}}
\begin{{tikzpicture}}[x=1cm,y=1cm,line join=round,line cap=round,
  font=\small,text=PInk,lbl/.style={{inner sep=1pt}}]
"""
TAIL = "\\end{tikzpicture}\n\\end{document}\n"
LEADER = "PSlate!85,line width=0.35pt"
TIPS = "-{Stealth[length=4.2pt,width=3.2pt]}"


def binom(n, k):
    if k < 0 or k > n:
        return 0
    r = 1
    for i in range(k):
        r = r * (n - i) // (i + 1)
    return r


def f4(v):
    return "%.4f" % v


# ====================================================================== Fig
class Fig:
    """A figure: 3D items sorted by depth, flat ink, leaders and labels."""

    def __init__(self, name, blurb, cam=None, gen="make_core.py",
                 light=(0.45, -0.70, 0.85)):
        self.name, self.blurb, self.gen, self.cam = name, blurb, gen, cam
        self.light = unit(light)
        self.items = []          # (depth, priority, tikz)
        self.pre = []            # flat ink under the 3D items
        self.post = []           # flat ink over the 3D items
        self.labels = []         # dict(x, y, anchor, text, style)
        self.leaders = []        # dict(a, b, free, style, dot)

    # ---------------------------------------------------------- projection
    def P(self, p):
        return self.cam.project(p)[0]

    def D(self, p):
        return self.cam.project(p)[1]

    def path(self, pts):
        return " -- ".join("(%s,%s)" % (f4(q[0]), f4(q[1]))
                           for q in (self.P(p) for p in pts))

    def add(self, depth, tikz, prio=0):
        self.items.append((depth, prio, tikz))

    # ------------------------------------------------------------- shading
    def tone(self, nrm, base, lo=22, hi=78, amb=0.30, dif=0.70):
        """Lambert shading of a face with outward normal nrm, as a tint of
        base: lo per cent for a face turned to the light, hi for one turned
        away."""
        lam = max(0.0, dot(unit(nrm), self.light))
        inten = amb + dif * lam
        pct = hi - (hi - lo) * inten
        return "%s!%d!white" % (base, int(round(max(8, min(95, pct)))))

    def facing(self, centre, nrm):
        return dot(nrm, sub(self.cam.eye, centre)) > 0

    # --------------------------------------------------------------- solids
    def prism_tikz(self, lo, hi, base, edge=None, lw=0.32, opacity=None,
                   tones=None):
        """The visible faces of the box [lo, hi], shaded, as TikZ."""
        x0, y0, z0 = lo
        x1, y1, z1 = hi
        faces = [
            ((0, 0, -1), [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0)]),
            ((0, 0, 1), [(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]),
            ((0, -1, 0), [(x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1)]),
            ((0, 1, 0), [(x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)]),
            ((-1, 0, 0), [(x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1)]),
            ((1, 0, 0), [(x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1)]),
        ]
        out = []
        edge = edge or "%s!65!black" % base
        op = ("fill opacity=%.2f," % opacity) if opacity else ""
        for nrm, pts in faces:
            c = smul(0.25, (sum(p[0] for p in pts), sum(p[1] for p in pts),
                            sum(p[2] for p in pts)))
            if not self.facing(c, nrm):
                continue
            fill = (tones or {}).get(nrm) or self.tone(nrm, base)
            out.append("  \\path[%sfill=%s,draw=%s,line width=%.2fpt] %s -- cycle;\n"
                       % (op, fill, edge, lw, self.path(pts)))
        return "".join(out)

    def prism(self, lo, hi, base, prio=0, **kw):
        c = smul(0.5, addv(lo, hi))
        self.add(self.D(c), self.prism_tikz(lo, hi, base, **kw), prio)

    def stack(self, x0, y0, dx, dy, segs, prio=0, **kw):
        """A column of boxes [z_a, z_b] with colours, drawn bottom up as one
        item, so that the painter keeps them in order."""
        out = []
        for za, zb, base in segs:
            out.append(self.prism_tikz((x0, y0, za), (x0 + dx, y0 + dy, zb),
                                       base, **kw))
        c = (x0 + dx / 2, y0 + dy / 2, 0.5 * (segs[0][0] + segs[-1][1]))
        self.add(self.D(c), "".join(out), prio)

    def poly3(self, pts, fill=None, draw=None, lw=0.3, opacity=None,
              prio=0, depth=None, extra=""):
        opts = []
        if opacity is not None:
            opts.append("fill opacity=%.2f" % opacity)
        opts.append("fill=%s" % fill if fill else "fill=none")
        opts.append("draw=%s" % draw if draw else "draw=none")
        opts.append("line width=%.2fpt" % lw)
        if extra:
            opts.append(extra)
        d = depth if depth is not None else sum(self.D(p) for p in pts) / len(pts)
        self.add(d, "  \\path[%s] %s -- cycle;\n" % (",".join(opts),
                                                    self.path(pts)), prio)

    def line3(self, pts, style, prio=1, depth=None):
        d = depth if depth is not None else sum(self.D(p) for p in pts) / len(pts)
        self.add(d, "  \\draw[%s] %s;\n" % (style, self.path(pts)), prio)

    def curve3(self, pts, style, prio=1, chunk=6, depth=None):
        """A sampled curve, cut into short depth-sorted runs."""
        k = 0
        while k < len(pts) - 1:
            m = min(k + chunk, len(pts) - 1)
            seg = pts[k:m + 1]
            self.line3(seg, style, prio, depth)
            k = m

    def dot3(self, p, fill, r=1.6, ring="white", prio=3, depth=None):
        x, y = self.P(p)
        d = depth if depth is not None else self.D(p)
        self.add(d, "  \\fill[%s,draw=%s,line width=0.45pt] (%s,%s) circle "
                    "(%.2fpt);\n" % (fill, ring, f4(x), f4(y), r), prio)

    # ------------------------------------------------------------ flat ink
    def flat(self, tikz, under=False):
        (self.pre if under else self.post).append(tikz)

    # --------------------------------------------------------------- labels
    def label(self, x, y, text, anchor="center", color="PInk", font=None,
              extra=""):
        self.labels.append(dict(x=x, y=y, text=text, anchor=anchor,
                                color=color, font=font, extra=extra))
        return len(self.labels) - 1

    def label3(self, p, text, dx=0.0, dy=0.0, **kw):
        x, y = self.P(p)
        return self.label(x + dx, y + dy, text, **kw)

    def tick(self, p, q, text, gap=0.10, **kw):
        """A tick from p to q (3D) with its label beyond q, in the screen
        direction of the tick, anchored on the side facing the tick."""
        a, b = self.P(p), self.P(q)
        dx, dy = b[0] - a[0], b[1] - a[1]
        L = math.hypot(dx, dy)
        dx, dy = dx / L, dy / L
        ang = math.degrees(math.atan2(dy, dx)) % 360
        names = ["west", "south west", "south", "south east", "east",
                 "north east", "north", "north west"]
        anchor = names[int(((ang + 22.5) % 360) // 45)]
        self.line3([p, q], "PInk,line width=0.35pt", prio=5, depth=-1)
        return self.label(b[0] + gap * dx, b[1] + gap * dy, text,
                          anchor=anchor, **kw)

    def edge_ticks(self, p0, p1, ts, texts, out, length=0.12, gap=0.06,
                   font=r"\footnotesize", color="PInk"):
        """Ticks on the 3D segment p0 p1 at the parameters ts, drawn in the
        screen direction perpendicular to the projected segment on the side
        of the screen point `out`, with their labels beyond them."""
        a, b = self.P(p0), self.P(p1)
        ex, ey = b[0] - a[0], b[1] - a[1]
        L = math.hypot(ex, ey)
        nx, ny = -ey / L, ex / L
        if (out[0] - a[0]) * nx + (out[1] - a[1]) * ny < 0:
            nx, ny = -nx, -ny
        ang = math.degrees(math.atan2(ny, nx)) % 360
        names = ["west", "south west", "south", "south east", "east",
                 "north east", "north", "north west"]
        anchor = names[int(((ang + 22.5) % 360) // 45)]
        for t, text in zip(ts, texts):
            p = tuple(p0[i] + t * (p1[i] - p0[i]) for i in range(3))
            x, y = self.P(p)
            self.flat("  \\draw[PInk,line width=0.35pt] (%s,%s) -- (%s,%s);\n"
                      % (f4(x), f4(y), f4(x + length * nx), f4(y + length * ny)))
            self.label(x + (length + gap) * nx, y + (length + gap) * ny, text,
                       anchor=anchor, font=font, color=color)
        return nx, ny

    def swatch(self, x, y, base, text, size=0.24, color="PInk", gap=0.14,
               font=None):
        """A legend entry: a shaded square at (x,y) and its text."""
        h = size / 2
        self.flat("  \\path[fill=%s!38!white,draw=%s!65!black,line width=0.32pt]"
                  " (%s,%s) rectangle (%s,%s);\n"
                  % (base, base, f4(x - h), f4(y - h), f4(x + h), f4(y + h)))
        return self.label(x + h + gap, y, text, anchor="west", color=color,
                          font=font, extra="text height=1.6ex,text depth=0.3ex")

    def leader(self, a, b, free=0.10, dot=True, style=LEADER):
        """A leader from a (next to its label) to b (on the object); only the
        last `free` cm of it may touch ink."""
        self.leaders.append(dict(a=a, b=b, free=free, dot=dot, style=style))

    SIMPLE = {"north west": ("west", -0.5), "south west": ("west", 0.5),
              "north east": ("east", -0.5), "south east": ("east", 0.5)}

    def _simple(self, x, y, an, h):
        """The same box with a simple anchor: checkfigs reads a compound
        anchor as centred, so the output never uses one."""
        if an in self.SIMPLE:
            a2, f = self.SIMPLE[an]
            return x, y + f * h, a2
        return x, y, an

    def _cfbox(self, L, x=None, y=None, an=None):
        import checkfigs
        M = dict(L)
        if x is not None:
            M["x"], M["y"], M["anchor"] = x, y, an
        spec = self._label_tex(M)
        m = re.match(r"\s*\\node\[([^\]]*)\]", spec)
        return checkfigs.box(m.group(1), M["x"], M["y"], M["text"])

    @staticmethod
    def _cf_hit(a, b):
        return a[0] < b[2] and b[0] < a[2] and a[1] < b[3] and b[1] < a[3]

    def _label_tex(self, L, audit_name=None):
        opts = ["lbl"]
        if L["anchor"] != "center":
            opts.append("anchor=%s" % L["anchor"])
        opts.append("text=%s" % L["color"])
        if L["font"]:
            opts.append("font=%s" % L["font"])
        if L["extra"]:
            opts.append(L["extra"])
        if audit_name:
            opts += ["name=%s" % audit_name, "opacity=0"]
        return "  \\node[%s] at (%s,%s) {%s};\n" % (
            ",".join(opts), f4(L["x"]), f4(L["y"]), L["text"])

    def _leader_tex(self, Q):
        (ax, ay), (bx, by) = Q["a"], Q["b"]
        s = "  \\draw[%s] (%s,%s) -- (%s,%s);\n" % (Q["style"], f4(ax), f4(ay),
                                                   f4(bx), f4(by))
        if Q["dot"]:
            s += "  \\fill[PSlate] (%s,%s) circle (0.75pt);\n" % (f4(bx), f4(by))
        return s

    def body(self):
        items = sorted(self.items, key=lambda it: (-it[0], it[1]))
        return ("".join(self.pre) + "".join(it[2] for it in items)
                + "".join(self.post))

    def tex(self):
        return (HEAD.format(name=self.name, gen=self.gen, blurb=self.blurb)
                + self.body()
                + "".join(self._leader_tex(Q) for Q in self.leaders)
                + "".join(self._label_tex(L) for L in self.labels) + TAIL)

    # ---------------------------------------------------------------- audit
    def _render(self, dpi=400):
        """Compile the ink with every label as an invisible probe; return the
        raster of the ink, the exact label boxes (pt) and the maps from pt
        to pixels."""
        wd = tempfile.mkdtemp(prefix="audit_")
        names = ["L%d" % i for i in range(len(self.labels))]
        probe = "".join(
            "\\pgfpointanchor{%s}{south west}\\pgfgetlastxy\\ax\\ay"
            "\\pgfpointanchor{%s}{north east}\\pgfgetlastxy\\bx\\by"
            "\\typeout{AUDIT %s \\ax\\space\\ay\\space\\bx\\space\\by}"
            % (n, n, n) for n in names + ["current bounding box"])
        src = (HEAD.format(name=self.name, gen=self.gen, blurb="audit")
               + self.body()
               + "".join(self._label_tex(L, n) for L, n in zip(self.labels, names))
               + "\\pgfextra{%s}\n" % probe + TAIL)
        with open(os.path.join(wd, "a.tex"), "w") as f:
            f.write(src)
        env = dict(os.environ, TEXINPUTS=HERE + "//:" + os.environ.get("TEXINPUTS", ""))
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                            "-halt-on-error", "a.tex"], cwd=wd, env=env,
                           capture_output=True, text=True)
        if r.returncode != 0:
            raise SystemExit("audit compile failed for %s:\n%s"
                             % (self.name, r.stdout[-3000:]))
        boxes = {}
        for line in open(os.path.join(wd, "a.log"), errors="replace"):
            m = re.match(r"AUDIT (.+?) (-?[\d.]+)pt (-?[\d.]+)pt (-?[\d.]+)pt "
                         r"(-?[\d.]+)pt", line)
            if m:
                boxes[m.group(1)] = tuple(float(m.group(k)) for k in range(2, 6))
        subprocess.run(["pdftoppm", "-gray", "-r", str(dpi), "-singlefile",
                        "a.pdf", "a"], cwd=wd, check=True)
        img = read_pgm(os.path.join(wd, "a.pgm"))
        shutil.rmtree(wd, ignore_errors=True)
        bx0, by0, bx1, by1 = boxes["current bounding box"]
        sc = dpi / 72.27

        def px(X):
            return (X - bx0 + BORDER) * sc

        def py(Y):
            return (by1 + BORDER - Y) * sc
        return img, [boxes[n] for n in names], px, py

    @staticmethod
    def _dark(img, px, py, box, pad, thr):
        H, W = img.shape
        ax, ay, bx, by = box
        c0, c1 = int(math.floor(px(ax - pad))), int(math.ceil(px(bx + pad)))
        r0, r1 = int(math.floor(py(by + pad))), int(math.ceil(py(ay - pad)))
        r0, r1 = max(0, min(H, r0)), max(0, min(H, r1))
        c0, c1 = max(0, min(W, c0)), max(0, min(W, c1))
        if r1 <= r0 or c1 <= c0:
            return 0
        return int((img[r0:r1, c0:c1] < thr).sum())

    @staticmethod
    def _leader_hits(img, px, py, A, B, free, lthr):
        H, W = img.shape
        L = math.hypot(B[0] - A[0], B[1] - A[1])
        n = max(2, int(L / 0.25))
        hits = 0
        for k in range(n + 1):
            t = k / n
            if t * L < 0.8 or (1 - t) * L < free * PT:
                continue
            X = A[0] + t * (B[0] - A[0])
            Y = A[1] + t * (B[1] - A[1])
            cc, rr = int(round(px(X))), int(round(py(Y)))
            if 0 <= rr < H and 0 <= cc < W:
                win = img[max(0, rr - 1):rr + 2, max(0, cc - 1):cc + 2]
                if (win < lthr).any():
                    hits += 1
        return hits

    def alabel(self, target, text, color="PInk", font=None, prefer=45,
               spread=180, rmin=0.08, rmax=1.6, lead=0.34, free=0.13):
        """A label placed automatically near the screen point `target`: the
        nearest position, in the preferred direction first, whose box is clear
        of ink and of the other labels; beyond `lead` cm it gets a leader."""
        i = self.label(target[0], target[1], text, color=color, font=font)
        self.labels[i]["auto"] = dict(target=target, prefer=prefer,
                                      spread=spread, rmin=rmin, rmax=rmax,
                                      lead=lead, free=free)
        return i

    def _autoplace(self, dpi=400, thr=246, lthr=172, pad=1.1, gap=1.2):
        img, boxes, px, py = self._render(dpi)
        auto = [i for i, L in enumerate(self.labels) if "auto" in L]
        placed = {i: boxes[i] for i in range(len(boxes)) if i not in auto}
        cfp = []
        for i in placed:
            L = self.labels[i]
            x, y, an = self._simple(L["x"] * PT, L["y"] * PT, L["anchor"],
                                    boxes[i][3] - boxes[i][1])
            cfp.append(self._cfbox(L, x / PT, y / PT, an))
        segs = [((Q["a"][0] * PT, Q["a"][1] * PT), (Q["b"][0] * PT, Q["b"][1] * PT))
                for Q in self.leaders]
        names = ["west", "south west", "south", "south east", "east",
                 "north east", "north", "north west"]
        for i in auto:
            L = self.labels[i]
            A = L["auto"]
            bx = boxes[i]
            w, h = bx[2] - bx[0], bx[3] - bx[1]
            tx, ty = A["target"][0] * PT, A["target"][1] * PT
            angs = [A["prefer"] + d for d in
                    sorted({s * 15 * k for k in range(13) for s in (1, -1)
                            if 15 * k <= A["spread"]}, key=abs)]
            found = None
            r = A["rmin"]
            while r <= A["rmax"] + 1e-9 and found is None:
                for ang in angs:
                    ca, sa = math.cos(math.radians(ang)), math.sin(math.radians(ang))
                    x, y = tx + r * PT * ca, ty + r * PT * sa
                    an = names[int(((ang % 360) + 22.5) % 360 // 45)]
                    ox = {"west": 0, "east": -w, "south": -w / 2, "north": -w / 2,
                          "south west": 0, "north west": 0, "south east": -w,
                          "north east": -w}[an]
                    oy = {"south": 0, "north": -h, "west": -h / 2, "east": -h / 2,
                          "south west": 0, "south east": 0, "north west": -h,
                          "north east": -h}[an]
                    box = (x + ox, y + oy, x + ox + w, y + oy + h)
                    if self._dark(img, px, py, box, pad, thr):
                        continue
                    sx, sy, sa = self._simple(x, y, an, h)
                    cfb = self._cfbox(L, sx / PT, sy / PT, sa)
                    if any(self._cf_hit(cfb, c) for c in cfp):
                        continue
                    if any(box[0] - gap < b[2] and b[0] - gap < box[2]
                           and box[1] - gap < b[3] and b[1] - gap < box[3]
                           for b in placed.values()):
                        continue
                    if any(seg_box(S[0], S[1], (box[0] - pad, box[1] - pad,
                                                box[2] + pad, box[3] + pad))
                           for S in segs):
                        continue
                    leader = None
                    if r > A["lead"]:
                        leader = ((x, y), (tx, ty))
                        if self._leader_hits(img, px, py, leader[0], leader[1],
                                             A["free"], lthr):
                            continue
                        if any(seg_box(leader[0], leader[1],
                                       (b[0] - pad, b[1] - pad, b[2] + pad,
                                        b[3] + pad))
                               for b in placed.values()):
                            continue
                        if any(seg_seg(leader, S) for S in segs):
                            continue
                    found = (x, y, an, box, leader, cfb)
                    break
                r += 0.025
            if found is None:
                if os.environ.get("FIGDRAFT") is None:
                    raise SystemExit("no place for label %r in %s"
                                     % (L["text"], self.name))
                print("    no place for", L["text"])
                del L["auto"]
                continue
            x, y, an, box, leader, cfb = found
            L["x"], L["y"], L["anchor"] = x / PT, y / PT, an
            placed[i] = box
            cfp.append(cfb)
            if leader:
                self.leader((x / PT, y / PT), A["target"], free=A["free"])
                segs.append(leader)
            del L["auto"]

    def audit(self, dpi=400, thr=246, lthr=172, pad=1.1, gap=1.2):
        """Rasterise the ink without labels and leaders, read the exact label
        boxes from TeX, and return the list of collisions."""
        img, lab, px, py = self._render(dpi)
        bad = []
        # ink under a label
        for i, box in enumerate(lab):
            k = self._dark(img, px, py, box, pad, thr)
            if k:
                bad.append("ink under label %r (%d px)" % (self.labels[i]["text"], k))
        # label against label
        for i in range(len(lab)):
            for j in range(i + 1, len(lab)):
                a, b = lab[i], lab[j]
                if (a[0] - gap < b[2] and b[0] - gap < a[2]
                        and a[1] - gap < b[3] and b[1] - gap < a[3]):
                    bad.append("labels touch: %r / %r" % (self.labels[i]["text"],
                                                          self.labels[j]["text"]))
        # the estimate of checkfigs.py must pass as well
        cfs = [self._cfbox(L) for L in self.labels]
        for i in range(len(cfs)):
            for j in range(i + 1, len(cfs)):
                if self._cf_hit(cfs[i], cfs[j]):
                    bad.append("checkfigs estimate: %r / %r"
                               % (self.labels[i]["text"], self.labels[j]["text"]))
        # leaders: clear of ink but for their last `free` cm, of the labels
        # but their own, and of each other
        segs = []
        for Q in self.leaders:
            A = (Q["a"][0] * PT, Q["a"][1] * PT)
            B = (Q["b"][0] * PT, Q["b"][1] * PT)
            segs.append((A, B))
            hits = self._leader_hits(img, px, py, A, B, Q["free"], lthr)
            if hits:
                bad.append("leader to %r crosses ink (%d samples)"
                           % (Q["b"], hits))
            for i, (ax, ay, bx, by) in enumerate(lab):
                if seg_box(A, B, (ax - pad, ay - pad, bx + pad, by + pad),
                           skip_end=A):
                    bad.append("leader to %r crosses label %r"
                               % (Q["b"], self.labels[i]["text"]))
        for i in range(len(segs)):
            for j in range(i + 1, len(segs)):
                if seg_seg(segs[i], segs[j]):
                    bad.append("leaders cross: %r / %r" % (self.leaders[i]["b"],
                                                           self.leaders[j]["b"]))
        return bad

    # ---------------------------------------------------------------- write
    def write(self, strict=None, **kw):
        if strict is None:
            strict = os.environ.get("FIGDRAFT") is None
        if any("auto" in L for L in self.labels):
            self._autoplace(**kw)
        if any(L["anchor"] in self.SIMPLE for L in self.labels):
            _, boxes, _, _ = self._render()
            for L, b in zip(self.labels, boxes):
                x, y, an = self._simple(L["x"], L["y"], L["anchor"],
                                        (b[3] - b[1]) / PT)
                L["x"], L["y"], L["anchor"] = x, y, an
        bad = self.audit(**kw)
        for b in bad:
            print("   ", self.name, ":", b)
        if bad and strict:
            raise SystemExit("audit failed for %s" % self.name)
        with open(os.path.join(HERE, self.name + ".tex"), "w") as f:
            f.write(self.tex())
        print("%-18s %2d labels, %2d leaders, audited clear"
              % (self.name, len(self.labels), len(self.leaders)))
        compile_figure(self.name)


def compile_figure(name):
    """pdflatex in the figures folder, a check of the log for missing glyphs,
    the 200 dpi PNG, and the cleanup."""
    r = subprocess.run(["pdflatex", "-interaction=nonstopmode",
                        "-halt-on-error", name + ".tex"], cwd=HERE,
                       capture_output=True, text=True)
    log = os.path.join(HERE, name + ".log")
    text = open(log, errors="replace").read() if os.path.exists(log) else ""
    if r.returncode != 0:
        sys.stdout.write(r.stdout[-3000:])
        raise SystemExit("pdflatex failed on %s" % name)
    for bad in ("Missing character", "Overfull", "Undefined control"):
        if bad in text:
            raise SystemExit("%s: '%s' in the log" % (name, bad))
    subprocess.run(["pdftoppm", "-png", "-r", "200", "-singlefile",
                    name + ".pdf", name], cwd=HERE, check=True)
    for ext in (".aux", ".log"):
        try:
            os.remove(os.path.join(HERE, name + ext))
        except OSError:
            pass


def read_pgm(path):
    data = open(path, "rb").read()
    tok, i = [], 0
    while len(tok) < 4:
        while data[i:i + 1].isspace():
            i += 1
        if data[i:i + 1] == b"#":
            while data[i:i + 1] not in (b"\n", b""):
                i += 1
            continue
        j = i
        while not data[j:j + 1].isspace():
            j += 1
        tok.append(data[i:j])
        i = j
    i += 1
    w, h = int(tok[1]), int(tok[2])
    return np.frombuffer(data, dtype=np.uint8, count=w * h,
                         offset=i).reshape(h, w)


def seg_box(A, B, box, skip_end=None):
    """Does the segment AB meet the box (x0,y0,x1,y1)?  The part within
    1.5pt of skip_end is ignored, since a leader starts at its own label."""
    x0, y0, x1, y1 = box
    L = math.hypot(B[0] - A[0], B[1] - A[1])
    n = max(2, int(L / 0.3))
    for k in range(n + 1):
        t = k / n
        X = A[0] + t * (B[0] - A[0])
        Y = A[1] + t * (B[1] - A[1])
        if skip_end is not None and math.hypot(X - skip_end[0],
                                               Y - skip_end[1]) < 1.5:
            continue
        if x0 <= X <= x1 and y0 <= Y <= y1:
            return True
    return False


def seg_seg(s, t):
    (a, b), (c, d) = s, t

    def orient(p, q, r):
        return (q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0])
    o1, o2 = orient(a, b, c), orient(a, b, d)
    o3, o4 = orient(c, d, a), orient(c, d, b)
    return o1 * o2 < 0 and o3 * o4 < 0


def orbit_cam(target, az, el, R=30.0):
    """A camera at azimuth az (degrees, from the -y axis towards +x) and
    elevation el, at distance R from the target."""
    a, e = math.radians(az), math.radians(el)
    eye = (target[0] + R * math.sin(a) * math.cos(e),
           target[1] - R * math.cos(a) * math.cos(e),
           target[2] + R * math.sin(e))
    return Camera(eye=eye, target=target, focal=R)


def fit(cam, pts, width):
    """Set the camera scale so that the points span the given width, and
    return the projected bounding box."""
    cam.scale = 1.0
    xs = [cam.project(p)[0][0] for p in pts]
    cam.scale = width / (max(xs) - min(xs))
    q = [cam.project(p)[0] for p in pts]
    return (min(a for a, b in q), min(b for a, b in q),
            max(a for a, b in q), max(b for a, b in q))


# ===================================================================== cube
def fig_weilcube():
    """The sixteen monomials w^(T), T in {1,2,3,4}, as the vertices of the
    4-cube under the linear projection e_j -> (a_j, 1), so that the height of
    w^(T) is |T| and all edges of one direction j are parallel; each vertex is
    written as the monomial itself, in the colour of the class it lies in."""
    a = (-2.25, -0.25, 0.75, 1.75)       # the horizontal parts of e_1..e_4
    G, HH = 1.54, 1.12                   # pitch of the middle row, of the rows
    BW, BH = 1.34, 0.38                  # the extent of a monomial
    GAP = 0.07                           # between an edge and a monomial
    F = Fig("fig_weilcube",
            "The 2^{2n} = 16 monomials w^(T) at n = 2 as the vertices of the "
            "4-cube under the linear projection e_j -> (a_j, 1): the height is "
            "|T|, edges of one direction are parallel, and the parity of |T| "
            "separates omega_1 from omega_2.")

    def pos(T):
        return (G * sum(a[j] for j in range(4) if T >> j & 1),
                HH * bin(T).count("1"))

    def mono(T):
        return "".join(("y_{%d}" if T >> j & 1 else "x_{%d}") % (j + 1)
                       for j in range(4))

    def clip(p, q):
        """the part of the segment pq outside the two monomials, less GAP"""
        dx, dy = q[0] - p[0], q[1] - p[1]
        hx, hy = BW / 2 + GAP, BH / 2 + GAP
        t = min(hx / abs(dx) if dx else 9.0, hy / abs(dy))
        return ((p[0] + t * dx, p[1] + t * dy), (q[0] - t * dx, q[1] - t * dy))

    # the 32 edges
    for T in range(16):
        for j in range(4):
            if T >> j & 1:
                continue
            (x0, y0), (x1, y1) = clip(pos(T), pos(T | 1 << j))
            F.flat("  \\draw[PSlate!75,line width=0.45pt] (%s,%s) -- (%s,%s);\n"
                   % (f4(x0), f4(y0), f4(x1), f4(y1)), under=True)
    # the sixteen vertices, each the monomial w^(T)
    for T in range(16):
        x, y = pos(T)
        even = bin(T).count("1") % 2 == 0
        F.label(x, y, "$%s$" % mono(T), font=r"\footnotesize",
                color="PIndigo" if even else "PTeal",
                extra="text height=1.5ex,text depth=0.45ex")

    # the axis of |T| on the left
    xl = -G * 2.5 - BW / 2 - 0.30
    F.flat("  \\draw[PInk,line width=0.45pt] (%s,%s) -- (%s,%s);\n"
           % (f4(xl), f4(-0.12), f4(xl), f4(4 * HH + 0.12)))
    for k in range(5):
        F.flat("  \\draw[PInk,line width=0.45pt] (%s,%s) -- (%s,%s);\n"
               % (f4(xl - 0.10), f4(k * HH), f4(xl), f4(k * HH)))
        F.label(xl - 0.17, k * HH, "$%d$" % k, anchor="east",
                font=r"\footnotesize")
    F.label(xl, 4 * HH + 0.30, r"$\lvert T\rvert$", anchor="south")

    # on the right, for each level: the class and the common coefficient
    xr = G * 2.5 + BW / 2 + 0.38
    cols = (0.25, 1.58)
    who = [r"$\omega_{1}$", r"$\omega_{2}$"] * 2 + [r"$\omega_{1}$"]
    coef = [r"$d^{2}$", r"$d$", r"$-d$", r"$-1$", r"$1$"]
    for k in range(5):
        col = "PIndigo" if k % 2 == 0 else "PTeal"
        F.label(xr + cols[0], k * HH, who[k], color=col)
        F.label(xr + cols[1], k * HH, coef[k])
    ytop = 4 * HH + 0.62
    for c, t in zip(cols, ("class", "coefficient")):
        F.label(xr + c, ytop, t, font=r"\footnotesize",
                extra="text height=1.6ex,text depth=0.4ex")
    F.flat("  \\draw[PRule,line width=0.45pt] (%s,%s) -- (%s,%s);\n"
           % (f4(xr - 0.18), f4(ytop - 0.28), f4(xr + cols[1] + 0.74),
              f4(ytop - 0.28)))

    # the generating product, which gives every coefficient at once
    F.label(0.0, -0.88,
            r"$\omega_{1}+\delta\,\omega_{2}=d^{-2}\prod_{j=1}^{4}"
            r"\bigl(d\,x_{j}+\delta\,y_{j}\bigr)=\sum_{T}d^{\,2-\lvert T\rvert}"
            r"\,\delta^{\lvert T\rvert}\,w^{(T)},\qquad \delta^{2}=-d$",
            anchor="north")
    F.write(thr=222)


# ===================================================================== spike
def fig_hodgespike():
    """dim Hdg^k(A) over k and n = 2, 3, 4 (thm:hdgcount): the line Q eta^k in
    every degree 0 <= k <= 2n, and the Weil line stacked on it at k = n.  The
    view is turned so that each row falls half a step between the bars of
    the row in front of it, so that no bar is hidden behind another."""
    DX, DY, HU, W = 1.0, 1.85, 0.66, 0.40  # pitch in k, in n, unit, bar width
    NS = (2, 3, 4)
    KMAX = 8
    az = math.degrees(math.atan2(0.5 * DX, DY))
    cam = orbit_cam((4.0, 1.85, 0.8), az, 27, R=38)
    F = Fig("fig_hodgespike",
            "dim Hdg^k(A) for n = 2, 3, 4 (thm:hdgcount): one class eta^k in "
            "every degree 0 <= k <= 2n, and the Weil line on top at k = n.",
            cam)
    xa, xb = -0.75, KMAX + 0.75
    ya, yb = -0.85, (len(NS) - 1) * DY + 0.85
    zt = 3.45 * HU
    fit(cam, [(xa, ya, 0), (xb, ya, 0), (xa, yb, zt), (xb, yb, zt),
              (xa, yb, 0), (xb, yb, 0)], 11.3)

    # floor, back wall, left wall
    F.poly3([(xa, ya, 0), (xb, ya, 0), (xb, yb, 0), (xa, yb, 0)],
            fill="WSlate!55", draw="PRule", lw=0.4, depth=1e6, prio=-6)
    F.poly3([(xa, yb, 0), (xb, yb, 0), (xb, yb, zt), (xa, yb, zt)],
            fill="WSlate!70", draw="PRule", lw=0.4, depth=1e6, prio=-6)
    F.poly3([(xa, ya, 0), (xa, yb, 0), (xa, yb, zt), (xa, ya, zt)],
            fill="WSlate!85", draw="PRule", lw=0.4, depth=1e6, prio=-6)
    # the domain 0 <= k <= 2n of each row, as a strip
    for j, n in enumerate(NS):
        y = j * DY
        F.poly3([(-0.5, y - 0.42, 0), (2 * n + 0.5, y - 0.42, 0),
                 (2 * n + 0.5, y + 0.42, 0), (-0.5, y + 0.42, 0)],
                fill="WSlate", draw="PRule!90", lw=0.35, depth=1e6, prio=-5)
    grid = "PRule!85,line width=0.25pt"
    for h in (1, 2, 3):
        z = h * HU
        F.line3([(xa, ya, z), (xa, yb, z), (xb, yb, z)], grid, prio=-4,
                depth=1e6)
    for k in range(KMAX + 1):
        F.line3([(k * DX, yb, 0), (k * DX, yb, zt)], "PRule!45,line width=0.2pt",
                prio=-4, depth=1e6)
        F.line3([(k * DX, ya, 0), (k * DX, yb, 0)], "PRule!60,line width=0.2pt",
                prio=-4, depth=1e6)
    for j, n in enumerate(NS):
        F.line3([(xa, j * DY, 0), (xb, j * DY, 0)], "PRule!60,line width=0.2pt",
                prio=-4, depth=1e6)
        F.line3([(xa, j * DY, 0), (xa, j * DY, zt)], "PRule!45,line width=0.2pt",
                prio=-4, depth=1e6)

    # the bars
    for j, n in enumerate(NS):
        for k in range(2 * n + 1):
            segs = [(0.0, HU, "PAmber")]
            if k == n:
                segs.append((HU, 3 * HU, "PIndigo"))
            F.stack(k * DX - W / 2, j * DY - W / 2, W, W, segs)

    # the scales: k along the front edge, n along the right edge, the
    # dimension on the front edge of the left wall
    for k in range(KMAX + 1):
        F.tick((k * DX, ya, 0), (k * DX, ya - 0.20, 0), "$%d$" % k,
               font=r"\footnotesize")
    q = F.P((5.5 * DX, ya - 0.20, 0))
    F.label(q[0] + 0.05, q[1] - 0.62, "$k$", anchor="north")
    for j, n in enumerate(NS):
        F.tick((xb, j * DY, 0), (xb + 0.20, j * DY, 0), "$%d$" % n,
               font=r"\footnotesize")
    q = F.P((xb + 0.20, 1.0 * DY, 0))
    F.label(q[0] + 0.62, q[1] - 0.02, "$n$", anchor="west")
    for h in (0, 1, 2, 3):
        F.tick((xa, ya, h * HU), (xa - 0.20, ya, h * HU), "$%d$" % h,
               font=r"\footnotesize")
    q = F.P((xa - 0.20, ya, 1.5 * HU))
    F.label(q[0] - 0.78, q[1], r"$\dim_{\QQ}\Hdg^{k}(A)$", extra="rotate=90")

    # the key, under the left half of the k axis
    q = F.P((xa, ya, 0))
    x0, y0 = q[0] + 0.25, q[1] - 1.45
    F.swatch(x0, y0, "PAmber", r"$\QQ\,\eta^{k}=\Hdg^{k}(A)$ for $k\neq n$")
    F.swatch(x0, y0 - 0.46, "PIndigo",
             r"$\HW(A)$, with $\Hdg^{n}(A)=\QQ\,\eta^{n}\oplus\HW(A)$")
    F.write()


# ============================================================ character grid
def fig_charactergrid():
    """The grid of pairs (r,s), 0 <= r,s <= 6, at n = 3: the summands of
    H^6(A,C) on the antidiagonal raised to their true dimensions
    C(6,r)C(6,s), each marked with its character tau^r conj(tau)^s, and the
    diagonal cells r = s of the norm characters marked with eta^k.  The view
    is steep enough that no bar stands in front of another bar or of a
    diagonal cell (checked by casting rays), and each bar is named in the
    free cell in front of it."""
    n = 3
    N = 2 * n
    HS = 2.8 / 400.0                 # height per dimension
    W = 0.52                         # the width of a bar
    cam = orbit_cam((N / 2, N / 2, 0.6), -17, 36, R=44)
    F = Fig("fig_charactergrid",
            "The K^x-grading of H^*(A,C) at n = 3 on the grid of pairs (r,s); "
            "the summands of H^{2n} at their true dimensions, summing to 924.",
            cam)
    a0, a1 = -0.5, N + 0.5
    floor = [(a0, a0, 0), (a1, a0, 0), (a1, a1, 0), (a0, a1, 0)]
    fit(cam, floor + [(n, n, 400 * HS)], 12.2)

    F.poly3(floor, fill="WSlate!70", draw="PRule", lw=0.45, depth=1e6,
            prio=-6)
    for k in range(1, N + 1):
        t = a0 + k
        F.line3([(t, a0, 0), (t, a1, 0)], "PRule!80,line width=0.25pt",
                prio=-5, depth=1e6)
        F.line3([(a0, t, 0), (a1, t, 0)], "PRule!80,line width=0.25pt",
                prio=-5, depth=1e6)
    # the antidiagonal r + s = 6 as a band of tinted cells, the diagonal
    # r = s as outlined cells
    for r in range(N + 1):
        s_ = N - r
        F.poly3([(r - 0.5, s_ - 0.5, 0), (r + 0.5, s_ - 0.5, 0),
                 (r + 0.5, s_ + 0.5, 0), (r - 0.5, s_ + 0.5, 0)],
                fill="WSlate", draw="PRule", lw=0.3, depth=1e6, prio=-4)
    for r in range(N + 1):
        if r == n:
            continue
        e = 0.38
        F.poly3([(r - e, r - e, 0), (r + e, r - e, 0), (r + e, r + e, 0),
                 (r - e, r + e, 0)], fill="PAmber!7", draw="PAmber!80",
                lw=0.5, depth=1e6, prio=-3)
        F.label3((r, r, 0), r"$\eta^{%d}$" % r, color="PAmber!80!black",
                 font=r"\footnotesize")

    # the bars of H^6
    tops = {}
    for r in range(N + 1):
        s_ = N - r
        d = binom(N, r) * binom(N, s_)
        h = max(d * HS, 0.03)
        col = "PIndigo" if r in (0, N) else ("PAmber" if r == n else "PSlate")
        F.prism((r - W / 2, s_ - W / 2, 0), (r + W / 2, s_ + W / 2, h), col)
        tops[r] = (d, h)

    # each bar: its character and its dimension, in the free cell in front
    # of it (the bar at (6,0) has none, and is named to its right)
    def char(r):
        s_ = N - r
        if r == n:
            return r"\Nm(\tau)^{3}"
        a = "" if r == 0 else (r"\tau" if r == 1 else r"\tau^{%d}" % r)
        b = "" if s_ == 0 else (r"\bar{\tau}" if s_ == 1 else
                                r"\bar{\tau}^{%d}" % s_)
        return a + b
    for r in range(N + 1):
        d, h = tops[r]
        s_ = N - r
        col = "PIndigo" if r in (0, N) else ("PAmber!85!black" if r == n
                                              else "PInk")
        p = (r, s_ - 1, 0) if r < N else (r + 1.1, s_, 0)
        q = F.P(p)
        F.label(q[0], q[1], r"$%s$\\[-1pt]$%d$" % (char(r), d),
                color=col, font=r"\footnotesize", extra="align=center")

    # ticks: r along the front right edge, s along the front left edge
    cen = F.P((N / 2, N / 2, 0))
    F.edge_ticks((a0, a0, 0), (a1, a0, 0), [(k - a0) / (a1 - a0)
                 for k in range(N + 1)], ["$%d$" % k for k in range(N + 1)],
                 (cen[0] + 20, cen[1] - 20))
    F.edge_ticks((a0, a0, 0), (a0, a1, 0), [(k - a0) / (a1 - a0)
                 for k in range(N + 1)], ["$%d$" % k for k in range(N + 1)],
                 (cen[0] - 20, cen[1] - 20))
    q = F.P((N / 2 + 0.5, a0, 0))
    F.label(q[0] + 0.30, q[1] - 0.62, "$r$", anchor="north")
    q = F.P((a0, N / 2 + 0.5, 0))
    F.label(q[0] - 0.62, q[1] - 0.30, "$s$", anchor="east")

    # the diagonal, named at its far end
    q = F.P((a1, a1, 0))
    F.label(q[0] + 0.28, q[1] + 0.10, r"$r=s$: $\Nm(\tau)^{k}$",
            anchor="west", color="PAmber!85!black")
    # what the picture says, in formulas, at the top left
    xl = min(F.P(c)[0] for c in floor) - 0.35
    yb = max(F.P((2 + u * W / 2, 4 + v * W / 2, tops[2][1]))[1]
             for u in (-1, 1) for v in (-1, 1)) + 0.40
    notes = [r"$H^{6}(A,\CC)=\bigoplus_{r+s=6}\bigwedge^{r}V_{+}"
             r"\otimes\bigwedge^{s}V_{-}$",
             r"$\dim H^{6}(A,\CC)=\binom{12}{6}=924$, $\ \eta^{3}\in(3,3)$",
             r"$\HW(A)\otimes\CC=(6,0)\oplus(0,6)$"]
    for i, t in enumerate(notes):
        F.label(xl, yb + 0.64 * (len(notes) - 1 - i), t, anchor="west",
                extra="text height=2.2ex,text depth=1.1ex")
    F.write(thr=226)


# ================================================================ Chern line
def fig_chernline():
    """The Weil line as the plane of omega_1, omega_2 at n = 2, K = Q(sqrt-2),
    in the coordinates u = a omega_1 + b omega_2; the orbit tau^{4k} omega_1,
    k = -1..2, of omega_1 under tau = 1 + sqrt(-2)/4, which acts through the
    rational matrix of tau^4 (thm:explicitgens (iv)), on the logarithmic
    spiral through it; the level set Nm(u) = a^2 + b^2/2 = 1 of the norm form;
    and the transverse axis Q eta^2 with the orbit Nm(tau)^{2k} eta^2."""
    d = 2
    # tau^4 = 17/64 + (7/8) sqrt(-2) acts on (a, b) by [[17/64, -7/8],
    # [7/4, 17/64]]: omega_1 -> 17/64 omega_1 + 7/4 omega_2
    al, be = 17 / 64, 7 / 8
    rho = math.hypot(al, be * math.sqrt(d))           # |tau^4| = Nm(tau)^2
    th = math.atan2(be * math.sqrt(d), al)             # arg tau^4

    def orbit(t):
        """omega_1 moved by tau^{4t}, in the coordinates (a, b)."""
        r = rho ** t
        return (r * math.cos(t * th), math.sqrt(d) * r * math.sin(t * th), 0.0)

    cam = orbit_cam((0.0, 0.0, 0.55), 34, 23, R=36)
    F = Fig("fig_chernline",
            "The Weil line W(A) at n = 2, K = Q(sqrt-2), as the plane of "
            "omega_1, omega_2, with the orbit of omega_1 under tau = "
            "1 + sqrt(-2)/4 and the axis Q eta^2 with the orbit of eta^2.",
            cam)
    A, B0, B = 2.0, 2.15, 2.35                          # the extent of W(A)
    plane = [(-A, -B0, 0), (A, -B0, 0), (A, B, 0), (-A, B, 0)]
    ZT = 2.45
    fit(cam, plane + [(0, 0, ZT), (0, 0, -1.0)], 12.6)

    # the eta axis below the plane, drawn first so that the plane covers it
    F.line3([(0, 0, -0.95), (0, 0, 0)], "PAmber!45,line width=0.8pt",
            prio=-9, depth=2e6)
    # the plane W(A)
    F.poly3(plane, fill="PIndigo!4", draw="PIndigo!50", lw=0.5, depth=1e6,
            prio=-6, opacity=0.93)
    # the coordinate axes of the plane, with unit ticks
    F.line3([(-A, 0, 0), (A + 0.45, 0, 0)],
            "PIndigo!80,line width=0.55pt," + TIPS, prio=-4, depth=1e6)
    F.line3([(0, -B0, 0), (0, B + 0.45, 0)],
            "PIndigo!80,line width=0.55pt," + TIPS, prio=-4, depth=1e6)
    for v in (-1, 1):
        F.line3([(v, -0.09, 0), (v, 0.09, 0)], "PIndigo!80,line width=0.5pt",
                prio=-4, depth=1e6)
    for v in (-1, 1, 2):
        F.line3([(-0.09, v, 0), (0.09, v, 0)], "PIndigo!80,line width=0.5pt",
                prio=-4, depth=1e6)
    # the level curve Nm(u) = 1 of the norm form through omega_1
    ell = [(math.cos(t), math.sqrt(d) * math.sin(t), 0)
           for t in [2 * math.pi * k / 240 for k in range(241)]]
    F.line3(ell, "PMag!55,line width=0.5pt,dash pattern=on 1.8pt off 1.5pt",
            prio=-3, depth=1e6)
    # the spiral t -> tau^{4t} omega_1 through the orbit
    ts = [-5.0 + (2.35 + 5.0) * k / 800 for k in range(801)]
    F.line3([orbit(t) for t in ts], "PMag,line width=1.0pt", prio=-1,
            depth=1e6)
    for k in range(-1, 3):
        F.dot3(orbit(k), "PMag", r=2.1, prio=4, depth=-1e5)
    # omega_2 on its axis, and the origin
    F.dot3((0, 1, 0), "white", r=1.9, ring="PIndigo", prio=4, depth=-1e5)
    F.dot3((0, 0, 0), "PInk", r=1.3, ring="white", prio=4, depth=-1e5)
    # the eta axis above the plane, with the orbit of eta^2
    F.line3([(0, 0, 0), (0, 0, ZT)], "PAmber,line width=0.9pt," + TIPS,
            prio=6, depth=-2e5)
    H0 = 1.25
    for k in range(0, 3):
        F.dot3((0, 0, H0 * rho ** k), "PAmber", r=2.0, prio=7, depth=-3e5)

    # the axes
    q = F.P((A + 0.45, 0, 0))
    F.label(q[0] + 0.10, q[1] - 0.02, r"$\QQ\,\omega_{1}$", anchor="west",
            color="PIndigo")
    q = F.P((0, B + 0.45, 0))
    F.label(q[0] + 0.12, q[1] + 0.04, r"$\QQ\,\omega_{2}$", anchor="west",
            color="PIndigo")
    q = F.P((0, 0, ZT))
    F.label(q[0], q[1] + 0.10, r"$\QQ\,\eta^{2}$", anchor="south",
            color="PAmber!85!black")
    # the plane, named on itself near its left corner
    q = F.P((A - 0.45, B - 0.55, 0))
    F.label(q[0], q[1], r"$\HW(A)$", color="PIndigo")
    # the orbit of omega_1, the basis vector omega_2, the level curve
    names = {0: r"$\omega_{1}$", 1: r"$\tau^{4}\omega_{1}$",
             2: r"$\tau^{8}\omega_{1}$", -1: r"$\tau^{-4}\omega_{1}$",
             -2: r"$\tau^{-8}\omega_{1}$"}
    pref = {0: -60, 1: 20, 2: 150, -1: -100}
    for k in (0, 1, 2):
        F.alabel(F.P(orbit(k)), names[k], color="PMag", prefer=pref[k])
    # tau^{-4} omega_1 lies next to the axis of omega_2 and inside the level
    # curve: its name goes below the curve, on a leader
    q = F.P(orbit(-1))
    F.label(q[0] + 0.30, q[1] - 0.62, names[-1], anchor="north", color="PMag")
    F.leader((q[0] + 0.24, q[1] - 0.60), (q[0] + 0.02, q[1] - 0.06),
             free=0.36)
    F.alabel(F.P((0, 1, 0)), r"$\omega_{2}$", color="PIndigo", prefer=160,
             spread=60)
    te = math.radians(200)
    F.alabel(F.P((math.cos(te), math.sqrt(d) * math.sin(te), 0)),
             r"$\Nm(u)=1$", color="PMag!85!black", prefer=185, spread=40,
             rmin=0.25, rmax=1.4, free=0.10)
    for k, t in ((2, r"$\Nm(\tau)^{4}\eta^{2}$"), (1, r"$\Nm(\tau)^{2}\eta^{2}$"),
                 (0, r"$\eta^{2}$")):
        F.alabel(F.P((0, 0, H0 * rho ** k)), t, color="PAmber!85!black",
                 prefer=0, spread=60)

    # the data of the example, at the top left
    x0 = min(F.P(c)[0] for c in plane)
    y0 = F.P((0, 0, ZT))[1] + 0.30
    rows = [(r"$n=2,\quad K=\QQ(\sqrt{-2})$", 0.0),
            (r"$\tau=1+\tfrac14\sqrt{-2},\quad \Nm(\tau)=\tfrac98$", -0.60),
            (r"$\tau^{4}=\tfrac{17}{64}+\tfrac78\sqrt{-2}$", -1.20),
            (r"$\iota(\tau)^{*}|_{\HW(A)}=\begin{pmatrix}\frac{17}{64}&"
             r"-\frac{7}{8}\\[2pt]\frac{7}{4}&\frac{17}{64}\end{pmatrix}$",
             -2.02)]
    for t, dy in rows:
        F.label(x0, y0 + dy, t, anchor="west",
                extra="text height=2.1ex,text depth=0.9ex")
    # the action on the axis of eta^2 and the norm form, at the top right
    x1 = max(F.P(c)[0] for c in plane)
    for t, dy in ((r"$\iota(\tau)^{*}\eta^{2}=\Nm(\tau)^{2}\eta^{2}="
                   r"\tfrac{81}{64}\,\eta^{2}$", 0.0),
                  (r"$\Nm(a\,\omega_{1}+b\,\omega_{2})=a^{2}+\tfrac12 b^{2}$",
                   -0.60)):
        F.label(x1, y0 + dy, t, anchor="east",
                extra="text height=2.1ex,text depth=0.9ex")
    F.write()


# =============================================================== annihilator
def fig_annihilator():
    """H^{0,2} = wedge^2 H^{0,1} at n = 3 as the strict upper triangle of the
    6 x 6 array on the basis u_1, u_2, u_3 of V_+^{0,1} and v_1, v_2, v_3 of
    V_-^{0,1}: the fifteen products e_i ^ e_j, i < j, each in its cell, in
    the three blocks of lem:annihilator, and beside each block what
    z -> z.omega does to it."""
    n = 3
    N = 2 * n
    CW, CH = 1.28, 0.64                         # the cell
    basis = [r"u_{%d}" % (k + 1) for k in range(n)] + \
            [r"v_{%d}" % (k + 1) for k in range(n)]
    F = Fig("fig_annihilator",
            "H^{0,2} = wedge^2 H^{0,1} at n = 3 as the strict upper triangle "
            "of the 6 x 6 array: the two outer blocks are carried injectively "
            "by z -> z.omega, the n^2 = 9 mixed products form its kernel.")
    PLUS, MIX, MINUS = "PIndigo", "PClay", "PTeal"

    def X(j):
        return j * CW

    def Y(i):
        return -i * CH

    def block(i, j):
        if j < n:
            return PLUS
        if i >= n:
            return MINUS
        return MIX

    # the fifteen cells, each with its product
    for i in range(N):
        for j in range(i + 1, N):
            c = block(i, j)
            F.flat("  \\path[fill=%s!9,draw=%s!45,line width=0.3pt] (%s,%s) "
                   "rectangle (%s,%s);\n"
                   % (c, c, f4(X(j)), f4(Y(i)), f4(X(j + 1)), f4(Y(i + 1))),
                   under=True)
            F.label(X(j) + CW / 2, Y(i) - CH / 2,
                    r"$%s\wedge %s$" % (basis[i], basis[j]),
                    font=r"\footnotesize", color="%s!70!black" % c)
    # the three blocks, outlined
    outline = "line width=0.9pt,line join=miter"
    F.flat("  \\draw[%s,%s] (%s,%s) -- (%s,%s) -- (%s,%s) -- (%s,%s) -- "
           "(%s,%s) -- (%s,%s) -- cycle;\n"
           % (PLUS, outline, f4(X(1)), f4(Y(0)), f4(X(3)), f4(Y(0)),
              f4(X(3)), f4(Y(2)), f4(X(2)), f4(Y(2)), f4(X(2)), f4(Y(1)),
              f4(X(1)), f4(Y(1))))
    F.flat("  \\draw[%s,%s] (%s,%s) rectangle (%s,%s);\n"
           % (MIX, outline, f4(X(3)), f4(Y(0)), f4(X(6)), f4(Y(3))))
    F.flat("  \\draw[%s,%s] (%s,%s) -- (%s,%s) -- (%s,%s) -- (%s,%s) -- "
           "(%s,%s) -- (%s,%s) -- cycle;\n"
           % (MINUS, outline, f4(X(4)), f4(Y(3)), f4(X(6)), f4(Y(3)),
              f4(X(6)), f4(Y(5)), f4(X(5)), f4(Y(5)), f4(X(5)), f4(Y(4)),
              f4(X(4)), f4(Y(4))))

    # the basis: the columns on top, the rows on the diagonal, where
    # e_k ^ e_k = 0; and the splitting H^{0,1} = V_+^{0,1} + V_-^{0,1} as
    # braces over the columns
    for k in range(N):
        c = PLUS if k < n else MINUS
        F.label(X(k) + CW / 2, Y(0) + 0.26, "$%s$" % basis[k], color=c)
        F.label(X(k) + CW - 0.16, Y(k) - CH / 2, "$%s$" % basis[k],
                anchor="east", color=c)
    for k0, c, t in ((0, PLUS, r"$V_{+}^{0,1}$"), (n, MINUS, r"$V_{-}^{0,1}$")):
        F.flat("  \\draw[%s,line width=0.5pt,decorate,decoration={brace,"
               "amplitude=4pt}] (%s,%s) -- (%s,%s);\n"
               % (c, f4(X(k0) + 0.08), f4(Y(0) + 0.56), f4(X(k0 + n) - 0.08),
                  f4(Y(0) + 0.56)))
        F.label(X(k0) + n * CW / 2, Y(0) + 1.04, t, color=c)

    # what z -> z.omega does to each block
    xr = X(N) + 0.40
    F.label(xr, Y(0) - 0.15,
            r"$V_{+}^{0,1}\otimes V_{-}^{0,1}$,\ \ $\dim n^{2}=9$",
            anchor="west", color="%s!85!black" % MIX)
    F.label(xr, Y(0) - 0.80, r"$u\wedge v\;\longmapsto\;u\wedge v\wedge\omega=0$",
            anchor="west", color="%s!85!black" % MIX)
    F.label(xr, Y(0) - 1.40,
            r"since $u\wedge\alpha_{+}=0$ and $v\wedge\alpha_{-}=0$",
            anchor="west", color="%s!85!black" % MIX, font=r"\footnotesize")
    F.label(xr, Y(3) - 0.35,
            r"$\bigwedge^{2}V_{-}^{0,1}$,\ \ $\dim\binom{n}{2}=3$",
            anchor="west", color="%s!85!black" % MINUS)
    F.label(xr, Y(3) - 1.00,
            r"$z\;\longmapsto\;a\,z\wedge\alpha_{+}$, injective",
            anchor="west", color="%s!85!black" % MINUS)
    xl, yl = X(0) - 0.10, Y(4) - 0.35
    F.label(xl, yl, r"$\bigwedge^{2}V_{+}^{0,1}$,\ \ $\dim\binom{n}{2}=3$",
            anchor="west", color="%s!85!black" % PLUS)
    F.label(xl, yl - 0.65,
            r"$z\;\longmapsto\;b\,z\wedge\alpha_{-}$, injective",
            anchor="west", color="%s!85!black" % PLUS)
    F.leader((X(1) + 0.22, yl + 0.26), (X(1) + 0.22, Y(1) - 0.02), free=0.02,
             dot=False, style="%s!70,line width=0.45pt" % PLUS)

    # the Weil class, and the count
    F.label(X(0) - 0.10, Y(N) - 0.62,
            r"$\omega=a\,\alpha_{+}+b\,\alpha_{-}\in\HW(A)\otimes\RR$,\ \ "
            r"$ab\neq0$,\ \ $\alpha_{\pm}$ spanning $\bigwedge^{2n}V_{\pm}$",
            anchor="west")
    F.label(X(0) - 0.10, Y(N) - 1.27,
            r"$H^{0,2}(A)=\bigwedge^{2}H^{0,1}$,\ \ "
            r"$\dim\binom{2n}{2}=15=3+9+3$",
            anchor="west")
    F.write(thr=215)


# =================================================================== witness
def fig_witness():
    """c(tau)^n = (tau / conj tau)^n for n = 0..12 as helices on the cylinder
    S^1 x [0,12], for K = Q(sqrt-1) and K = Q(sqrt-3); the characters
    tau^{2n} and Nm(tau)^n agree at tau exactly on the seam c^n = 1."""
    cam = orbit_cam((0.0, 0.0, 1.85), 0, 4, R=60)
    F = Fig("fig_witness",
            "The values c(tau)^n = (tau/conj tau)^n, n = 0..12, as helices on "
            "a cylinder, for bad and good witnesses at d = 1 and d = 3; the "
            "characters agree at tau exactly where a helix meets the seam.",
            cam)
    R, HN, NMAX = 1.0, 0.31, 12
    ZT = HN * NMAX
    panels = [
        (-2.45, 1, [(1, "PClay"), (2, "PTeal")], (0, 4, 8, 12)),
        (2.45, 3, [(1, "PClay"), (3, "PAmber"), (2, "PTeal")], (0, 3, 6, 9, 12)),
    ]
    pts = []
    for cx, _, _, _ in panels:
        for t in range(0, 360, 10):
            a = math.radians(t)
            pts += [(cx + R * math.sin(a), -R * math.cos(a), 0),
                    (cx + R * math.sin(a), -R * math.cos(a), ZT)]
    fit(cam, pts, 9.4)

    def on(cx, th, z):
        return (cx + R * math.sin(th), -R * math.cos(th), z)

    def front(cx, th, z):
        p = on(cx, th, z)
        nrm = (math.sin(th), -math.cos(th), 0.0)
        return dot(nrm, sub(cam.eye, p)) > 0

    for cx, d, taus, marks in panels:
        # the cylinder: its front strips, translucent, over the back of the
        # helices; the rims at n = 0 and n = 12
        NS = 72
        for k in range(NS):
            a0, a1 = 2 * math.pi * k / NS, 2 * math.pi * (k + 1) / NS
            if not front(cx, 0.5 * (a0 + a1), 0.5 * ZT):
                continue
            quad = [on(cx, a0, 0), on(cx, a1, 0), on(cx, a1, ZT), on(cx, a0, ZT)]
            F.poly3(quad, fill=F.tone((math.sin(0.5 * (a0 + a1)),
                                       -math.cos(0.5 * (a0 + a1)), 0),
                                      "PSlate", lo=4, hi=14),
                    opacity=0.70, prio=-1, depth=1e5)
        for z in (0.0, ZT):
            ring = [on(cx, 2 * math.pi * k / 120, z) for k in range(121)]
            runs, cur, prev = [], [], None
            for k, p in enumerate(ring):
                f = front(cx, 2 * math.pi * k / 120, z)
                if prev is not None and f != prev:
                    runs.append((prev, cur))
                    cur = [cur[-1]]
                cur.append(p)
                prev = f
            runs.append((prev, cur))
            for f, run in runs:
                if len(run) > 1:
                    F.line3(run, "PSlate!70,line width=0.5pt" if f else
                            "PSlate!45,line width=0.4pt,dash pattern=on 1.5pt "
                            "off 1.3pt", prio=0 if f else -2,
                            depth=-1e5 if f else 2e5)
        # the two silhouettes and the seam c^n = 1
        for sx in (-1, 1):
            F.line3([(cx + sx * R, 0, 0), (cx + sx * R, 0, ZT)],
                     "PSlate!70,line width=0.5pt", prio=0, depth=-1e5)
        F.line3([on(cx, 0, 0), on(cx, 0, ZT)], "PInk,line width=0.75pt",
                prio=1, depth=-2e5)
        for n in range(NMAX + 1):
            F.line3([on(cx, -0.05, n * HN), on(cx, 0.05, n * HN)],
                    "PInk,line width=0.45pt", prio=1, depth=-2e5)
        # the helices, their back halves first
        for m, col in taus:
            tau = complex(m, math.sqrt(d))
            phi = math.atan2((tau / tau.conjugate()).imag,
                             (tau / tau.conjugate()).real)
            N = 600
            samp = [(k * NMAX / N) for k in range(N + 1)]
            cur, prev = [], None
            for t in samp:
                th = t * phi
                f = front(cx, th, t * HN)
                p = on(cx, th, t * HN)
                if prev is not None and f != prev:
                    cur.append(p)
                    F.line3(cur, "%s,line width=1.0pt" % col if prev else
                            "%s!40,line width=0.6pt" % col,
                            prio=2 if prev else -3,
                            depth=-3e5 if prev else 3e5)
                    cur = []
                cur.append(p)
                prev = f
            F.line3(cur, "%s,line width=1.0pt" % col if prev else
                    "%s!40,line width=0.6pt" % col, prio=2 if prev else -3,
                    depth=-3e5 if prev else 3e5)
            for n in range(NMAX + 1):
                th = n * phi
                f = front(cx, th, n * HN)
                F.dot3(on(cx, th, n * HN), col if f else "%s!40" % col,
                       r=1.55, prio=4 if f else -2,
                       depth=(-4e5 if f else 2.5e5))
        # the points where the characters agree, ringed
        for n in range(1, NMAX + 1):
            for m, col in taus:
                tau = complex(m, math.sqrt(d))
                c = tau / tau.conjugate()
                if abs(c ** n - 1) < 1e-9:
                    x, y = F.P(on(cx, 0, n * HN))
                    F.add(-5e5, "  \\draw[PInk,line width=0.6pt] (%s,%s) "
                                "circle (3.3pt);\n" % (f4(x), f4(y)), 5)
                    break
        # the scale of n on the left silhouette
        for n in marks:
            F.tick((cx - R, 0, n * HN), (cx - R - 0.14, 0, n * HN), "$%d$" % n,
                   font=r"\footnotesize")
        q = F.P((cx - R - 0.14, 0, ZT))
        F.label(q[0] - 0.02, q[1] + 0.30, "$n$", anchor="south east")
        # the field, and under it the witnesses
        q = F.P(on(cx, 0, 0))
        F.label(q[0], q[1] - 0.22, r"$K=\QQ(\sqrt{-%d})$" % d, anchor="north")
        y0 = q[1] - 0.95
        for k, (m, col) in enumerate(taus):
            yy = y0 - 0.46 * k
            xx = q[0] - 1.05
            F.flat("  \\draw[%s,line width=1.0pt] (%s,%s) -- (%s,%s);\n"
                   % (col, f4(xx - 0.30), f4(yy), f4(xx + 0.10), f4(yy)))
            F.flat("  \\fill[%s,draw=white,line width=0.45pt] (%s,%s) circle "
                   "(1.55pt);\n" % (col, f4(xx - 0.10), f4(yy)))
            F.label(xx + 0.22, yy, r"$\tau=%d+\sqrt{-%d}$" % (m, d),
                    anchor="west", color=col)
        # the seam
        q = F.P(on(cx, 0, ZT))
        F.label(q[0], q[1] + 0.20, r"$c(\tau)^{n}=1$", anchor="south")
    F.write()


if __name__ == "__main__":
    which = sys.argv[1:] or ["weilcube", "hodgespike", "charactergrid",
                             "witness", "chernline", "annihilator"]
    for w in which:
        globals()["fig_" + w]()
