"""gf.py -- the Q-Lie algebra g_F = su(V,H) of a member of the (F,2)-family through
A = X x Xhat (track A1): 16x16 rational matrices X (acting on the generators of
H^1(A,Q), column = image) with [X,R] = [X,M] = 0, X G + G X^T = 0 (G the Gram
matrix of eta), and Tr(a X) = 0 for a in {1, R, M, RM} (trace over F zero)."""
from fractions import Fraction as Fr
import random
import flint
from amodel import *


def lie_algebra(Am, eta):
    n = 16
    G = Am.gram(eta)
    R, M = Am.R, Am.M
    RM = matmul(R, M)
    I = ident(n)
    # unknown X_{ab} -> index a*n+b
    eqs = []

    def commut(S):
        # (X S - S X)_{ij} = sum_k X_ik S_kj - S_ik X_kj
        for i in range(n):
            for j in range(n):
                row = {}
                for k in range(n):
                    if S[k][j] != 0:
                        row[i * n + k] = row.get(i * n + k, 0) + S[k][j]
                    if S[i][k] != 0:
                        row[k * n + j] = row.get(k * n + j, 0) - S[i][k]
                row = {a: b for a, b in row.items() if b != 0}
                if row:
                    eqs.append(row)
    commut(R)
    commut(M)
    # X G + G X^T = 0: (XG)_ij + (G X^T)_ij = sum_k X_ik G_kj + G_ik X_jk
    for i in range(n):
        for j in range(n):
            row = {}
            for k in range(n):
                if G[k][j] != 0:
                    row[i * n + k] = row.get(i * n + k, 0) + G[k][j]
                if G[i][k] != 0:
                    row[j * n + k] = row.get(j * n + k, 0) + G[i][k]
            row = {a: b for a, b in row.items() if b != 0}
            if row:
                eqs.append(row)
    for S in (I, R, M, RM):
        # Tr(S X) = sum_{i,k} S_ik X_ki
        row = {}
        for i in range(n):
            for k in range(n):
                if S[i][k] != 0:
                    row[k * n + i] = row.get(k * n + i, 0) + S[i][k]
        eqs.append(row)
    Mq = flint.fmpq_mat(len(eqs), n * n)
    for r, e in enumerate(eqs):
        for a, b in e.items():
            b = Fr(b)
            Mq[r, a] = flint.fmpq(b.numerator, b.denominator)
    basis = []
    for v in fmpq_nullspace(Mq):
        basis.append([[v[a * n + b] for b in range(n)] for a in range(n)])
    return basis


def lie_closure_dim_modp(gens, p=1000003):
    """dimension mod p of the Lie algebra generated by gens; a LOWER bound for the
    dimension over Q (rank mod p <= rank over Q)."""
    n = len(gens[0])
    def md(X):
        return [[(x.numerator * pow(x.denominator, -1, p)) % p for x in r] for r in X]
    def mm(A, B):
        return [[sum(A[i][k] * B[k][j] for k in range(n)) % p for j in range(n)] for i in range(n)]
    def br(A, B):
        AB, BA = mm(A, B), mm(B, A)
        return [[(AB[i][j] - BA[i][j]) % p for j in range(n)] for i in range(n)]
    basis = []
    elems = []
    def insert(X):
        v = [x for r in X for x in r]
        for piv, row in basis:
            if v[piv]:
                f = v[piv]
                v = [(a - f * b) % p for a, b in zip(v, row)]
        for i, a in enumerate(v):
            if a:
                inv = pow(a, -1, p)
                v = [(x * inv) % p for x in v]
                for k in range(len(basis)):
                    piv, row = basis[k]
                    if row[i]:
                        f = row[i]
                        basis[k] = (piv, [(x - f * y) % p for x, y in zip(row, v)])
                basis.append((i, v))
                return True
        return False
    frontier = []
    for X in gens:
        Xm = md(X)
        if insert(Xm):
            elems.append(Xm); frontier.append(Xm)
    while frontier:
        new = []
        for A in frontier:
            for B in list(elems):
                C = br(A, B)
                if insert(C):
                    elems.append(C); new.append(C)
        frontier = new
    return len(basis)


def random_element(basis, rng, lo=-2, hi=2):
    cs = [rng.randint(lo, hi) for _ in basis]
    n = len(basis[0])
    return [[sum(c * b[i][j] for c, b in zip(cs, basis)) for j in range(n)] for i in range(n)]
