#!/usr/bin/env python3
"""
exceptional_classes.py

The two statements of the frontier that are not reductions, and what the
semiregularity form of the propagation statement forces.  Item (XXXV).

Three computations, all in exact arithmetic.

  (A) Mumford type.  Let X be an abelian fourfold whose Hodge group is a
      Q-form of SL(2)^3 acting on H^1(X) = V_1 (x) V_2 (x) V_3, the tensor
      product of the three standard representations.  The Hodge classes of
      X and of X x X, tensored with C, are the invariants of SL(2)^3 in
      wedge^*(V) and in wedge^*(V + V).  The script decomposes every wedge
      power of V under SL(2)^3 by peeling highest weights, finds one
      invariant in wedge^2 V and one in wedge^4 V, so that the Hodge ring of
      X is generated by the polarisation, and finds eight invariants in
      wedge^4(V + V).  It then builds the exterior algebra of V + V (of
      dimension 2^16) far enough to multiply the three divisor classes
      psi_11, psi_12, psi_22 of X x X, and finds that their six pairwise
      products are linearly independent, so that the divisor classes generate
      a six-dimensional space in H^4(X x X); and it counts the Sp(8)
      invariants in wedge^4(V + V) by the Weyl character formula, finding
      six.  So B^2(X x X) has dimension eight and D^2(X x X) dimension six:
      two exceptional Hodge classes, on a variety with no Weil structure.
      This is the computation behind the proposition that the reduction of
      Hodge classes on abelian varieties to Weil classes is false as a
      statement about Hodge rings.

  (B) Abelian type.  A Hodge structure lying in the tensor category generated
      by the H^1 of abelian varieties has a Mumford-Tate group on whose Lie
      algebra the Hodge cocharacter acts with weights in {-1, 0, 1}.  For the
      weight three Hodge structure H^3 of a smooth quintic threefold, with
      h^{3,0} = 1, the Lie algebra of Sp(H^3) contains the rank one map sending
      the (0,3) part to the (3,0) part, of adjoint weight 3.  The script
      records the Hodge numbers (1, 101, 101, 1) from the Jacobian ring of the
      Fermat quintic, exhibits the element of adjoint weight 3 in a
      four-dimensional model with the same weights, checks that it lies in
      the symplectic Lie algebra, and checks that no difference of two
      weights from {0, 1} leaves {-1, 0, 1}.

  (C) The annihilator of the Weil class in Hochschild cohomology.  For n = 2
      and n = 3 the script builds H^*(A, C) = wedge^*(H^{1,0} + H^{0,1}) with
      the eigenspace decomposition of the Weil structure, the Weil class
      omega = alpha_+ + alpha_-, and the action of HT^2 = H^{0,2} + H^1(T) +
      H^0(wedge^2 T) on it, and computes the annihilator of omega: it has
      dimension 4 n^2, and it is the sum of the mixed block of H^{0,2}
      (n^2), the K-linear deformations in H^1(T) (2 n^2), and the mixed
      bivectors (n^2).  It also checks the two pieces of linear algebra used
      in the theorem: the ideal generated by the mixed block in the exterior
      algebra on 2n generators has codimension 2^{n+1} - 1, with the
      quotient of dimension 2 binom(n,k) in each degree k >= 1; and if two
      subspaces spanning a space of dimension at least two have all mixed
      wedge products zero, one of them is zero (checked over F_3 for
      dimension 2 and 3).
"""

import itertools
import sys
from collections import Counter
from fractions import Fraction as Fr
from math import comb

PASS, FAIL = [], []


def check(name, ok, detail=""):
    tag = "PASS" if ok else "FAIL"
    (PASS if ok else FAIL).append(name)
    print("    [%s] %s" % (tag, name))
    if detail:
        for line in detail.split("\n"):
            print("           " + line)


# ------------------------------------------------------------------ (A)
# weights of V_1 (x) V_2 (x) V_3 under the maximal torus of SL(2)^3
WTS = [(a, b, c) for a in (1, -1) for b in (1, -1) for c in (1, -1)]


def wedge_char(k, wts=WTS):
    C = Counter()
    for S in itertools.combinations(range(len(wts)), k):
        w = tuple(sum(wts[i][j] for i in S) for j in range(3))
        C[w] += 1
    return C


def decompose_sl2cubed(C):
    """peel highest weights; irreducibles V(a,b,c) have weights
    (a-2i, b-2j, c-2k)"""
    C = Counter(C)
    res = {}
    while any(v != 0 for v in C.values()):
        hw = max([w for w, m in C.items() if m > 0],
                 key=lambda w: (w[0] + w[1] + w[2], w))
        a, b, c = hw
        m = C[hw]
        if m < 0:
            raise RuntimeError("negative multiplicity: not a character")
        res[hw] = m
        for i in range(a + 1):
            for j in range(b + 1):
                for k in range(c + 1):
                    C[(a - 2 * i, b - 2 * j, c - 2 * k)] -= m
    return res


def part_A():
    print("  (A) the self-product of a Mumford fourfold")
    D = {k: decompose_sl2cubed(wedge_char(k)) for k in range(9)}
    check("wedge^k V has dimension binom(8,k) after decomposition",
          all(sum(m * (l[0] + 1) * (l[1] + 1) * (l[2] + 1)
                  for l, m in D[k].items()) == comb(8, k) for k in range(9)))
    inv2 = D[2].get((0, 0, 0), 0)
    inv4 = D[4].get((0, 0, 0), 0)
    check("SL(2)^3 invariants: one in wedge^2 V, one in wedge^4 V",
          inv2 == 1 and inv4 == 1,
          "so B^1(X) and B^2(X) are spanned by the polarisation and its "
          "square: X itself has no exceptional class\n"
          "wedge^2 V = " + str(D[2]) + "\nwedge^4 V = " + str(D[4]))

    def hom(a, b):
        return sum(D[a].get(l, 0) * D[b].get(l, 0)
                   for l in set(D[a]) | set(D[b]))

    inv_prod = [hom(a, 4 - a) for a in range(5)]
    n_sl = sum(inv_prod)
    check("SL(2)^3 invariants in wedge^4(V + V): 8, distributed 1,1,4,1,1",
          n_sl == 8 and inv_prod == [1, 1, 4, 1, 1],
          "Hom(wedge^a V, wedge^{4-a} V) for a = 0..4: %s" % inv_prod)
    ns_rank = hom(0, 2) + hom(1, 1) + hom(2, 0)
    check("Hodge classes in H^2(X x X): 3 (the Neron-Severi rank)",
          ns_rank == 3)

    # Sp(8) invariants in wedge^4(V (x) C^2) by the Weyl character formula:
    # mult of the trivial representation = sum_w sgn(w) m(rho - w rho)
    sp_wts = []
    for i in range(4):
        e = [0, 0, 0, 0]
        e[i] = 1
        sp_wts += [tuple(e), tuple(-x for x in e)]
    sp_wts2 = sp_wts + sp_wts          # V (x) C^2: every weight twice
    char4 = Counter()
    for S in itertools.combinations(range(16), 4):
        w = tuple(sum(sp_wts2[i][j] for i in S) for j in range(4))
        char4[w] += 1
    char4_single = Counter()
    for S in itertools.combinations(range(8), 4):
        w = tuple(sum(sp_wts[i][j] for i in S) for j in range(4))
        char4_single[w] += 1
    rho = (4, 3, 2, 1)

    def trivial_mult(char):
        tot = 0
        for perm in itertools.permutations(range(4)):
            # sign of the permutation
            sgn = 1
            p = list(perm)
            for i in range(4):
                for j in range(i + 1, 4):
                    if p[i] > p[j]:
                        sgn = -sgn
            for signs in itertools.product((1, -1), repeat=4):
                s = sgn
                for x in signs:
                    if x < 0:
                        s = -s
                wr = tuple(signs[i] * rho[perm[i]] for i in range(4))
                mu = tuple(rho[i] - wr[i] for i in range(4))
                tot += s * char.get(mu, 0)
        return tot

    sp_single = trivial_mult(char4_single)
    sp_double = trivial_mult(char4)
    check("Sp(8) invariants: one in wedge^4 V, six in wedge^4(V + V)",
          sp_single == 1 and sp_double == 6)

    # the six products of the three divisor classes in wedge^4(V + V)
    # basis of W = V + V: indices 0..7 first copy, 8..15 second copy;
    # psi on V pairs e_i with e_{i+4}
    def wedge2(i, j):
        # a 2-form as a dict {(i,j): coeff} with i < j
        if i < j:
            return {(i, j): Fr(1)}
        return {(j, i): Fr(-1)}

    def add(a, b, c=Fr(1)):
        r = dict(a)
        for k, v in b.items():
            r[k] = r.get(k, Fr(0)) + c * v
            if r[k] == 0:
                del r[k]
        return r

    def psi(copy1, copy2):
        f = {}
        for i in range(4):
            f = add(f, wedge2(8 * copy1 + i, 8 * copy2 + i + 4))
            if copy1 != copy2:
                # symmetrise: psi_12(x,y) = psi(x_1, y_2), as a 2-form on W
                f = add(f, wedge2(8 * copy2 + i, 8 * copy1 + i + 4))
        return f

    def mult(a, b):
        r = {}
        for (i, j), u in a.items():
            for (k, l), v in b.items():
                idx = [i, j, k, l]
                if len(set(idx)) < 4:
                    continue
                # sort with sign
                sgn = 1
                arr = idx[:]
                for x in range(4):
                    for y in range(3 - x):
                        if arr[y] > arr[y + 1]:
                            arr[y], arr[y + 1] = arr[y + 1], arr[y]
                            sgn = -sgn
                key = tuple(arr)
                r[key] = r.get(key, Fr(0)) + sgn * u * v
                if r[key] == 0:
                    del r[key]
        return r

    P = {"11": psi(0, 0), "12": psi(0, 1), "22": psi(1, 1)}
    prods = []
    names = []
    for a, b in [("11", "11"), ("11", "12"), ("11", "22"),
                 ("12", "12"), ("12", "22"), ("22", "22")]:
        prods.append(mult(P[a], P[b]))
        names.append("psi_%s psi_%s" % (a, b))
    keys = sorted(set().union(*[p.keys() for p in prods]))
    M = [[p.get(k, Fr(0)) for k in keys] for p in prods]
    rank = rank_of(M)
    check("the six products of divisor classes on X x X are independent",
          rank == 6, "rank of %s is %d" % (", ".join(names), rank))
    check("B^2(X x X) has dimension 8, D^2(X x X) dimension 6: "
          "two exceptional classes",
          n_sl - sp_double == 2 and rank == sp_double)


def rank_of(rows):
    M = [list(r) for r in rows]
    if not M:
        return 0
    nr, nc = len(M), len(M[0])
    r = 0
    for c in range(nc):
        piv = None
        for i in range(r, nr):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][c]
        M[r] = [x / pv for x in M[r]]
        for i in range(nr):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [x - f * y for x, y in zip(M[i], M[r])]
        r += 1
        if r == nr:
            break
    return r


# ------------------------------------------------------------------ (B)
def part_B():
    print("  (B) the Hodge structure of a quintic threefold is not of "
          "abelian type")
    # Jacobian ring of the Fermat quintic: C[x_0..x_4]/(x_i^4); Griffiths:
    # H^{3-p,p}_prim = R_{5(p+1)-5}
    def dimR(k):
        return sum(1 for e in itertools.product(range(4), repeat=5)
                   if sum(e) == k)
    hodge = [dimR(5 * (p + 1) - 5) for p in range(4)]
    check("Hodge numbers of a quintic threefold: (1, 101, 101, 1), total 204",
          hodge == [1, 101, 101, 1] and sum(hodge) == 204)
    # a four-dimensional model with one vector of each weight 3, 2, 1, 0 and
    # the symplectic form pairing 3 with 0 and 2 with 1
    J = [[0, 0, 0, 1], [0, 0, 1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]]
    mu = [3, 2, 1, 0]
    # X = e_3 (x) psi(., e_3): X(v) = psi(v, e_3) e_3, e_3 the weight 3 vector
    # (index 0); psi(v, e_0) = J[v][0] nonzero only for v = index 3 (weight 0)
    X = [[0] * 4 for _ in range(4)]
    for v in range(4):
        X[0][v] = J[v][0]
    # symplectic: X^T J + J X = 0
    def matmul(A, B):
        return [[sum(A[i][k] * B[k][j] for k in range(4)) for j in range(4)]
                for i in range(4)]
    XT = [[X[j][i] for j in range(4)] for i in range(4)]
    S = matmul(XT, J)
    T = matmul(J, X)
    symp = all(S[i][j] + T[i][j] == 0 for i in range(4) for j in range(4))
    # adjoint weight: [mu, X] = 3 X
    adj_ok = all((mu[i] - mu[j]) * X[i][j] == 3 * X[i][j]
                 for i in range(4) for j in range(4)) and any(
        X[i][j] != 0 for i in range(4) for j in range(4))
    check("the map (0,3) -> (3,0) lies in sp and has adjoint weight 3",
          symp and adj_ok)
    diffs = sorted({p - q for p in (0, 1) for q in (0, 1)})
    check("weight one structures: adjoint weights of the Hodge cocharacter "
          "lie in {-1,0,1}", diffs == [-1, 0, 1])
    diffs3 = sorted({p - q for p in range(4) for q in range(4)
                     if hodge[3 - p] and hodge[3 - q]})
    check("weight three with h^{3,0} = 1: adjoint weights -3..3 occur",
          diffs3 == list(range(-3, 4)))


# ------------------------------------------------------------------ (C)
class Ext:
    """exterior algebra on m generators over Q, elements as dict mask->coef"""

    def __init__(self, m):
        self.m = m

    @staticmethod
    def sign(a, b):
        # sign of merging masks a and b (disjoint)
        s = 1
        x = b
        while x:
            lo = x & -x
            # number of bits of a above lo
            cnt = bin(a >> (lo.bit_length())).count("1")
            if cnt % 2:
                s = -s
            x ^= lo
        return s

    def mul(self, u, v):
        r = {}
        for a, ca in u.items():
            for b, cb in v.items():
                if a & b:
                    continue
                s = self.sign(a, b)
                k = a | b
                r[k] = r.get(k, Fr(0)) + s * ca * cb
                if r[k] == 0:
                    del r[k]
        return r

    def gen(self, i):
        return {1 << i: Fr(1)}

    def contract(self, i, u):
        """interior product with the dual of generator i (odd derivation)"""
        r = {}
        for a, ca in u.items():
            if not (a >> i) & 1:
                continue
            # sign: number of generators below i in a
            below = bin(a & ((1 << i) - 1)).count("1")
            s = -1 if below % 2 else 1
            k = a ^ (1 << i)
            r[k] = r.get(k, Fr(0)) + s * ca
            if r[k] == 0:
                del r[k]
        return r


def add(u, v, c=Fr(1)):
    r = dict(u)
    for k, x in v.items():
        r[k] = r.get(k, Fr(0)) + c * x
        if r[k] == 0:
            del r[k]
    return r


def part_C():
    print("  (C) the annihilator of the Weil class in HT^2, and two lemmas")
    for n in (2, 3):
        # generators: 0..n-1 : V_+^{1,0};  n..2n-1 : V_-^{1,0};
        #             2n..3n-1 : V_+^{0,1}; 3n..4n-1 : V_-^{0,1}
        m = 4 * n
        E = Ext(m)
        hol = list(range(2 * n))              # (1,0) generators
        ahol = list(range(2 * n, 4 * n))      # (0,1) generators
        Vp = list(range(n)) + list(range(2 * n, 3 * n))
        Vm = list(range(n, 2 * n)) + list(range(3 * n, 4 * n))

        def top(idx):
            u = {0: Fr(1)}
            for i in idx:
                u = E.mul(u, E.gen(i))
            return u
        alpha_p = top(Vp)
        alpha_m = top(Vm)
        omega = add(alpha_p, alpha_m)

        # HT^2 basis and its action on omega
        # (a) z = e_i ^ e_j, i<j in (0,1): wedge
        # (b) v = e_j (x) dual(e_i), i in (1,0), j in (0,1): derivation
        #     replacing e_i by e_j:  v . w = e_j ^ (iota_i w)  (up to sign
        #     conventions, which do not affect the kernel)
        # (c) pi = dual(e_i) ^ dual(e_j), i<j in (1,0): iota_i iota_j
        ops = []
        labels = []
        for i, j in itertools.combinations(ahol, 2):
            ops.append(lambda w, i=i, j=j: E.mul(E.mul(E.gen(i), E.gen(j)), w))
            kind = "mixed" if ((i < 3 * n) != (j < 3 * n)) else "pure"
            labels.append(("z", kind))
        for i in hol:
            for j in ahol:
                ops.append(lambda w, i=i, j=j: E.mul(E.gen(j), E.contract(i, w)))
                same = ((i < n) == (j < 3 * n))
                labels.append(("v", "Klinear" if same else "Kanti"))
        for i, j in itertools.combinations(hol, 2):
            ops.append(lambda w, i=i, j=j: E.contract(i, E.contract(j, w)))
            kind = "mixed" if ((i < n) != (j < n)) else "pure"
            labels.append(("pi", kind))
        images = [op(omega) for op in ops]
        keys = sorted(set().union(*[im.keys() for im in images]) | {0})
        M = [[im.get(k, Fr(0)) for k in keys] for im in images]
        rk = rank_of(M)
        dimHT2 = len(ops)
        ann = dimHT2 - rk
        check("n=%d: dim HT^2 = %d and dim Ann(omega) = 4n^2 = %d"
              % (n, comb(2 * n, 2) + 4 * n * n + comb(2 * n, 2), 4 * n * n),
              dimHT2 == 2 * comb(2 * n, 2) + 4 * n * n and ann == 4 * n * n)
        # the predicted annihilator: mixed z, K-linear v, mixed pi; check
        # that each of these kills omega and that they are independent
        pred = [i for i, l in enumerate(labels)
                if l in (("z", "mixed"), ("v", "Klinear"), ("pi", "mixed"))]
        kills = all(not images[i] for i in pred)
        check("n=%d: the mixed z, the K-linear v and the mixed pi kill omega, "
              "%d + %d + %d = %d of them"
              % (n, n * n, 2 * n * n, n * n, len(pred)),
              kills and len(pred) == 4 * n * n)
        others = [i for i in range(len(ops)) if i not in pred]
        Mo = [M[i] for i in others]
        check("n=%d: the remaining %d classes act injectively" % (n, len(others)),
              rank_of(Mo) == len(others))

        # the ideal generated by the mixed block in wedge^*(V_+^{0,1} + V_-^{0,1})
        L = Ext(2 * n)
        gens = [L.mul(L.gen(i), L.gen(j)) for i in range(n)
                for j in range(n, 2 * n)]
        # the ideal in degree k: span of gens ^ wedge^{k-2}
        dims = []
        for k in range(2 * n + 1):
            span = []
            for g in gens:
                for S in itertools.combinations(range(2 * n), k - 2) if k >= 2 else []:
                    u = {0: Fr(1)}
                    for i in S:
                        u = L.mul(u, L.gen(i))
                    span.append(L.mul(g, u))
            ks = sorted(set().union(*[s.keys() for s in span])) if span else []
            r = rank_of([[s.get(x, Fr(0)) for x in ks] for s in span]) if span else 0
            dims.append(comb(2 * n, k) - r)
        expected = [1] + [2 * comb(n, k) for k in range(1, 2 * n + 1)]
        check("n=%d: the quotient by the ideal of the mixed block has "
              "dimensions %s in degrees 0..%d" % (n, expected, 2 * n),
              dims == expected and sum(dims) == 2 ** (n + 1) - 1)

    # linear algebra lemma over F_3: subspaces I1, I2 of N with I1 + I2 = N,
    # dim N in {2,3}, all mixed wedges zero  =>  I1 = 0 or I2 = 0
    for c in (2, 3):
        p = 3
        vecs = [v for v in itertools.product(range(p), repeat=c) if any(v)]

        def span(vs):
            S = {tuple([0] * c)}
            for v in vs:
                S = {tuple((a + t * b) % p for a, b in zip(s, v))
                     for s in S for t in range(p)}
            return S

        def wedge_zero(a, b):
            return all((a[i] * b[j] - a[j] * b[i]) % p == 0
                       for i in range(c) for j in range(i + 1, c))
        subspaces = set()
        for k in range(0, c + 1):
            for vs in itertools.combinations(vecs, k):
                subspaces.add(frozenset(span(vs)))
        bad = 0
        total = 0
        for I1 in subspaces:
            for I2 in subspaces:
                if len(span(list(I1) + list(I2))) != p ** c:
                    continue
                total += 1
                if all(wedge_zero(a, b) for a in I1 for b in I2):
                    if len(I1) > 1 and len(I2) > 1:
                        bad += 1
        check("dim N = %d over F_3: mixed wedges all zero forces one subspace "
              "to vanish (%d pairs examined)" % (c, total), bad == 0)


def main():
    part_A()
    part_B()
    part_C()
    print("  exceptional_classes: %d passed, %d failed" % (len(PASS), len(FAIL)))
    return 0 if not FAIL else 1


if __name__ == "__main__":
    sys.exit(main())
