"""Item (LXXII), part (H): the rank of the fourfold products, certified.

The rank of prop:fourfoldrank is computed here in ball arithmetic (Arb, through
python-flint, at 128 bits), so that every number carries a rigorous error
bound and the rank is proved, not estimated.  Nothing is computed by
quadrature and nothing in floating point.  The method rests on four exact
facts, each proved in the paper or recalled below.

  1. Theta functions.  On E_0 = C/Z[i] a line bundle of degree d > 0 with
     semicharacter exp(2 pi i r) has, in the symmetric unitary gauge, the
     basis F_k (k = 0, ..., d - 1) of item (LXXII), with |F_k|^2 integrating
     to (2d)^(-1/2), the F_k pairwise orthogonal, and nabla_z^l F_k of norm
     squared l! (pi d)^l (2d)^(-1/2).  The series converge with the explicit
     tail bound of `tail`, so every value is an exact ball.

  2. Levels of a product.  For holomorphic sections a, b of degrees d_a, d_b,
     nabla(a b) is of level one and H = d_b (nabla a) b - d_a a (nabla b) is
     holomorphic, since [nabla_zbar, nabla_z] = -pi d; so
     (nabla a) b = d_a/(d_a + d_b) nabla(a b) + H/(d_a + d_b).  Every integral
     of item (LXXII) is therefore an inner product of a holomorphic section
     with a theta function, that is a coefficient of a holomorphic section in
     the basis F_k, multiplied by (2d)^(-1/2).

  3. Coefficients by interpolation.  A holomorphic section of degree d is
     determined by its values at d points at which the matrix (F_k(z_p)) is
     invertible; Arb solves that system and returns balls that contain the
     exact coefficients.

  4. Descent.  The sections on B_j are the sections on the cover E_0 x E_0
     invariant under the kernel K of phi_zeta, generated by the half periods
     k_1 = (1/2, 1/2) and k_2 = (i/2, i/2).  Each acts by
     R f(w) = c^(-1) exp(-i pi Im H(w, k)) f(w + k), a tensor product of
     operators on the two curves, and R_1^2 = R_2^2 = 1, R_1 R_2 = R_2 R_1
     exactly (checked below in rational arithmetic), so
     P = (1 + R_1)(1 + R_2)/4 projects onto the invariant sections.  The
     theta basis of B_j pulls back to the cover by phi_zeta exactly (the
     symmetric gauge is invariant under the unitary map phi_zeta / sqrt 2),
     and its coefficients are found by interpolation, as in 3.

With these, the 729 x 192 matrix of prop:fourfoldrank is a matrix of balls,
and the determinant of its Gram matrix is a ball that does not contain 0, so
the rank is exactly 192 at the chosen data.  The data (semicharacters,
sample points, components) are exact rationals drawn with a fixed seed.

  (H) checks:
    - the group relations of K and the dimensions |det| of the invariant
      sections, exactly;
    - the level decomposition against the quadrature of item (LXXII) on one
      curve (to 1e-11);
    - rank 192 on the 192 classes of type (1,1,0) at p = 0, t = (2, 5, 6),
      and rank 12 on each of the sixteen pieces, certified;
    - the same with x1 x2^zeta = 0 = x2^zeta x3^zeta, certified, the kernels
      of dimensions 11 and 19 being certified as well;
    - the same with the relative sign of the two terms reversed, and at
      t = (2, 5, 7), certified.
"""
import itertools
import random
import sys
from fractions import Fraction as Fr

from flint import acb, acb_mat, arb, ctx

ctx.prec = 128
PI = arb.pi()
PASS, FAIL = [], []


def check(name, ok, detail=""):
    (PASS if ok else FAIL).append(name)
    print(("  [PASS] " if ok else "  [FAIL] ") + name +
          (("   " + detail) if detail else ""))


def fa(q):
    """The exact ball of a rational number."""
    q = Fr(q)
    return arb(q.numerator) / q.denominator


def cis(q):
    """exp(2 pi i q) for rational q."""
    q = Fr(q) % 1
    return acb(fa(2 * q)).exp_pi_i()


def zeros(r, c):
    return acb_mat(r, c)


def mat(rows):
    return acb_mat([[x for x in row] for row in rows])


def kron(A, B):
    ra, ca, rb, cb = A.nrows(), A.ncols(), B.nrows(), B.ncols()
    out = acb_mat(ra * rb, ca * cb)
    for i in range(ra):
        for j in range(ca):
            a = A[i, j]
            for k in range(rb):
                for l in range(cb):
                    out[i * rb + k, j * cb + l] = a * B[k, l]
    return out


def ident(n):
    out = acb_mat(n, n)
    for i in range(n):
        out[i, i] = acb(1)
    return out


# ----------------------------------------------------------------------
# 1. theta functions on E_0 in the symmetric unitary gauge

MTERMS = 10


def tail(d, Y, level):
    """Upper bound for sum_{|m| > MTERMS} |P_level(xi)| exp(-pi d xi^2),
    where |xi| >= |m| - Y and |xi| <= |m| + Y, P_0 = 1, P_1 = 2 pi i d xi.
    With j = |m| - Y >= J0 = MTERMS + 1 - Y and q = exp(-pi d J0), one has
    exp(-pi d j^2) <= q^j, |P| <= A + B j with A = 1 + 2 pi d (2Y),
    B = 2 pi d, and each j occurs for at most two m."""
    J0 = MTERMS + 1 - Y
    assert J0 >= 1
    q = (-PI * d * J0).exp()
    s0 = q ** J0 / (1 - q)
    s1 = q ** J0 * (arb(J0) / (1 - q) + q / (1 - q) ** 2)
    A = 1 + (2 * PI * d * 2 * Y if level else 0)
    B = 2 * PI * d if level else 0
    bound = 2 * (A * s0 + B * s1)
    return float(bound.mid() + bound.rad()) * 2.0


class CBundle:
    """Degree d > 0, semicharacter exp(2 pi i r1) on 1 and exp(2 pi i ri) on
    i, with r1, ri rational.  F_k(z) = sum_m exp(-pi d xi^2 +
    2 pi i (d x y / 2 + n x - m ri)), s = k + alpha, alpha = r1 mod 1,
    n = s + m d, xi = y + m + s / d (the basis of item (LXXII))."""

    def __init__(self, d, r1, ri):
        assert d > 0
        self.d, self.r1, self.ri = d, Fr(r1) % 1, Fr(ri) % 1
        self.alpha = self.r1
        self.cache = {}

    def value(self, k, z, level=0):
        key = (k, z, level)
        if key in self.cache:
            return self.cache[key]
        x, y = z
        d = self.d
        s = k + self.alpha
        tot = acb(0)
        for m in range(-MTERMS, MTERMS + 1):
            n = s + m * d
            xi = y + m + s / d
            ph = Fr(d) * x * y / 2 + n * x - m * self.ri
            t = (-PI * d * fa(xi * xi)).exp() * cis(ph)
            if level == 1:
                t = t * acb(0, 2 * PI * d * fa(xi))
            tot += t
        Y = int(abs(y)) + 2
        r = tail(d, Y, level)
        tot += acb(arb(0, r), arb(0, r))
        self.cache[key] = tot
        return tot

    def values(self, pts, level=0):
        return [[self.value(k, z, level) for z in pts] for k in range(self.d)]

    def floats(self):
        import numpy as np
        return (np.exp(2j * np.pi * float(self.r1)),
                np.exp(2j * np.pi * float(self.ri)))


def rand_points(rng, n, lo=0, span=1):
    return [(Fr(rng.randrange(1, 2 ** 12), 2 ** 12) * span + lo,
             Fr(rng.randrange(1, 2 ** 12), 2 ** 12) * span + lo)
            for _ in range(n)]


def interp(bundle, pts, columns):
    """Coefficients in the basis F_k of the holomorphic sections whose values
    at the points pts (len(pts) = d) are the given columns."""
    d = bundle.d
    V = acb_mat([[bundle.value(k, z) for k in range(d)] for z in pts])
    R = acb_mat([[col[p] for col in columns] for p in range(d)])
    return V.solve(R)


# ----------------------------------------------------------------------
# 2. the per-curve maps of item (LXXII), by the decomposition into levels

def curve_ops(bS, bOm, bU, bE, bPhi, rng):
    """The tensors Cup, Dn, F0, F1 of item (LXXII) (CurveOps there) and the
    tensor coef0, as exact balls.  Returned as nested lists [s][o][u][w]
    (and coef0 as [s][o][g])."""
    dS, dO, dU, dE, dP = bS.d, bOm.d, bU.d, bE.d, bPhi.d
    assert dS + dE == dO and dU + dP == dE
    kO = fa(Fr(1, 2 * dO)).sqrt()                 # (2 d_Om)^(-1/2)
    kE4 = fa(2 * dE).sqrt().sqrt()               # (2 d_E)^(1/4)
    sq = (PI * dE).sqrt()
    # coef0, coef1: interpolation in the basis of Om
    pO = rand_points(rng, dO)
    S0, S1 = bS.values(pO), bS.values(pO, 1)
    E0, E1 = bE.values(pO), bE.values(pO, 1)
    cols0, colsH = [], []
    for s in range(dS):
        for g in range(dE):
            cols0.append([S0[s][p] * E0[g][p] for p in range(dO)])
            colsH.append([dS * E1[g][p] * S0[s][p] - dE * E0[g][p] * S1[s][p]
                          for p in range(dO)])
    C0, CH = interp(bOm, pO, cols0), interp(bOm, pO, colsH)
    coef0 = [[[C0[o, s * dE + g] * kO * kE4 for g in range(dE)]
              for o in range(dO)] for s in range(dS)]
    k1 = kO * kE4 / (sq * (dE + dS))
    coef1 = [[[CH[o, s * dE + g] * k1 for g in range(dE)]
              for o in range(dO)] for s in range(dS)]
    # P0, P0d, P1d: interpolation in the basis of E
    pE = rand_points(rng, dE)
    U0, U1 = bU.values(pE), bU.values(pE, 1)
    F0, F1 = bPhi.values(pE), bPhi.values(pE, 1)
    colsUF, colsH2 = [], []
    for u in range(dU):
        for w in range(dP):
            colsUF.append([U0[u][p] * F0[w][p] for p in range(dE)])
            colsH2.append([dP * U1[u][p] * F0[w][p] - dU * U0[u][p] * F1[w][p]
                           for p in range(dE)])
    CUF, CH2 = interp(bE, pE, colsUF), interp(bE, pE, colsH2)
    kE = 1 / kE4                                   # (2 d_E)^(-1/4)
    P0 = acb_mat(dE, dU * dP)
    P0d = acb_mat(dE, dU * dP)
    P1d = acb_mat(dE, dU * dP)
    for g in range(dE):
        for c in range(dU * dP):
            P0[g, c] = CUF[g, c] * kE
            P0d[g, c] = CH2[g, c] * kE / (dU + dP)
            P1d[g, c] = CUF[g, c] * kE * sq * dU / (dU + dP)
    A0 = acb_mat([[coef0[s][o][g] for g in range(dE)]
                  for s in range(dS) for o in range(dO)])
    A1 = acb_mat([[coef1[s][o][g] for g in range(dE)]
                  for s in range(dS) for o in range(dO)])
    out = {'Cup': A0 * P0, 'Dn': A1 * P0, 'F0': A0 * P0d, 'F1': A1 * P1d}
    shaped = {}
    for key, M in out.items():
        shaped[key] = [[[[M[s * dO + o, u * dP + w] for w in range(dP)]
                         for u in range(dU)] for o in range(dO)]
                       for s in range(dS)]
    return shaped, coef0, (pO, pE)


def q_tensor(bOm, bU, bQ, rng):
    """Q[o][u][m] = <U_u Q_m, F^Om_o>, the product into H^6(M3, M1)."""
    dO, dU, dQ = bOm.d, bU.d, bQ.d
    assert dU + dQ == dO
    kO = fa(Fr(1, 2 * dO)).sqrt()
    pO = rand_points(rng, dO)
    U0, Q0 = bU.values(pO), bQ.values(pO)
    cols = [[U0[u][p] * Q0[m][p] for p in range(dO)]
            for u in range(dU) for m in range(dQ)]
    C = interp(bOm, pO, cols)
    return [[[C[o, u * dQ + m] * kO for m in range(dQ)] for u in range(dU)]
            for o in range(dO)]


# ----------------------------------------------------------------------
# surfaces, pieces and covers, with exact rational semicharacters

BASIS = [(1, 0), (1j, 0), (0, 1), (0, 1j)]


def herm(x, y, H):
    return sum(x[a] * H[a][b] * complex(y[b]).conjugate()
               for a in range(2) for b in range(2))


class Piece:
    def __init__(self, H, vals):
        self.H = [[complex(H[a][b]) for b in range(2)] for a in range(2)]
        self.vals = [Fr(v) for v in vals]
        self.E = [[int(round(herm(BASIS[k], BASIS[l], self.H).imag))
                   for l in range(4)] for k in range(4)]

    def chi(self, n):
        q = sum(n[k] * n[l] * self.E[k][l] for k in range(4)
                for l in range(k + 1, 4))
        return (sum(n[k] * self.vals[k] for k in range(4)) + Fr(q, 2)) % 1


class Hom:
    def __init__(self, a, b):
        self.a, self.b = a, b
        self.H = [[b.H[i][j] - a.H[i][j] for j in range(2)] for i in range(2)]

    def chi(self, n):
        return (self.b.chi(n) - self.a.chi(n)) % 1

    def det(self):
        H = self.H
        return int(round((H[0][0] * H[1][1] - H[0][1] * H[1][0]).real))


class Cover:
    def __init__(self, zeta):
        self.zeta = complex(zeta)
        self.P = [[1, 1], [self.zeta, -self.zeta]]

    def phi(self, w):
        return (w[0] + w[1], self.zeta * w[0] - self.zeta * w[1])

    @staticmethod
    def nvec(x):
        return [int(round(x[0].real)), int(round(x[0].imag)),
                int(round(x[1].real)), int(round(x[1].imag))]

    def pullform(self, hom):
        P, H = self.P, hom.H
        return [[sum(P[a][i] * H[a][b] * complex(P[b][j]).conjugate()
                     for a in range(2) for b in range(2))
                 for j in range(2)] for i in range(2)]

    def bundles(self, hom):
        Hp = self.pullform(hom)
        assert abs(Hp[0][1]) < 1e-12
        out = []
        for col in (0, 1):
            d = int(round(Hp[col][col].real))
            e = [0, 0]
            e[col] = 1
            ie = [0, 0]
            ie[col] = 1j
            out.append(CBundle(d, hom.chi(self.nvec(self.phi(e))),
                               hom.chi(self.nvec(self.phi(ie)))))
        return out


def translation(b, k, rng):
    """Matrix of f -> exp(-i pi d Im(w conj k)) f(w + k) on the theta basis,
    for k = 1/2 or i/2, by interpolation."""
    pts = rand_points(rng, b.d)
    if k == '1/2':
        shift = [(x + Fr(1, 2), y) for x, y in pts]
        fac = [cis(-Fr(b.d) * y / 4) for x, y in pts]          # e^{-i pi d y/2}
    else:
        shift = [(x, y + Fr(1, 2)) for x, y in pts]
        fac = [cis(Fr(b.d) * x / 4) for x, y in pts]           # e^{i pi d x/2}
    cols = [[fac[p] * b.value(a, shift[p]) for p in range(b.d)]
            for a in range(b.d)]
    return interp(b, pts, cols)


def projector(cover, hom, Bu, Bv, rng):
    """The projector onto the K-invariant sections, with the exact check of
    the group relations: (R^u_{1/2})^2 = chi_1^u, (R^u_{i/2})^2 = chi_i^u,
    and R_{1/2} R_{i/2} = (-1)^{d/2} R_{i/2} R_{1/2} on a curve of degree d."""
    ck1 = hom.chi(cover.nvec(cover.phi((0.5, 0.5))))
    ck2 = hom.chi(cover.nvec(cover.phi((0.5j, 0.5j))))
    exact = ((-2 * ck1 + Bu.r1 + Bv.r1) % 1 == 0
             and (-2 * ck2 + Bu.ri + Bv.ri) % 1 == 0
             and Bu.d % 2 == 0 and Bv.d % 2 == 0
             and ((Bu.d + Bv.d) // 2) % 2 == 0)
    Ru1, Ru2 = translation(Bu, '1/2', rng), translation(Bu, 'i/2', rng)
    Rv1, Rv2 = translation(Bv, '1/2', rng), translation(Bv, 'i/2', rng)
    R1 = kron(Ru1, Rv1) * cis(-ck1)
    R2 = kron(Ru2, Rv2) * cis(-ck2)
    n = Bu.d * Bv.d
    I = ident(n)
    P = (I + R1) * (I + R2) * acb(fa(Fr(1, 4)))
    tr = sum((P[i, i] for i in range(n)), acb(0))
    det = abs(hom.det())
    balls = ((R1 * R1 - I).contains(acb_mat(n, n))
             and (R2 * R2 - I).contains(acb_mat(n, n))
             and (R1 * R2 - R2 * R1).contains(acb_mat(n, n)))
    dim_ok = tr.contains(det) and tr.rad() < 0.25
    return P, exact and balls, dim_ok


def zpull(cover, hom, d, Bu, Bv, rng):
    """Coefficients of the pulled-back theta basis of B (degree d in each
    coordinate) in the product basis of the cover, by interpolation."""
    assert hom.H[0][0] == hom.H[1][1] == d and hom.H[0][1] == 0
    B1 = CBundle(d, hom.chi([1, 0, 0, 0]), hom.chi([0, 1, 0, 0]))
    B2 = CBundle(d, hom.chi([0, 0, 1, 0]), hom.chi([0, 0, 0, 1]))
    n = Bu.d * Bv.d
    w1s, w2s = rand_points(rng, n), rand_points(rng, n)
    z = cover.zeta
    zr, zi = int(round(z.real)), int(round(z.imag))
    G = acb_mat(n, n)
    Z = acb_mat(n, d * d)
    for p in range(n):
        (x1, y1), (x2, y2) = w1s[p], w2s[p]
        for a in range(Bu.d):
            for b in range(Bv.d):
                G[p, a * Bv.d + b] = Bu.value(a, w1s[p]) * Bv.value(b, w2s[p])
        za = (x1 + x2, y1 + y2)
        dx, dy = x1 - x2, y1 - y2
        zb = (zr * dx - zi * dy, zr * dy + zi * dx)
        for i1 in range(d):
            for i2 in range(d):
                Z[p, i1 * d + i2] = B1.value(i1, za) * B2.value(i2, zb)
    return G.solve(Z)


# ----------------------------------------------------------------------
# the configuration of prop:fourfoldrank

def rfr(rng):
    return Fr(rng.randrange(2 ** 12), 2 ** 12)


class Config:
    def __init__(self, p, t1, t2, t3, rng):
        self.p, self.t, self.rng = p, (t1, t2, t3), rng
        self.M = [{t: Piece([[t, 0], [0, t]], [rfr(rng) for _ in range(4)])
                   for t in (t1, t2, t3)} for _ in range(3)]
        self.Lvals, self.surf = {}, {}

    def L(self, zj, j):
        key = (zj, j)
        if key not in self.Lvals:
            self.Lvals[key] = [rfr(self.rng) for _ in range(4)]
        z = complex(zj)
        return Piece([[self.p, z], [z.conjugate(), self.p]], self.Lvals[key])

    def surface(self, zj, j):
        key = (zj, j)
        if key in self.surf:
            return self.surf[key]
        rng = self.rng
        t1, t2, t3 = self.t
        M1, M2, M3 = self.M[j][t1], self.M[j][t2], self.M[j][t3]
        L = self.L(zj, j)
        C = Cover(zj)
        homs = {'S': Hom(M2, M3), 'Om': Hom(L, M3), 'U': Hom(L, M1),
                'E': Hom(L, M2), 'Phi': Hom(M1, M2), 'Q': Hom(M1, M3)}
        bund = {k: C.bundles(h) for k, h in homs.items()}
        ops, coef0 = [], []
        for c in (0, 1):
            o, c0, _ = curve_ops(*(bund[k][c] for k in
                                   ('S', 'Om', 'U', 'E', 'Phi')), rng)
            ops.append(o)
            coef0.append(c0)
        Q = [q_tensor(bund['Om'][c], bund['U'][c], bund['Q'][c], rng)
             for c in (0, 1)]
        proj, rel, dims = {}, True, True
        for k in ('Om', 'U'):
            P, r, dm = projector(C, homs[k], *bund[k], rng)
            proj[k] = P
            rel &= r
            dims &= dm
        Zc = zpull(C, homs['Phi'], t2 - t1, *bund['Phi'], rng)
        Sc = zpull(C, homs['S'], t3 - t2, *bund['S'], rng)
        dSu, dSv = bund['S'][0].d, bund['S'][1].d
        X1 = [[Sc[a * dSv + b, 0] for b in range(dSv)] for a in range(dSu)]
        sd = dict(ops=ops, coef0=coef0, Q=Q, proj=proj, Zc=Zc, X1=X1,
                  bund=bund, rel=rel, dims=dims)
        self.surf[key] = sd
        return sd


def rvec_proj(rng, P, conj=False):
    """P c (or conj(P) c) for a random rational vector c."""
    n = P.nrows()
    c = acb_mat([[acb(fa(Fr(rng.randrange(-2 ** 10, 2 ** 10), 2 ** 10)),
                      fa(Fr(rng.randrange(-2 ** 10, 2 ** 10), 2 ** 10)))]
                 for _ in range(n)])
    M = P.conjugate() if conj else P
    return M * c


def as_matrix(vec, r, c):
    return [[vec[i * c + j, 0] for j in range(c)] for i in range(r)]


def surfvec(sd, X1, x2, X3, opu, opv):
    """T[w, v] = sum X1[a,b] x2[c,e] X3[f,g] op_u[a][c][f][w] op_v[b][e][g][v],
    paired with the pulled-back theta basis of Hom(M1, M2) on B_j."""
    Ou, Ov = sd['ops'][0][opu], sd['ops'][1][opv]
    dSu, dOu, dUu, dPu = len(Ou), len(Ou[0]), len(Ou[0][0]), len(Ou[0][0][0])
    dSv, dOv, dUv, dPv = len(Ov), len(Ov[0]), len(Ov[0][0]), len(Ov[0][0][0])
    Ut = acb_mat([[Ou[a][c][f][w] for a in range(dSu) for c in range(dOu)
                   for f in range(dUu)] for w in range(dPu)])
    Vm = acb_mat([[Ov[b][e][g][v] for v in range(dPv)] for b in range(dSv)
                  for e in range(dOv) for g in range(dUv)])
    K = acb_mat(dSu * dOu * dUu, dSv * dOv * dUv)
    for a in range(dSu):
        for c in range(dOu):
            for f in range(dUu):
                row = (a * dOu + c) * dUu + f
                for b in range(dSv):
                    x1 = X1[a][b]
                    for e in range(dOv):
                        y = x1 * x2[c][e]
                        for g in range(dUv):
                            K[row, (b * dOv + e) * dUv + g] = y * X3[f][g]
    T = Ut * K * Vm
    flat = acb_mat(1, dPu * dPv)
    for w in range(dPu):
        for v in range(dPv):
            flat[0, w * dPv + v] = T[w, v]
    return flat * sd['Zc']


def right_sign():
    mu4 = [1, 1j, -1, -1j]
    out = []
    for z in itertools.product(range(4), repeat=3):
        if sum(z) % 4 == 0:
            out.append(tuple(mu4[k] for k in z))
    return out


def _midpoints(M):
    """The midpoints of an acb matrix as a complex numpy array."""
    import numpy as np
    return np.array([[complex(float(M[i, j].real.mid()),
                              float(M[i, j].imag.mid()))
                      for j in range(M.ncols())] for i in range(M.nrows())])


def _pivots(mid, rank):
    """Sorted indices of `rank` columns of a complex array chosen by QR with
    column pivoting (Businger-Golub): take the column of largest residual
    norm and project it out of the others, rank times.  Only the choice of
    columns uses floating point; the minor they give is certified in balls."""
    import numpy as np
    res = mid.copy()
    piv = []
    for _ in range(rank):
        norms = (np.abs(res) ** 2).sum(axis=0)
        norms[piv] = -1.0
        j = int(np.argmax(norms))
        piv.append(j)
        q = res[:, j] / np.linalg.norm(res[:, j])
        res = res - np.outer(q, q.conj() @ res)
    return sorted(piv)


def kernel_vectors(Lm, rank):
    """Balls containing exact vectors spanning the kernel of a matrix of
    exact rank `rank` (the rank is at most `rank` by theory; a nonsingular
    minor of that size is certified here)."""
    mid = _midpoints(Lm)
    cols = _pivots(mid, rank)
    rows = _pivots(mid[:, cols].T, rank)
    A = acb_mat([[Lm[i, j] for j in cols] for i in rows])
    free = [j for j in range(Lm.ncols()) if j not in cols]
    out = []
    for f in free:
        b = acb_mat([[Lm[i, f]] for i in rows])
        x = A.solve(b)
        v = acb_mat(Lm.ncols(), 1)
        v[f, 0] = acb(1)
        for t, j in enumerate(cols):
            v[j, 0] = -x[t, 0]
        out.append(v)
    return out


def contract_m1(X1, coef0u, coef0v):
    """m1[(c,e),(g,h)] = sum_ab X1[a][b] coef0_u[a][c][g] coef0_v[b][e][h]."""
    dSu, dOu, dEu = len(coef0u), len(coef0u[0]), len(coef0u[0][0])
    dSv, dOv, dEv = len(coef0v), len(coef0v[0]), len(coef0v[0][0])
    out = acb_mat(dOu * dOv, dEu * dEv)
    for c in range(dOu):
        for e in range(dOv):
            for g in range(dEu):
                for h in range(dEv):
                    s = acb(0)
                    for a in range(dSu):
                        for b in range(dSv):
                            s += X1[a][b] * coef0u[a][c][g] * coef0v[b][e][h]
                    out[c * dOv + e, g * dEv + h] = s
    return out


def contract_m2(X3, Qu, Qv):
    """m2[(c,e),(m,n)] = sum_fg X3[f][g] Q_u[c][f][m] Q_v[e][g][n]."""
    dOu, dUu, dQu = len(Qu), len(Qu[0]), len(Qu[0][0])
    dOv, dUv, dQv = len(Qv), len(Qv[0]), len(Qv[0][0])
    out = acb_mat(dOu * dOv, dQu * dQv)
    for c in range(dOu):
        for e in range(dOv):
            for m in range(dQu):
                for n in range(dQv):
                    s = acb(0)
                    for f in range(dUu):
                        for g in range(dUv):
                            s += X3[f][g] * Qu[c][f][m] * Qv[e][g][n]
                    out[c * dOv + e, m * dQv + n] = s
    return out


def basis_of_image(P, rank):
    """Columns of P spanning its image (rank certified by a minor)."""
    cols = _pivots(_midpoints(P), rank)
    B = acb_mat([[P[i, j] for j in cols] for i in range(P.nrows())])
    return B


def columns(cfg, zeta, rng, mc=False, sign=-1, info=None):
    sds = [cfg.surface(zeta[j], j) for j in range(3)]
    X1 = [sd['X1'] for sd in sds]
    X3, x2opts = [], []
    for m, sd in enumerate(sds):
        bU, bO = sd['bund']['U'], sd['bund']['Om']
        x3 = rvec_proj(rng, sd['proj']['U'])
        X3.append(as_matrix(x3, bU[0].d, bU[1].d))
        x2opts.append(None)
    terms = []
    if mc:
        K1, K2, Vy = [], [], []
        for m, sd in enumerate(sds):
            bO = sd['bund']['Om']
            nOm = abs(Hom(cfg.L(zeta[m], m), cfg.M[m][cfg.t[2]]).det())
            nE = abs(Hom(cfg.L(zeta[m], m), cfg.M[m][cfg.t[1]]).det())
            nM1M3 = abs(Hom(cfg.M[m][cfg.t[0]], cfg.M[m][cfg.t[2]]).det())
            B = basis_of_image(sd['proj']['Om'].conjugate(), nOm)
            m1 = contract_m1(X1[m], sd['coef0'][0], sd['coef0'][1])
            m2 = contract_m2(X3[m], sd['Q'][0], sd['Q'][1])
            L1 = m1.transpose() * B
            L2 = m2.transpose() * B
            k1 = [B * v for v in kernel_vectors(L1, nE)]
            k2 = [B * v for v in kernel_vectors(L2, nM1M3)]
            if info is not None:
                info.append((len(k1), len(k2)))
            K1.append(k1)
            K2.append(k2)
            Vy.append(B)
        for j, jp in itertools.permutations(range(3), 2):
            for _ in range(2):
                fac = []
                for m in range(3):
                    if m == j:
                        pool = K1[m]
                    elif m == jp:
                        pool = K2[m]
                    else:
                        pool = None
                    if pool is None:
                        v = rvec_proj(rng, sds[m]['proj']['Om'], conj=True)
                    else:
                        v = acb_mat(pool[0].nrows(), 1)
                        for vec in pool:
                            c = acb(fa(Fr(rng.randrange(-2 ** 10, 2 ** 10),
                                          2 ** 10)))
                            v = v + vec * c
                    fac.append(v)
                terms.append(fac)
        if info is not None:
            # x1 x2 = 0 and x2 x3 = 0 hold on the kernel vectors: the
            # images are balls containing 0
            ok = True
            for m in range(3):
                m1 = contract_m1(X1[m], sds[m]['coef0'][0],
                                 sds[m]['coef0'][1])
                m2 = contract_m2(X3[m], sds[m]['Q'][0], sds[m]['Q'][1])
                for v in K1[m]:
                    ok &= (m1.transpose() * v).contains(
                        acb_mat(m1.ncols(), 1))
                for v in K2[m]:
                    ok &= (m2.transpose() * v).contains(
                        acb_mat(m2.ncols(), 1))
            info.append(('zero products', ok))
    else:
        terms.append([rvec_proj(rng, sd['proj']['Om'], conj=True)
                      for sd in sds])
    terms = [[as_matrix(f, sds[m]['bund']['Om'][0].d,
                        sds[m]['bund']['Om'][1].d)
              for m, f in enumerate(fac)] for fac in terms]
    cache = {}

    def sv(m, opu, opv, r):
        key = (m, opu, opv, r)
        if key not in cache:
            cache[key] = surfvec(sds[m], X1[m], terms[r][m], X3[m], opu, opv)
        return cache[key]

    def tensor(assign):
        tot = acb_mat(1, 729)
        for r in range(len(terms)):
            vs = [sv(m, assign.get(2 * m, 'Cup'), assign.get(2 * m + 1, 'Cup'),
                     r) for m in range(3)]
            t = acb_mat(1, 729)
            for a in range(9):
                for b in range(9):
                    ab = vs[0][0, a] * vs[1][0, b]
                    for c in range(9):
                        t[0, (a * 9 + b) * 9 + c] = ab * vs[2][0, c]
            tot = tot + t
        return tot
    de = [sds[c // 2]['bund']['E'][c % 2].d for c in range(6)]
    du = [sds[c // 2]['bund']['U'][c % 2].d for c in range(6)]
    cols = []
    for a, b in [(a, b) for a in range(6) for b in range(a + 1, 6)
                 if a // 2 != b // 2]:
        den = PI * (du[a] + du[b])
        out = acb_mat(1, 729)
        for M in (0, 1):
            kA = (PI * de[b]).sqrt() / (PI * (de[a] * M + de[b]) * den)
            kB = (PI * de[a]).sqrt() / (PI * (de[a] + de[b] * M) * den)
            out = out + tensor({a: 'F%d' % M, b: 'Dn'}) * acb(kA) \
                + tensor({a: 'Dn', b: 'F%d' % M}) * acb(sign * kB)
        cols.append(out)
    A = acb_mat(729, len(cols))
    for j, col in enumerate(cols):
        for i in range(729):
            A[i, j] = col[0, i]
    return A, sds


def certified_rank(A):
    """True if the Gram determinant of the columns of A is a ball excluding
    0, which proves that the exact matrix has full column rank."""
    G = A.conjugate().transpose() * A
    det = G.det()
    return not det.contains(0), det


def singular_ratio(A):
    import numpy as np
    mid = np.array([[complex(float(A[i, j].real.mid()),
                             float(A[i, j].imag.mid()))
                     for j in range(A.ncols())] for i in range(A.nrows())])
    s = np.linalg.svd(mid, compute_uv=False)
    return s[-1] / s[0], max(float(A[i, j].rad()) for i in range(A.nrows())
                              for j in range(A.ncols())) / s[0]


def total(params, seed, mc=False, sign=-1, info=None):
    rng = random.Random(seed)
    cfg = Config(*params, rng)
    blocks, per = [], []
    for zeta in right_sign():
        B, sds = columns(cfg, zeta, rng, mc=mc, sign=sign, info=info)
        blocks.append(B)
        per.append(certified_rank(B)[0])
    A = acb_mat(729, 12 * len(blocks))
    for k, B in enumerate(blocks):
        for i in range(729):
            for j in range(12):
                A[i, 12 * k + j] = B[i, j]
    ok, det = certified_rank(A)
    rel = all(sd['rel'] and sd['dims'] for sd in cfg.surf.values())
    return ok, per, rel, singular_ratio(A), len(cfg.surf)


# ----------------------------------------------------------------------

def part_H_levels():
    """The decomposition into levels against the quadrature of item (LXXII)."""
    import numpy as np
    import fourfold_products as fp
    rng = random.Random(5)
    cfg = Config(0, 2, 5, 6, rng)
    sd = cfg.surface(1j, 0)
    worst = 0.0
    for c in (0, 1):
        bs = [sd['bund'][k][c] for k in ('S', 'Om', 'U', 'E', 'Phi')]
        fb = [fp.Bundle(b.d, *b.floats()) for b in bs]
        fo = fp.CurveOps(*fb, fp.Grid(64))
        for key in ('Cup', 'Dn', 'F0', 'F1'):
            X = fo.op(key)
            Y = sd['ops'][c][key]
            Ym = np.array([[[[complex(float(Y[s][o][u][w].real.mid()),
                                      float(Y[s][o][u][w].imag.mid()))
                              for w in range(len(Y[0][0][0]))]
                             for u in range(len(Y[0][0]))]
                            for o in range(len(Y[0]))]
                           for s in range(len(Y))])
            worst = max(worst, np.abs(X - Ym).max() / np.abs(X).max())
    check("(H) the levels of products by interpolation agree with the "
          "quadrature of item (LXXII) on both curves", worst < 1e-11,
          "relative difference %.1e" % worst)


def part_H():
    part_H_levels()
    ok, per, rel, (ratio, rad), nsurf = total((0, 2, 5, 6), 101)
    check("(H) the group relations of K hold exactly and the invariant "
          "sections have dimension |det|, on all %d surfaces" % nsurf, rel)
    check("(H) t = (2,5,6): rank 12 at each of the 16 pieces, certified",
          all(per) and len(per) == 16)
    check("(H) t = (2,5,6): rank 192 on the 192 classes of type (1,1,0), "
          "certified (Gram determinant a ball excluding 0)", ok,
          "smallest/largest singular value %.4f, ball radii below %.0e of "
          "the largest" % (ratio, rad))
    info = []
    ok, per, rel, (ratio, rad), _ = total((0, 2, 5, 6), 202, mc=True,
                                          info=info)
    kd = {x for x in info if len(x) == 2 and x[0] != 'zero products'}
    zp = all(x[1] for x in info if x[0] == 'zero products')
    check("(H) the kernels of x1 . and . x3 have dimensions 11 and 19 on "
          "every surface, certified, with x1 x2 = 0 = x2 x3 on them",
          kd == {(11, 19)} and zp)
    check("(H) with x1 x2^zeta = 0 = x2^zeta x3^zeta: rank 192, certified",
          ok and all(per), "smallest/largest singular value %.4f" % ratio)
    ok, per, rel, (ratio, rad), _ = total((0, 2, 5, 6), 303, sign=+1)
    check("(H) the relative sign of the two terms reversed: rank 192, "
          "certified", ok, "%.4f" % ratio)
    ok, per, rel, (ratio, rad), _ = total((0, 2, 5, 7), 404)
    check("(H) t = (2,5,7): rank 192, certified", ok and rel,
          "%.4f" % ratio)


def main():
    part_H()
    print()
    print("passed %d, failed %d" % (len(PASS), len(FAIL)))
    return 0 if not FAIL else 1


if __name__ == "__main__":
    sys.exit(main())
