#!/usr/bin/env python3
"""
hochschild_annihilator.py

The annihilator of a Weil class in the whole of Hochschild cohomology, and
the ring through which the action on any object carrying that class must
factor.  Item (XXXVIII).

For an abelian 2n-fold A of Weil type the Hochschild cohomology is the
exterior algebra on

    HH^1(A) = H^{0,1}(A) (+) H^0(T_A),

of dimension 4n, acting on H^*(A,C) = wedge^*(H^{1,0} (+) H^{0,1}) by wedging
with the (0,1) generators and contracting the (1,0) ones.  Since the wedging
and the contraction involve disjoint generators, the 4n operators pairwise
anticommute and HH^*(A) is the exterior algebra on them, of dimension 2^{4n}.

Write the Weil class as omega = a alpha_+ + b alpha_- with a b nonzero, and

    P = Ann_{HH^1}(alpha_+) = V_+^{0,1} (+) T_-,
    Q = Ann_{HH^1}(alpha_-) = V_-^{0,1} (+) T_+,

each of dimension 2n.  The script checks, for n = 1, 2, 3, in exact rational
arithmetic on the exterior algebra:

  (A) P and Q are exactly the annihilators of alpha_+ and of alpha_- in
      degree one, they are complementary in HH^1, and Ann_{HH^1}(omega) = 0.

  (B) Ann_{HH^2}(omega) = P ^ Q, of dimension 4n^2, which is the space of
      Setup "what injectivity forces" written as the mixed part of a splitting
      of HH^1; and in every degree k,

          dim Ann_{HH^k}(omega) = binom(4n,k) - 2 binom(2n,k),

      with one extra dimension at k = 2n and no other exception.  Equivalently
      Ann is the ideal generated by P ^ Q, except for that one class.

  (C) The ideal generated by P ^ Q is the sum of the summands wedge^i P (x)
      wedge^j Q with i, j >= 1; its codimension in HH^* is 2^{2n+1} - 1, so an
      object on which the evaluation map kills the degree-two annihilator has
      its whole Hochschild action factoring through a ring of that dimension.

  (D) Contraction with alpha_- is injective on wedge^* P and contraction with
      alpha_+ is injective on wedge^* Q, and the two images meet in exactly
      one line, in degree 2n.  Since sigma composed with the evaluation map is
      contraction with the Chern character, the evaluation map is injective on
      the quotient, so for every nonzero perfect complex with Chern character
      N omega,

          dim Ext^k(E,E) >= 2 binom(2n,k)   for 1 <= k < 2n,

      with no hypothesis on semiregularity at all; in degree two this reads
      dim Ext^2(E,E) >= 2n(2n-1).

Nothing here decides whether such a complex with injective semiregularity map
exists.  The script computes what one would have to look like.
"""

import itertools
import sys
from fractions import Fraction as Fr
from math import comb

PASS, FAIL = [], []


def check(name, ok, detail=""):
    tag = "PASS" if ok else "FAIL"
    (PASS if ok else FAIL).append(name)
    print("    [%s] %s" % (tag, name))
    if detail:
        for line in detail.split("\n"):
            print("           " + line)


# ------------------------------------------------- exterior algebra by masks
def bits(mask):
    out = []
    while mask:
        low = mask & -mask
        out.append(low.bit_length() - 1)
        mask ^= low
    return out


def wedge_sign(a, b):
    """sign of merging disjoint masks a and b"""
    s = 1
    x = b
    while x:
        low = x & -x
        i = low.bit_length() - 1
        if bin(a >> (i + 1)).count("1") % 2:
            s = -s
        x ^= low
    return s


def ext_mul(u, v):
    out = {}
    for a, ca in u.items():
        for b, cb in v.items():
            if a & b:
                continue
            s = wedge_sign(a, b)
            k = a | b
            out[k] = out.get(k, Fr(0)) + s * ca * cb
            if out[k] == 0:
                del out[k]
    return out


def wedge_gen(i, u):
    """e_i ^ u"""
    out = {}
    for a, c in u.items():
        if (a >> i) & 1:
            continue
        s = wedge_sign(1 << i, a)
        k = a | (1 << i)
        out[k] = out.get(k, Fr(0)) + s * c
        if out[k] == 0:
            del out[k]
    return out


def contract_gen(i, u):
    """iota_i u, the odd derivation dual to e_i"""
    out = {}
    for a, c in u.items():
        if not ((a >> i) & 1):
            continue
        below = bin(a & ((1 << i) - 1)).count("1")
        s = -1 if below % 2 else 1
        k = a ^ (1 << i)
        out[k] = out.get(k, Fr(0)) + s * c
        if out[k] == 0:
            del out[k]
    return out


def rank_q(rows):
    M = [list(r) for r in rows]
    if not M:
        return 0
    nr, nc = len(M), len(M[0])
    r = 0
    for c in range(nc):
        piv = None
        for i in range(r, nr):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][c]
        M[r] = [x / pv for x in M[r]]
        for i in range(nr):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [x - f * y for x, y in zip(M[i], M[r])]
        r += 1
        if r == nr:
            break
    return r


def run_n(n, a, b, kmax=None):
    """the whole computation for one n and one choice of (a, b); kmax limits
    the degrees in which the dimension of the annihilator is computed, the
    structural checks being made in every degree"""
    N = 4 * n
    # cohomology generators: x_0..x_{n-1} = 0..n-1,  y = n..2n-1,
    # bar x = 2n..3n-1,  bar y = 3n..4n-1
    XS = list(range(0, n))
    YS = list(range(n, 2 * n))
    BXS = list(range(2 * n, 3 * n))
    BYS = list(range(3 * n, 4 * n))

    def top(idx):
        u = {0: Fr(1)}
        for i in idx:
            u = wedge_gen(i, u)
        return u

    alpha_p = top(XS + BXS)
    alpha_m = top(YS + BYS)
    omega = dict(alpha_p)
    omega = {k: Fr(a) * v for k, v in alpha_p.items()}
    for k, v in alpha_m.items():
        omega[k] = omega.get(k, Fr(0)) + Fr(b) * v
        if omega[k] == 0:
            del omega[k]

    # the 4n operators of HH^1: wedge by a (0,1) generator, contract a (1,0)
    # generator.  op[t] = (kind, index)
    ops = ([("w", i) for i in BXS] + [("c", j) for j in YS]      # this is P
           + [("w", i) for i in BYS] + [("c", j) for j in XS])   # this is Q
    dimP = 2 * n
    assert len(ops) == N

    def apply_op(t, u):
        kind, i = ops[t]
        return wedge_gen(i, u) if kind == "w" else contract_gen(i, u)

    def apply_mono(mask, u):
        # apply the operators of the mask in decreasing order, so that the
        # monomial op_{i_1} ... op_{i_k} acts as the composite
        for t in sorted(bits(mask), reverse=True):
            u = apply_op(t, u)
            if not u:
                return {}
        return u

    # (A) P and Q as annihilators in degree one
    killP = all(not apply_mono(1 << t, alpha_p) for t in range(dimP))
    killQ = all(not apply_mono(1 << t, alpha_m) for t in range(dimP, N))
    nzP = all(apply_mono(1 << t, alpha_m) for t in range(dimP))
    nzQ = all(apply_mono(1 << t, alpha_p) for t in range(dimP, N))
    check("n=%d: P kills alpha_+ and nothing else, Q kills alpha_- and "
          "nothing else, so P = Ann(alpha_+) and Q = Ann(alpha_-) in degree "
          "one" % n, killP and killQ and nzP and nzQ)

    top = N if kmax is None else min(kmax, N)
    dims = {}
    for k in range(top + 1):
        rows = []
        masks = [m for m in range(1 << N) if bin(m).count("1") == k]
        cols = sorted({key for m in masks for key in apply_mono(m, omega)})
        pos = {c: t for t, c in enumerate(cols)}
        for m in masks:
            img = apply_mono(m, omega)
            row = [Fr(0)] * len(cols)
            for key, v in img.items():
                row[pos[key]] = v
            rows.append(row)
        dims[k] = len(masks) - rank_q(rows)

    check("n=%d: Ann(omega) is zero in degree one" % n, dims[1] == 0)
    if n >= 2:
        check("n=%d: dim Ann(omega) in degree two is 4n^2 = %d"
              % (n, 4 * n * n), dims[2] == 4 * n * n)
    else:
        check("n=1: degree two is the exceptional degree 2n, so the "
              "annihilator is 4n^2 + 1 = 5", dims[2] == 4 * n * n + 1)

    expected = {}
    for k in range(top + 1):
        e = comb(N, k) - 2 * comb(2 * n, k)
        if k == 2 * n:
            e += 1
        if k == 0:
            e = 0
        expected[k] = e
    check("n=%d: dim Ann(omega) = binom(4n,k) - 2 binom(2n,k) in every "
          "degree computed, with one extra class at k = 2n" % n,
          all(dims[k] == expected[k] for k in range(top + 1)),
          "degrees 0 to %d\ncomputed %s\nexpected %s"
          % (top, [dims[k] for k in range(top + 1)],
             [expected[k] for k in range(top + 1)]))

    # (B) the degree two annihilator is exactly P ^ Q
    PQ = [(1 << s) | (1 << t) for s in range(dimP) for t in range(dimP, N)]
    okPQ = all(not apply_mono(m, omega) for m in PQ)
    check("n=%d: every monomial of P ^ Q annihilates omega, and there are "
          "4n^2 = %d of them" % (n, 4 * n * n),
          okPQ and len(PQ) == 4 * n * n)

    # (C) the ideal generated by P ^ Q, and its codimension
    pmask = (1 << dimP) - 1
    qmask = ((1 << N) - 1) ^ pmask
    in_ideal = [m for m in range(1 << N)
                if (m & pmask) and (m & qmask)]
    codim = (1 << N) - len(in_ideal)
    check("n=%d: the ideal generated by P ^ Q is the set of monomials meeting "
          "both, of codimension 2^{2n+1} - 1 = %d in HH^* of dimension %d"
          % (n, 2 ** (2 * n + 1) - 1, 2 ** N),
          codim == 2 ** (2 * n + 1) - 1)
    # it is an ideal, and every element of it annihilates omega
    okid = all(not apply_mono(m, omega) for m in in_ideal)
    check("n=%d: every element of that ideal annihilates omega" % n, okid)

    # (D) contraction with alpha_- is injective on wedge^* P, with alpha_+ on
    # wedge^* Q, and the images meet in one line at k = 2n
    def inj_on(masks, target):
        cols = sorted({key for m in masks for key in apply_mono(m, target)})
        pos = {c: t for t, c in enumerate(cols)}
        rows = []
        for m in masks:
            img = apply_mono(m, target)
            row = [Fr(0)] * len(cols)
            for key, v in img.items():
                row[pos[key]] = v
            rows.append(row)
        return rank_q(rows) == len(masks), rows, cols

    Pmasks = [m for m in range(1 << N) if m and not (m & qmask)]
    Qmasks = [m for m in range(1 << N) if m and not (m & pmask)]
    okP, rowsP, colsP = inj_on(Pmasks, alpha_m)
    okQ, rowsQ, colsQ = inj_on(Qmasks, alpha_p)
    check("n=%d: contraction with alpha_- is injective on the nonconstant "
          "part of wedge^* P, and with alpha_+ on that of wedge^* Q" % n,
          okP and okQ)

    meets = 0
    for k in range(1, (N if kmax is None else min(kmax, N)) + 1):
        Pk = [m for m in Pmasks if bin(m).count("1") == k]
        Qk = [m for m in Qmasks if bin(m).count("1") == k]
        if not Pk or not Qk:
            continue
        cols = sorted({key for m in Pk + Qk
                       for key in (apply_mono(m, alpha_m) if m in set(Pk)
                                   else apply_mono(m, alpha_p))})
        pos = {c: t for t, c in enumerate(cols)}
        rows = []
        for m in Pk:
            img = apply_mono(m, alpha_m)
            row = [Fr(0)] * len(cols)
            for key, v in img.items():
                row[pos[key]] = v
            rows.append(row)
        rP = rank_q(rows)
        rows2 = []
        for m in Qk:
            img = apply_mono(m, alpha_p)
            row = [Fr(0)] * len(cols)
            for key, v in img.items():
                row[pos[key]] = v
            rows2.append(row)
        rQ = rank_q(rows2)
        rboth = rank_q(rows + rows2)
        inter = rP + rQ - rboth
        if inter:
            meets += inter
            if k != 2 * n or inter != 1:
                check("n=%d: an unexpected meeting in degree %d" % (n, k),
                      False, "intersection of dimension %d" % inter)
    if kmax is None or kmax >= 2 * n:
        check("n=%d: the two images meet in exactly one line, and it sits in "
              "degree 2n = %d" % (n, 2 * n), meets == 1)
    else:
        check("n=%d: the two images meet in no degree up to %d"
              % (n, kmax), meets == 0)

    # the unconditional lower bound in degree two
    if n >= 2:
        lower = 2 * comb(2 * n, 2)
        check("n=%d: dim HH^2 - dim Ann = 2 binom(2n,2) = %d, so any nonzero "
              "perfect complex with this Chern character has dim Ext^2 at "
              "least that" % (n, lower),
              comb(N, 2) - dims[2] == lower,
              "dim HH^2 = %d, dim Ann = %d, quotient = %d = 2n(2n-1)"
              % (comb(N, 2), dims[2], lower))


def main():
    for n, a, b, kmax in ((1, 1, 1, None), (2, 1, 1, None), (2, 3, -5, None),
                          (3, 1, 2, 3)):
        print("  n = %d, omega = %d alpha_+ + %d alpha_-%s"
              % (n, a, b, "" if kmax is None else
                 "  (dimensions to degree %d)" % kmax))
        run_n(n, a, b, kmax)
    print("  hochschild_annihilator: %d passed, %d failed"
          % (len(PASS), len(FAIL)))
    return 0 if not FAIL else 1


if __name__ == "__main__":
    sys.exit(main())
