#!/usr/bin/env python3
"""
lefschetz_closure.py

Item (XLVI) of COMPUTATIONS.md: the finite computations behind the
theorem that objects generated by line bundles have Lefschetz Chern
characters on the square of a Mumford fourfold, at every point of the curve,
and that the exceptional classes are not Lefschetz classes.

Model.  As in items (XLIII) to (XLV): V = V_1 (x) V_2 (x) V_3, V_i = C^2,
basis indexed by (a,b,c) in {0,1}^3 with weight (1-2a, 1-2b, 1-2c) for the
maximal torus of G = SL_2^3; psi = eps (x) eps (x) eps; H^1(X x X) = V (+) V,
bits 0..7 and 8..15.  The symplectic Lie algebra sp(V, psi) is spanned by the
36 maps x -> psi(u,x) v + psi(v,x) u for basis vectors u, v.  psi pairs the
basis vector i with i xor 7, so the diagonal matrices in Sp(V, psi) form a
maximal torus T_Sp of rank four through the torus of G: the vector i has
T_Sp-weight +e_j for i = j < 4 and -e_j for i = 7 - j.

At a point of the Mumford curve that is not a CM point the Lefschetz group
of X (the centraliser of End^0(X) = Q in Sp) is Sp(V, psi); at a CM point
End^0(X) (x) C is the algebra of diagonal matrices in the weight basis
(the eight weights of the Hodge torus are distinct) and the Lefschetz group
is T_Sp.  Everything below is exact over Q or a rank modulo the prime
p = 1000003 of integer vectors; a rank modulo p bounds the rank over Q from
below, and a kernel modulo p bounds the kernel over Q from above, and every
conclusion below is drawn from a lower bound meeting an upper bound.

What is checked:

  (a) the 36 maps lie in sp(V, psi) and the Lie algebra of G lies in it;

  (b) the Sp(V, psi)-invariants of wedge^k(V (+) V), k even, have dimension
      at most 1,3,6,10,15,10,6,3,1 (weight-zero vectors killed by the 32
      root vectors, modulo p), and products of the three invariant divisor
      classes span spaces of exactly these dimensions: at a point that is
      not CM the Lefschetz invariants are the subring generated by divisor
      classes, in every degree;

  (c) the G-invariants (the Hodge classes at such a point) have dimensions
      1,3,8,16,28,16,8,3,1, so the classes that are Hodge but not
      Lefschetz number 0,0,2,6,13,6,2,0,0 by degree, 29 in all;

  (d) at a CM point the T_Sp-invariant monomials number
      1,16,100,304,454,304,100,16,1, the coefficients of (1+4y+y^2)^4,
      each is a product of the 16 divisor classes (a weight-zero set of
      weights +-e_j is a union of opposite pairs), and those products span
      spaces of these dimensions; the Hodge classes number
      1,16,132,432,648,432,132,16,1;

  (e) pi_0 and pi_12 + pi_13 + pi_23 are Sp(V, psi)-invariant, pi_12 is not,
      and omega_a is T_Sp-invariant exactly when a_1 = a_2 = a_3: the
      components of pi_12, pi_13, pi_23 of nonzero T_Sp-weight form a matrix
      of rank two whose kernel is spanned by (1,1,1), exactly over Q;

  (f) the sp(V, psi)-module generated by pi_12 - pi_13, and the one generated
      by pi_13 - pi_23, have dimension 308 and highest weight (2,2,0,0);
      Weyl's formula for Sp_8 gives dimension 308 to the highest weight
      2 w_2 = (2,2,0,0), and 1 + 27 + 42 + 308 = 378 = dim Sym^2 of the
      primitive part of wedge^2 V;

  (g) that module meets the span of the four pi in the plane of the
      classes with a_0 = 0 and a_1 + a_2 + a_3 = 0, the exceptional plane.

Run:  python3 lefschetz_closure.py
"""
from fractions import Fraction
from itertools import combinations
import os
import sys

import sympy

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mumford_rigidity as MR  # noqa: E402

PASS, FAIL = [], []
P = 1000003
NB = 16


def check(name, ok, detail=""):
    (PASS if ok else FAIL).append(name)
    print(("  [PASS] " if ok else "  [FAIL] ") + name +
          (("   " + detail) if detail else ""))


def popcount(m):
    return bin(m).count("1")


def mono_sign(a, b):
    if a & b:
        return 0
    s, bb = 0, b
    while bb:
        j = (bb & -bb).bit_length() - 1
        s += popcount(a >> (j + 1))
        bb &= bb - 1
    return -1 if s % 2 else 1


def wedge(x, y, mod=None):
    out = {}
    for a, ca in x.items():
        for b, cb in y.items():
            s = mono_sign(a, b)
            if s:
                v = out.get(a | b, 0) + s * ca * cb
                out[a | b] = v % mod if mod else v
    return {k: v for k, v in out.items() if v}


def eps(a, b):
    return 1 if (a, b) == (0, 1) else (-1 if (a, b) == (1, 0) else 0)


def psi8(a, b):
    v = 1
    for bit in (2, 1, 0):
        v *= eps((a >> bit) & 1, (b >> bit) & 1)
    return v


def gwt(i):
    j = i % 8
    return (1 - 2 * ((j >> 2) & 1), 1 - 2 * ((j >> 1) & 1), 1 - 2 * (j & 1))


def swt(i):
    j = i % 8
    w = [0, 0, 0, 0]
    w[min(j, j ^ 7)] = 1 if j < 4 else -1
    return tuple(w)


def mweight(m, f, n):
    w = [0] * n
    for i in range(NB):
        if m >> i & 1:
            for t, x in enumerate(f(i)):
                w[t] += x
    return tuple(w)


def sp_gen(u, v):
    M = [[0] * 8 for _ in range(8)]
    for c in range(8):
        M[v][c] += psi8(u, c)
        M[u][c] += psi8(v, c)
    return M


def sl2_gen(t, kind):
    M = [[0] * 8 for _ in range(8)]
    bit = 2 - t
    for i in range(8):
        if kind == "E" and (i >> bit) & 1:
            M[i - (1 << bit)][i] = 1
        if kind == "F" and not (i >> bit) & 1:
            M[i + (1 << bit)][i] = 1
        if kind == "H":
            M[i][i] = gwt(i)[t]
    return M


def in_sp(M):
    for i in range(8):
        for j in range(8):
            s = sum(M[r][i] * psi8(r, j) for r in range(8)) + \
                sum(psi8(i, r) * M[r][j] for r in range(8))
            if s:
                return False
    return True


def act(M, x, mod=None):
    """the derivation induced by the 8 x 8 matrix M, acting diagonally on
    V (+) V, applied to an element of the exterior algebra"""
    out = {}
    for m, c in x.items():
        bits = [i for i in range(NB) if m >> i & 1]
        for k, i in enumerate(bits):
            left = sum(1 << b for b in bits[:k])
            right = sum(1 << b for b in bits[k + 1:])
            off = 8 if i >= 8 else 0
            for r8 in range(8):
                a = M[r8][i - off]
                if a == 0:
                    continue
                r = r8 + off
                if (left | right) >> r & 1:
                    continue
                s = mono_sign(left, 1 << r) * mono_sign(left | (1 << r), right)
                new = left | (1 << r) | right
                v = out.get(new, 0) + s * a * c
                out[new] = v % mod if mod else v
    return {k: v for k, v in out.items() if v}


class ModSpan:
    """a growing echelon basis modulo P"""

    def __init__(self):
        self.piv = {}

    def add(self, v):
        v = {k: c % P for k, c in v.items() if c % P}
        while v:
            p = max(v)
            if p in self.piv:
                b = self.piv[p]
                f = v[p] * pow(b[p], P - 2, P) % P
                for k, c in b.items():
                    nv = (v.get(k, 0) - f * c) % P
                    if nv:
                        v[k] = nv
                    else:
                        v.pop(k, None)
            else:
                self.piv[p] = v
                return True
        return False

    def __len__(self):
        return len(self.piv)


def masks(k):
    return [sum(1 << i for i in c) for c in combinations(range(NB), k)]


def kernel_upper(k, gens, wf, n):
    """weight-zero monomials of degree k, and an upper bound (modulo p) for
    the dimension of the vectors among them killed by every map in gens"""
    zero = (0,) * n
    W0 = [m for m in masks(k) if mweight(m, wf, n) == zero]
    S = ModSpan()
    for m in W0:
        img = {}
        for g, M in enumerate(gens):
            for mm, c in act(M, {m: 1}, P).items():
                img[g * (1 << 16) + mm] = c
        S.add(img)
    return W0, len(W0) - len(S)


def weyl_c4(lam):
    rho = [4, 3, 2, 1]
    l = [lam[i] + rho[i] for i in range(4)]
    num, den = Fraction(1), Fraction(1)
    for i in range(4):
        for j in range(i + 1, 4):
            num *= (l[i] - l[j]) * (l[i] + l[j])
            den *= (rho[i] - rho[j]) * (rho[i] + rho[j])
        num *= l[i]
        den *= rho[i]
    return num / den


def tomod(x):
    out = {}
    for k, v in x.items():
        v = sympy.Rational(v)
        out[k] = int(v.p) * pow(int(v.q), P - 2, P) % P
    return {k: v for k, v in out.items() if v}


def run():
    SP = [sp_gen(u, v) for u in range(8) for v in range(u, 8)]
    roots = [sp_gen(u, v) for u in range(8) for v in range(u, 8)
             if any(a + b for a, b in zip(swt(u), swt(v)))]
    GL = [sl2_gen(t, k) for t in range(3) for k in "EFH"]
    groots = [sl2_gen(t, k) for t in range(3) for k in "EF"]

    # (a)
    check("the 36 maps lie in sp(V, psi), there are 32 root vectors, and "
          "the Lie algebra of G lies in sp(V, psi)",
          all(in_sp(M) for M in SP) and len(roots) == 32
          and all(in_sp(M) for M in GL))

    # (b)
    sp_up, g_dim, tsp, tc = [], [], [], []
    for k in range(0, 17, 2):
        _, d = kernel_upper(k, roots, swt, 4)
        sp_up.append(d)
        W0g, dg = kernel_upper(k, groots, gwt, 3)
        g_dim.append(dg)
        tc.append(len(W0g))
        tsp.append(len([m for m in masks(k)
                        if mweight(m, swt, 4) == (0, 0, 0, 0)]))
    W2 = [m for m in masks(2) if mweight(m, swt, 4) == (0, 0, 0, 0)]
    rows = {}
    for j, m in enumerate(W2):
        for g, M in enumerate(roots):
            for mm, c in act(M, {m: 1}).items():
                rows.setdefault((g, mm), {})[j] = c
    A = sympy.Matrix([[r.get(j, 0) for j in range(len(W2))]
                      for r in rows.values()])
    I2 = []
    for v in A.nullspace():
        v = v * sympy.ilcm(*[x.q for x in v])
        I2.append({W2[j]: int(v[j]) for j in range(len(W2)) if v[j] != 0})
    exact_inv = len(I2) == 3 and all(not act(M, x) for M in SP for x in I2)
    span = {0: [{0: 1}]}
    lower = [1]
    for k in range(2, 17, 2):
        S = ModSpan()
        basis = []
        for a in span[k - 2]:
            for g in I2:
                v = wedge(a, g, P)
                if S.add(v):
                    basis.append(v)
        span[k] = basis
        lower.append(len(basis))
    target = [1, 3, 6, 10, 15, 10, 6, 3, 1]
    check("the Sp(V, psi)-invariants of wedge^k(V+V) have dimension "
          "1,3,6,10,15,10,6,3,1, and the products of the three invariant "
          "divisor classes span them",
          exact_inv and sp_up == target and lower == target,
          "upper %s, lower %s" % (sp_up, lower))

    # (c)  exact count by weight multiplicities: the multiplicity of the
    # trivial representation of sl_2^3 is the alternating sum of the weight
    # multiplicities at (2e_0, 2e_1, 2e_2), e in {0,1}^3
    char = []
    for k in range(0, 17, 2):
        cnt = {}
        for m in masks(k):
            w = mweight(m, gwt, 3)
            cnt[w] = cnt.get(w, 0) + 1
        tot = 0
        for e in range(8):
            e0, e1, e2 = (e >> 2) & 1, (e >> 1) & 1, e & 1
            tot += (-1) ** (e0 + e1 + e2) * cnt.get((2 * e0, 2 * e1, 2 * e2),
                                                     0)
        char.append(tot)
    gt = [1, 3, 8, 16, 28, 16, 8, 3, 1]
    exc = [g - s for g, s in zip(char, sp_up)]
    check("the G-invariants have dimension 1,3,8,16,28,16,8,3,1 (by weight "
          "multiplicities, and as the kernel modulo p), so the Hodge classes "
          "that are not Lefschetz number 0,0,2,6,13,6,2,0,0, 29 in all",
          char == gt and g_dim == gt
          and exc == [0, 0, 2, 6, 13, 6, 2, 0, 0] and sum(exc) == 29,
          "computed %s" % char)

    # (d)
    poly = [1]
    for _ in range(4):
        new = [0] * (len(poly) + 2)
        for i, c in enumerate(poly):
            new[i] += c
            new[i + 1] += 4 * c
            new[i + 2] += c
        poly = new
    pairs_ok = True
    for k in range(0, 17, 2):
        for m in masks(k):
            if mweight(m, swt, 4) != (0, 0, 0, 0):
                continue
            ws = [swt(i) for i in range(NB) if m >> i & 1]
            for j in range(4):
                plus = sum(1 for w in ws if w[j] == 1)
                minus = sum(1 for w in ws if w[j] == -1)
                if plus != minus:
                    pairs_ok = False
    D2 = [{m: 1} for m in W2]
    spanc = {0: [{0: 1}]}
    lowc = [1]
    for k in range(2, 17, 2):
        S = ModSpan()
        basis = []
        for a in spanc[k - 2]:
            for g in D2:
                v = wedge(a, g, P)
                if v and S.add(v):
                    basis.append(v)
        spanc[k] = basis
        lowc.append(len(basis))
    check("at a CM point the T_Sp-invariant monomials number "
          "1,16,100,304,454,304,100,16,1 = coefficients of (1+4y+y^2)^4, "
          "each a product of the 16 divisor classes, which span exactly them",
          tsp == poly == lowc == [1, 16, 100, 304, 454, 304, 100, 16, 1]
          and len(W2) == 16 and pairs_ok, "Hodge classes %s" % tc)
    check("at a CM point the Hodge classes number "
          "1,16,132,432,648,432,132,16,1",
          tc == [1, 16, 132, 432, 648, 432, 132, 16, 1])

    # (e)
    pieces, PI, _ = MR.build_tensors()
    PIm = {k: tomod(v) for k, v in PI.items()}
    tot = {}
    for key in ("12", "13", "23"):
        for m, c in PIm[key].items():
            tot[m] = (tot.get(m, 0) + c) % P
    tot = {k: v for k, v in tot.items() if v}
    inv0 = all(not act(M, PIm["0"], P) for M in SP)
    invs = all(not act(M, tot, P) for M in SP)
    inv12 = all(not act(M, PIm["12"], P) for M in SP)
    comps = {}
    for key in ("12", "13", "23"):
        for m, c in PI[key].items():
            if any(mweight(m, swt, 4)):
                comps.setdefault(m, {})[key] = sympy.Rational(c)
    Mq = sympy.Matrix([[comps[m].get(k, 0) for k in ("12", "13", "23")]
                       for m in comps])
    ker = Mq.nullspace()
    ker_ok = (Mq.rank() == 2 and len(ker) == 1
              and ker[0] / ker[0][0] == sympy.Matrix([1, 1, 1]))
    check("pi_0 and pi_12 + pi_13 + pi_23 are Sp-invariant and pi_12 is "
          "not; omega_a is T_Sp-invariant exactly when a1 = a2 = a3",
          inv0 and invs and not inv12 and ker_ok,
          "%d monomials of nonzero T_Sp-weight, exact rank %d"
          % (len(comps), Mq.rank()))

    # (f), (g)
    dims, tops, planes = [], [], []
    piv = {k: PIm[k] for k in ("0", "12", "13", "23")}
    for a, b in (("12", "13"), ("13", "23")):
        vec = {m: (PIm[a].get(m, 0) - PIm[b].get(m, 0)) % P
               for m in set(PIm[a]) | set(PIm[b])}
        vec = {k: v for k, v in vec.items() if v}
        S = ModSpan()
        S.add(vec)
        allv, frontier = [vec], [vec]
        while frontier:
            new = []
            for x in frontier:
                for M in SP:
                    y = act(M, x, P)
                    if y and S.add(dict(y)):
                        new.append(y)
                        allv.append(y)
            frontier = new
        dims.append(len(S))
        wts = set()
        for x in allv:
            for m in x:
                wts.add(mweight(m, swt, 4))
        tops.append(max(wts))
        # dim(module meet span of the pi) = 4 - (pi independent modulo it)
        big = ModSpan()
        big.piv = dict(S.piv)
        added = sum(1 for key in ("0", "12", "13", "23")
                    if big.add(piv[key]))
        planes.append(4 - added)
    wd = [weyl_c4(l) for l in ((0, 0, 0, 0), (1, 1, 0, 0), (1, 1, 1, 1),
                               (2, 2, 0, 0))]
    check("the module generated by pi_12 - pi_13, and the one generated by "
          "pi_13 - pi_23, has dimension 308 and highest weight (2,2,0,0)",
          dims == [308, 308] and tops == [(2, 2, 0, 0), (2, 2, 0, 0)],
          "dimensions %s" % dims)
    check("Weyl's formula for Sp_8: dimensions 1, 27, 42, 308 for 0, w_2, "
          "w_4, 2w_2, and 1 + 27 + 42 + 308 = 378 = 27*28/2",
          wd == [1, 27, 42, 308] and sum(wd) == 378 == 27 * 28 // 2)
    check("that module meets the span of the four pi in a plane: the "
          "exceptional plane", planes == [2, 2], "computed %s" % planes)


if __name__ == "__main__":
    print("(XLVI) what line bundles generate on the square of a Mumford "
          "fourfold")
    run()
    print()
    print("  %d checks passed, %d failed" % (len(PASS), len(FAIL)))
    raise SystemExit(0 if not FAIL else 1)
