#!/usr/bin/env python3
"""
split_locus.py

Is the Weil class algebraic on the split member of the family?

The family of section 14 puts a (K,-1,n)-Weil structure on A = X x Xhat for
every abelian n-fold X, every squarefree d and every nondegenerate
beta in NS(X)_Q.  On that A three classes are algebraic for free:

    beta      the polarisation of X, pulled back,
    betahat   the dual polarisation of Xhat, pulled back,
    ell       the class of the Poincare bundle on X x Xhat.

This script decides, by exact rational linear algebra, whether the two
generators omega_1, omega_2 of the Weil line lie in the subring of
H^*(A,Q) generated by those three classes.  If they do, the Weil classes are
algebraic at every point of the split locus, with an explicit expression as a
polynomial in divisor classes, and the residual problem is exactly the
propagation off that locus.

Set-up.  U = H^1(X,Q) with basis x_1..x_{2n}; U^dual = H^1(Xhat,Q) with dual
basis xi_1..xi_{2n}; H^1(A,Q) = U + U^dual, of dimension 4n.  With
beta = sum_{j<=n} x_j ^ x_{n+j} the map B : U -> U^dual sends
x_j -> xi_{n+j} and x_{n+j} -> -xi_j.  The endomorphism M of section 14 acts
on H^1(A) by  u -> -B u  on U and  phi -> d B^{-1} phi  on U^dual, so
M^2 = -d, and its eigenvectors for +- delta are

    u  +-  (delta/d) B u,      u in U tensor C.

Hence omega_+ = wedge_i ( x_i + (delta/d) B x_i ) and omega_- is its
conjugate, and the two rational generators are omega_+ + omega_- and
(omega_+ - omega_-)/delta, cleared of denominators.
"""

from fractions import Fraction as F
from itertools import combinations


# ------------------------------------------------- scalars in Q(sqrt(-d))

def sc(a=0, b=0):
    return (F(a), F(b))


def add(p, q):
    return (p[0] + q[0], p[1] + q[1])


def mul(p, q, d):
    return (p[0] * q[0] - d * p[1] * q[1], p[0] * q[1] + p[1] * q[0])


def iszero(p):
    return p[0] == 0 and p[1] == 0


def smul(c, p):
    return (c * p[0], c * p[1])


# ------------------------------------------------------ exterior algebra
# basis of H^1(A) is indexed 0..4n-1:  0..2n-1 are x_1..x_{2n},
# 2n..4n-1 are xi_1..xi_{2n}.  An element is {sorted tuple: scalar}.

def wedge(u, v, d):
    out = {}
    for su, cu in u.items():
        setu = set(su)
        for sv, cv in v.items():
            if setu & set(sv):
                continue
            arr = list(su) + list(sv)
            sign = 1
            for i in range(len(arr)):
                for j in range(i + 1, len(arr)):
                    if arr[i] > arr[j]:
                        sign = -sign
            key = tuple(sorted(arr))
            out[key] = add(out.get(key, sc()), smul(F(sign), mul(cu, cv, d)))
    return {k: v for k, v in out.items() if not iszero(v)}


def eadd(u, v):
    out = dict(u)
    for k, c in v.items():
        out[k] = add(out.get(k, sc()), c)
    return {k: v for k, v in out.items() if not iszero(v)}


def escale(c, u):
    return {k: smul(c, v) for k, v in u.items() if not iszero(smul(c, v))}


def epow(u, k, d):
    r = {(): sc(1)}
    for _ in range(k):
        r = wedge(r, u, d)
    return r


# ---------------------------------------------------------------- model

class Split:
    def __init__(self, n, d):
        self.n, self.d = n, d
        self.m = 2 * n              # dim U
        self.N = 4 * n              # dim H^1(A)

    def x(self, i):                  # i = 1..2n
        return i - 1

    def xi(self, i):                 # i = 1..2n
        return self.m + i - 1

    def Bx(self, i):
        """B(x_i) as a degree one element."""
        n = self.n
        if i <= n:
            return {(self.xi(n + i),): sc(1)}
        return {(self.xi(i - n),): sc(-1)}

    def beta(self):
        n = self.n
        out = {}
        for j in range(1, n + 1):
            out[tuple(sorted((self.x(j), self.x(n + j))))] = sc(1)
        return out

    def betahat(self):
        n = self.n
        out = {}
        for j in range(1, n + 1):
            out[tuple(sorted((self.xi(j), self.xi(n + j))))] = sc(1)
        return out

    def ell(self):
        out = {}
        for i in range(1, self.m + 1):
            out[tuple(sorted((self.x(i), self.xi(i))))] = sc(1)
        return out

    def omega(self, s):
        """omega_s = wedge_i ( x_i + s (delta/d) B x_i )."""
        d = self.d
        r = {(): sc(1)}
        for i in range(1, self.m + 1):
            term = {(self.x(i),): sc(1)}
            coef = (F(0), F(s, d))          # s * delta / d
            for k, c in self.Bx(i).items():
                term = eadd(term, {k: mul(coef, c, d)})
            r = wedge(r, term, d)
        return r

    def generators(self):
        return self.omega(+1), self.omega(-1)


def rational_pair(sp):
    """The two rational generators of the Weil line, cleared of denominators."""
    d, n = sp.d, sp.n
    op, om = sp.generators()
    w1 = eadd(op, om)
    diff = eadd(op, escale(F(-1), om))
    inv = (F(0), F(-1, d))                   # 1/delta = -delta/d
    w2 = {k: mul(inv, c, d) for k, c in diff.items()}
    w2 = {k: v for k, v in w2.items() if not iszero(v)}
    for w in (w1, w2):
        for c in w.values():
            assert c[1] == 0, "not rational"
    lam = F(d) ** n
    w1 = {k: (lam * c[0], F(0)) for k, c in w1.items()}
    w2 = {k: (lam * c[0], F(0)) for k, c in w2.items()}
    return w1, w2


# ---------------------------------------------------- linear algebra over Q

def solve(basis, target, dim_keys):
    """Is `target` in the Q-span of `basis`?  Returns the coefficients or
    None.  Everything is rational; the second component is zero throughout."""
    keys = sorted(dim_keys)
    idx = {k: i for i, k in enumerate(keys)}
    rows = len(keys)
    cols = len(basis)
    M = [[F(0)] * (cols + 1) for _ in range(rows)]
    for j, b in enumerate(basis):
        for k, c in b.items():
            M[idx[k]][j] = c[0]
    for k, c in target.items():
        M[idx[k]][cols] = c[0]
    # gaussian elimination
    piv_rows = []
    r = 0
    for c in range(cols):
        p = None
        for i in range(r, rows):
            if M[i][c] != 0:
                p = i
                break
        if p is None:
            continue
        M[r], M[p] = M[p], M[r]
        pv = M[r][c]
        M[r] = [a / pv for a in M[r]]
        for i in range(rows):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        piv_rows.append((r, c))
        r += 1
    # inconsistency?
    for i in range(r, rows):
        if M[i][cols] != 0:
            return None
    coeff = [F(0)] * cols
    for (ri, ci) in piv_rows:
        coeff[ci] = M[ri][cols]
    return coeff


def monomials(sp, gens, degree):
    """All products of the generators of total cohomological degree `degree`,
    each generator having degree two."""
    d = sp.d
    k = degree // 2
    out, names = [], []
    for expo in combinations(range(k + len(gens) - 1), len(gens) - 1):
        # compositions of k into len(gens) parts
        cuts = [-1] + list(expo) + [k + len(gens) - 1]
        parts = [cuts[i + 1] - cuts[i] - 1 for i in range(len(gens))]
        prod = {(): sc(1)}
        for g, e in zip(gens, parts):
            if e:
                prod = wedge(prod, epow(g[1], e, d), d)
            if not prod:
                break
        if prod:
            out.append(prod)
            names.append(" ".join("%s^%d" % (g[0], e)
                                  for g, e in zip(gens, parts) if e))
    return out, names


def run(n, d, verbose=True):
    sp = Split(n, d)
    w1, w2 = rational_pair(sp)
    gens = [("beta", sp.beta()), ("betahat", sp.betahat()), ("ell", sp.ell())]
    mons, names = monomials(sp, gens, 2 * n)
    allkeys = set()
    for m in mons:
        allkeys |= set(m)
    allkeys |= set(w1) | set(w2)

    res = []
    for label, w in (("omega_1", w1), ("omega_2", w2)):
        coeff = solve(mons, w, allkeys)
        res.append((label, coeff))
        if verbose:
            if coeff is None:
                print("    [----] %s is NOT in the span of the %d monomials"
                      % (label, len(mons)))
            else:
                terms = " + ".join("(%s) %s" % (c, nm)
                                   for c, nm in zip(coeff, names) if c != 0)
                print("    [DONE] %s = %s" % (label, terms if terms else "0"))
    return res


def closed_form(n, d):
    """Check omega_- = eps/(n! d^n) * (gamma + delta ell)^n with
    gamma = d beta - betahat and eps = (-1)^(n(n-1)/2), and the conjugate
    statement for omega_+ with gamma - delta ell."""
    sp = Split(n, d)
    op, om = sp.generators()
    beta, bh, ell = sp.beta(), sp.betahat(), sp.ell()
    gamma = eadd(escale(F(d), beta), escale(F(-1), bh))
    import math
    eps = F((-1) ** (n * (n - 1) // 2))
    lam = eps / (F(math.factorial(n)) * F(d) ** n)
    ok = True
    for s, target in ((+1, op), (-1, om)):
        # theta = gamma - s*delta*ell
        theta = dict(gamma)
        for k, c in ell.items():
            theta[k] = add(theta.get(k, sc()), (F(0), F(-s)))
        theta = {k: v for k, v in theta.items() if not iszero(v)}
        got = escale(lam, epow(theta, n, d))
        keys = set(got) | set(target)
        for k in keys:
            if not iszero(add(got.get(k, sc()),
                              smul(F(-1), target.get(k, sc())))):
                ok = False
    return ok


def example_check(n, d):
    """The displayed formulas of ex:splitsmall are the integral generators
    omega_1, omega_2 of eq:omegagens for the K-basis x_1, ..., x_{2n}, on
    which sqrt(-d) acts by x -> -B x (so y_j = -B x_j):
    n = 2: omega_1 = (d ell^2 - gamma^2)/2, omega_2 = -gamma ell;
    n = 3: omega_1 = d gamma ell^2/2 - gamma^3/6,
           omega_2 = d ell^3/6 - gamma^2 ell/2."""
    from itertools import combinations
    sp = Split(n, d)
    beta, bh, ell = sp.beta(), sp.betahat(), sp.ell()
    gamma = eadd(escale(F(d), beta), escale(F(-1), bh))
    if n == 2:
        cands = [eadd(escale(F(d, 2), epow(ell, 2, d)),
                      escale(F(-1, 2), epow(gamma, 2, d))),
                 escale(F(-1), wedge(gamma, ell, d))]
    else:
        cands = [eadd(escale(F(d, 2), wedge(gamma, epow(ell, 2, d), d)),
                      escale(F(-1, 6), epow(gamma, 3, d))),
                 eadd(escale(F(d, 6), epow(ell, 3, d)),
                      escale(F(-1, 2), wedge(epow(gamma, 2, d), ell, d)))]
    xs = [{(sp.x(j),): sc(1)} for j in range(1, 2 * n + 1)]
    ys = [escale(F(-1), sp.Bx(j)) for j in range(1, 2 * n + 1)]
    w1, w2 = {}, {}
    for k in range(2 * n + 1):
        for T in combinations(range(2 * n), k):
            m = {(): sc(1)}
            for j in range(2 * n):
                m = wedge(m, ys[j] if j in T else xs[j], d)
            if k % 2 == 0:
                w1 = eadd(w1, escale(F((-1) ** (k // 2) * d ** (n - k // 2)), m))
            else:
                w2 = eadd(w2, escale(F((-1) ** ((k - 1) // 2)
                                       * d ** (n - (k + 1) // 2)), m))
    return (eadd(cands[0], escale(F(-1), w1)) == {}
            and eadd(cands[1], escale(F(-1), w2)) == {})


def divisor_check_closed(n, d):
    """gamma +- delta ell lies in wedge^2 V_-+ : verify by checking that
    iota(sqrt(-d))^* multiplies it by -d, which is tau^2 at tau = sqrt(-d)."""
    sp = Split(n, d)
    beta, bh, ell = sp.beta(), sp.betahat(), sp.ell()
    gamma = eadd(escale(F(d), beta), escale(F(-1), bh))
    # M^* on degree one: x_i -> -B x_i,  xi_i -> d B^{-1} xi_i
    img = {}
    for i in range(1, sp.m + 1):
        img[sp.x(i)] = escale(F(-1), sp.Bx(i))
    n_ = sp.n
    for j in range(1, n_ + 1):
        img[sp.xi(j)] = {(sp.x(n_ + j),): sc(-d)}
        img[sp.xi(n_ + j)] = {(sp.x(j),): sc(d)}

    def applyM(u):
        out = {}
        for k, c in u.items():
            piece = {(): sc(1)}
            for idx in k:
                piece = wedge(piece, img[idx], d)
            piece = {kk: mul(c, cc, d) for kk, cc in piece.items()}
            out = eadd(out, piece)
        return out

    ok = True
    for s in (+1, -1):
        theta = dict(gamma)
        for k, c in ell.items():
            theta[k] = add(theta.get(k, sc()), (F(0), F(-s)))
        theta = {k: v for k, v in theta.items() if not iszero(v)}
        lhs = applyM(theta)
        rhs = escale(F(-d), theta)
        keys = set(lhs) | set(rhs)
        for k in keys:
            if not iszero(add(lhs.get(k, sc()),
                              smul(F(-1), rhs.get(k, sc())))):
                ok = False
    return ok


if __name__ == "__main__":
    print("the Weil class on the split member A = X x Xhat")
    npass = nfail = 0
    for (n, d) in [(1, 1), (1, 2), (2, 1), (2, 2), (2, 3), (2, 7),
                   (3, 1), (3, 2)]:
        print("  n=%d, d=%d   (dim A = %d, dim H^1 = %d)"
              % (n, d, 2 * n, 4 * n))
        out = run(n, d)
        got = all(c is not None for _, c in out)
        tag = "PASS" if got else "FAIL"
        print("    [%s] both generators lie in the divisor subring" % tag)
        npass += 1 if got else 0
        nfail += 0 if got else 1
    print("  the closed form  omega_-+ = eps/(n! d^n) (gamma -+ delta ell)^n")
    for (n, d) in [(1, 1), (2, 1), (2, 3), (3, 1), (3, 2), (3, 5),
                   (4, 1), (4, 3), (5, 1), (5, 2)]:
        ok1 = closed_form(n, d)
        ok2 = divisor_check_closed(n, d)
        print("    [%s] n=%d, d=%d: gamma -+ delta ell is a tau^2 eigenclass"
              % ("PASS" if ok2 else "FAIL", n, d))
        print("    [%s] n=%d, d=%d: omega_-+ equals the closed form"
              % ("PASS" if ok1 else "FAIL", n, d))
        npass += (1 if ok1 else 0) + (1 if ok2 else 0)
        nfail += (0 if ok1 else 1) + (0 if ok2 else 1)

    print("  the displayed formulas of ex:splitsmall at n = 2, 3")
    for (n, d) in [(2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3), (3, 7)]:
        ok = example_check(n, d)
        print("    [%s] n=%d, d=%d: the displayed classes are omega_1, omega_2"
              % ("PASS" if ok else "FAIL", n, d))
        npass += 1 if ok else 0
        nfail += 0 if ok else 1

    print()
    print("  %d checks passed, %d failed" % (npass, nfail))
    print("  overall: %s" % ("PASS" if nfail == 0 else "FAIL"))
