#!/usr/bin/env python3
"""
targets_reduction.py

Item (XLIII) of COMPUTATIONS.md: the finite computations behind the
subsection "The two remaining targets, reduced to the Lefschetz standard
conjecture of one variety each".

Model.  A Mumford fourfold X has H^1(X, C) = V = V_1 (x) V_2 (x) V_3 with
V_i = C^2 carrying the standard representation of SL_2; basis vectors are
indexed by (a, b, c) in {0,1}^3, of weight (1 - 2a, 1 - 2b, 1 - 2c) for the
diagonal torus.  H^1(X x X) = V (+) V, sixteen generators, and
H^*(X x X) = wedge^*(V (+) V).  A monomial of the exterior algebra is a bit
mask.  Everything below is either exact rational arithmetic or a rank computed
modulo the prime p = 1000003 of integer vectors; a rank modulo p is a lower
bound for the rank over Q, and it is used only to show that a set of integer
vectors spans a space whose dimension is known exactly, so no conclusion
depends on the choice of p.

What is checked:

  (a) the invariants of sl_2^3 in wedge^k(V (+) V) have dimensions
      1,0,3,0,8,0,16,0,28,0,16,0,8,0,3,0,1, from weight multiplicities;
      in degree 2 the exact invariants span a 3-dimensional space and in
      degree 4 an 8-dimensional one, of which products of degree-2
      invariants give 6: the two exceptional classes;

  (b) the ring of invariants is generated in degrees 2 and 4: products of
      the exact invariants of degrees 2 and 4 span every degree;

  (c) at a CM point the Hodge group is a maximal torus, the Hodge classes of
      X_c x X_c are the weight-zero monomials, 1,0,16,0,132,0,432,0,648,...;
      and the ring generated by the divisor classes of X_c x X_c and by the
      pull-backs f^*(t), t a Hodge class of X_c and
      f = (phi, psi) : X_c x X_c -> X_c with phi, psi diagonal in the weight
      basis, contains every Hodge class of X_c x X_c; the divisor classes
      alone do not (100 of 132 in degree 4);

  (d) on an abelian 2n-fold of Weil type, n = 1, 2, 3, with
      H^1 = V_+^{1,0} + V_-^{1,0} + V_+^{0,1} + V_-^{0,1} and
      P = V_+^{0,1} (+) T_-, Q = V_-^{0,1} (+) T_+ acting by wedge and
      contraction, the classes of type (p,p) killed by Q ^ HH^1 are the
      multiples of alpha_-, those killed by P ^ HH^1 the multiples of
      alpha_+, and none is killed by HH^1 ^ HH^1.

Run:  python3 targets_reduction.py
"""
from collections import Counter
from fractions import Fraction
from itertools import combinations
import random

PASS, FAIL = [], []
P = 1000003


def check(name, ok, detail=""):
    (PASS if ok else FAIL).append(name)
    print(("  [PASS] " if ok else "  [FAIL] ") + name +
          (("   " + detail) if detail else ""))


# ------------------------------------------------------- exterior algebra

def popcount(m):
    return bin(m).count("1")


def mono_sign(a, b):
    if a & b:
        return 0
    s, bb = 0, b
    while bb:
        j = (bb & -bb).bit_length() - 1
        s += popcount(a >> (j + 1))
        bb &= bb - 1
    return -1 if s % 2 else 1


def wedge(x, y, mod=None):
    out = {}
    for a, ca in x.items():
        for b, cb in y.items():
            s = mono_sign(a, b)
            if s:
                v = out.get(a | b, 0) + s * ca * cb
                out[a | b] = v % mod if mod else v
    return {k: v for k, v in out.items() if v}


NB = 16


def weight(i):
    j = i % 8
    return (1 - 2 * ((j >> 2) & 1), 1 - 2 * ((j >> 1) & 1), 1 - 2 * (j & 1))


WT = [weight(i) for i in range(NB)]


def mweight(m):
    w = [0, 0, 0]
    for i in range(NB):
        if m >> i & 1:
            for t in range(3):
                w[t] += WT[i][t]
    return tuple(w)


def masks(k, nbits):
    return [sum(1 << i for i in c) for c in combinations(range(nbits), k)]


def raise_basis(t, i):
    bit = 2 - t
    return i - (1 << bit) if ((i % 8) >> bit) & 1 else None


def derivation(t, x):
    out = {}
    for m, c in x.items():
        bits = [i for i in range(NB) if m >> i & 1]
        for k, i in enumerate(bits):
            r = raise_basis(t, i)
            if r is None or ((m ^ (1 << i)) >> r & 1):
                continue
            left = sum(1 << b for b in bits[:k])
            right = sum(1 << b for b in bits[k + 1:])
            s = mono_sign(left, 1 << r) * mono_sign(left | (1 << r), right)
            new = left | (1 << r) | right
            out[new] = out.get(new, 0) + s * c
    return {k: v for k, v in out.items() if v}


def invariant_dim(k, nbits=NB):
    cnt = Counter(mweight(m) for m in masks(k, nbits))
    tot = 0
    for e0 in (0, 1):
        for e1 in (0, 1):
            for e2 in (0, 1):
                tot += (-1) ** (e0 + e1 + e2) * cnt.get((2 * e0, 2 * e1, 2 * e2), 0)
    return tot


def exact_invariants(k):
    """a Q-basis of the sl_2^3-invariants of wedge^k(V+V), as integer vectors"""
    ws = [m for m in masks(k, NB) if mweight(m) == (0, 0, 0)]
    rows = {}
    for j, m in enumerate(ws):
        for t in range(3):
            for mm, c in derivation(t, {m: 1}).items():
                rows.setdefault((t, mm), {})[j] = Fraction(c)
    # reduced row echelon form over Q
    piv = {}
    for r in rows.values():
        r = dict(r)
        for c in sorted(piv):
            if c in r:
                f = r[c]
                for kk, cc in piv[c].items():
                    r[kk] = r.get(kk, 0) - f * cc
                    if r[kk] == 0:
                        del r[kk]
        if not r:
            continue
        c0 = min(r)
        inv = 1 / r[c0]
        r = {kk: cc * inv for kk, cc in r.items()}
        for c in piv:
            if c0 in piv[c]:
                f = piv[c][c0]
                for kk, cc in r.items():
                    piv[c][kk] = piv[c].get(kk, 0) - f * cc
                    if piv[c][kk] == 0:
                        del piv[c][kk]
        piv[c0] = r
    free = [j for j in range(len(ws)) if j not in piv]
    out = []
    for fj in free:
        v = {fj: Fraction(1)}
        for c, r in piv.items():
            if fj in r:
                v[c] = -r[fj]
        den = 1
        for x in v.values():
            den = den * x.denominator // _gcd(den, x.denominator)
        out.append({ws[j]: int(x * den) for j, x in v.items()})
    return out


def _gcd(a, b):
    while b:
        a, b = b, a % b
    return a


class ModSpan:
    """a growing echelon basis modulo P"""

    def __init__(self):
        self.piv = {}

    def add(self, v):
        v = {k: c % P for k, c in v.items() if c % P}
        while v:
            p = max(v)
            if p in self.piv:
                b = self.piv[p]
                f = v[p] * pow(b[p], P - 2, P) % P
                for k, c in b.items():
                    nv = (v.get(k, 0) - f * c) % P
                    if nv:
                        v[k] = nv
                    else:
                        v.pop(k, None)
            else:
                self.piv[p] = v
                return True
        return False

    def __len__(self):
        return len(self.piv)


# ------------------------------------------------ (a), (b) generic X x X

def run_generic():
    dims = [invariant_dim(k) for k in range(17)]
    check("the invariants of sl_2^3 in wedge^k(V+V) have dimensions "
          "1,0,3,0,8,0,16,0,28,0,16,0,8,0,3,0,1",
          dims == [1, 0, 3, 0, 8, 0, 16, 0, 28, 0, 16, 0, 8, 0, 3, 0, 1],
          "computed: %s" % dims)
    I2 = exact_invariants(2)
    I4 = exact_invariants(4)
    ok = all(not derivation(t, v) for v in I2 + I4 for t in range(3))
    check("exact invariants in degrees 2 and 4 are killed by the three "
          "raising operators", ok and len(I2) == 3 and len(I4) == 8,
          "%d and %d of them" % (len(I2), len(I4)))
    prod = ModSpan()
    for a in I2:
        for b in I2:
            prod.add(wedge(a, b, P))
    check("products of divisor classes give 6 of the 8 classes in degree 4: "
          "two are exceptional", len(prod) == 6)
    span = {0: [{0: 1}]}
    ok = True
    got = []
    for k in range(2, 17, 2):
        S = ModSpan()
        basis = []
        for d, G in ((2, I2), (4, I4)):
            if k - d not in span:
                continue
            for a in span[k - d]:
                for g in G:
                    v = wedge(a, g, P)
                    if S.add(v):
                        basis.append(v)
        span[k] = basis
        got.append(len(basis))
        ok = ok and len(basis) == dims[k]
    check("the invariant ring is generated by the invariants of degrees 2 "
          "and 4", ok, "ranks by degree: %s" % got)
    return I2, I4


# ------------------------------------------------ (c) a CM point

def pullback(phi, psi, x):
    out = {}
    for m, c in x.items():
        img = {0: c % P}
        for i in range(8):
            if m >> i & 1:
                img = wedge(img, {1 << i: phi[i] % P,
                                  1 << (i + 8): psi[i] % P}, P)
        for k, v in img.items():
            out[k] = (out.get(k, 0) + v) % P
    return {k: v for k, v in out.items() if v}


def run_cm():
    TX = {k: [m for m in masks(k, 8) if mweight(m) == (0, 0, 0)]
          for k in range(9)}
    TXX = {k: [m for m in masks(k, NB) if mweight(m) == (0, 0, 0)]
           for k in range(17)}
    hx = [len(TX[k]) for k in range(9)]
    hxx = [len(TXX[k]) for k in range(17)]
    check("at a CM point the Hodge classes of X_c are 1,0,4,0,8,0,4,0,1 and "
          "those of X_c x X_c are 1,0,16,0,132,0,432,0,648,...",
          hx == [1, 0, 4, 0, 8, 0, 4, 0, 1]
          and hxx == [1, 0, 16, 0, 132, 0, 432, 0, 648, 0, 432, 0, 132, 0,
                      16, 0, 1])
    div = [{m: 1} for m in TXX[2]]
    D4 = ModSpan()
    for i in range(len(div)):
        for j in range(i, len(div)):
            D4.add(wedge(div[i], div[j], P))
    check("the divisor classes of X_c x X_c span only 100 of the 132 Hodge "
          "classes of degree 4", len(D4) == 100)
    random.seed(20260924)
    gens = {2: div}
    for k in (4, 6):
        gens[k] = []
        for _ in range(80):
            phi = [random.randint(-60, 60) for _ in range(8)]
            psi = [random.randint(-60, 60) for _ in range(8)]
            for m in TX[k]:
                gens[k].append(pullback(phi, psi, {m: 1}))
    span = {0: [{0: 1}]}
    got, ok = [], True
    for k in range(2, 17, 2):
        S = ModSpan()
        basis = []
        for d, G in gens.items():
            if k - d not in span:
                continue
            for a in span[k - d]:
                for g in G:
                    if len(basis) == len(TXX[k]):
                        break
                    v = wedge(a, g, P)
                    if S.add(v):
                        basis.append(v)
        span[k] = basis
        got.append(len(basis))
        ok = ok and len(basis) == len(TXX[k])
    check("the ring generated by the divisor classes and the pull-backs of "
          "Hodge classes of X_c contains every Hodge class of X_c x X_c", ok,
          "ranks by degree: %s" % got)


# ------------------------------------------------ (d) two branches

def run_two_branches():
    ok = True
    for n in (1, 2, 3):
        A = list(range(0, n))
        B = list(range(n, 2 * n))
        C = list(range(2 * n, 3 * n))
        D = list(range(3 * n, 4 * n))
        nb = 4 * n

        def wop(i):
            return lambda m: None if m >> i & 1 else m | (1 << i)

        def cop(i):
            return lambda m: m ^ (1 << i) if m >> i & 1 else None

        Pg = [wop(i) for i in C] + [cop(i) for i in B]
        Qg = [wop(i) for i in D] + [cop(i) for i in A]
        H1 = Pg + Qg

        def killed(m, left):
            for q in left:
                for w in H1:
                    x = w(m)
                    if x is not None and q(x) is not None:
                        return False
            return True

        def pp(m):
            hol = sum(1 for i in A + B if m >> i & 1)
            return hol == popcount(m) - hol

        aQ = [m for m in range(1 << nb) if pp(m) and killed(m, Qg)]
        aP = [m for m in range(1 << nb) if pp(m) and killed(m, Pg)]
        aH = [m for m in range(1 << nb) if pp(m) and killed(m, H1)]
        am = sum(1 << i for i in B + D)
        ap = sum(1 << i for i in A + C)
        ok = ok and aQ == [am] and aP == [ap] and aH == []
        print("         n=%d  (p,p) part of Ann(Q^HH^1): %s  of Ann(P^HH^1): %s"
              "  of Ann(HH^2): %s" % (n, "alpha_-" if aQ == [am] else aQ,
                                      "alpha_+" if aP == [ap] else aP,
                                      aH if aH else "0"))
    check("the classes of type (p,p) killed by Q^HH^1, by P^HH^1 and by "
          "HH^1^HH^1 are C alpha_-, C alpha_+ and 0", ok,
          "n = 1, 2, 3; the operators map monomials to monomials injectively, "
          "so the annihilators are spanned by monomials")


if __name__ == "__main__":
    print("(XLIII) the two remaining targets, reduced")
    run_generic()
    run_cm()
    run_two_branches()
    print()
    print("  %d checks passed, %d failed" % (len(PASS), len(FAIL)))
    raise SystemExit(0 if not FAIL else 1)
