-- local_germs.m2
--
-- Item (LXVIII), local part: the Yoneda squares a_k a_l of the jet classes of a
-- germ M at the origin of C^4, for the constant vector fields d/dx_k.
--
-- For a graded module M over R = Q[x1,x2,x3,x4] with minimal free resolution
-- P, the jet class of the derivation D = d/dx_k is represented by the chain
-- map of degree -1 with components -D(d_i) (entrywise derivative of the
-- differential), and the Yoneda product a_k a_l in Ext^2(M,M) is the class
-- of the cocycle  eps . (-D_k d_1) . (-D_l d_2) : P_2 -> P_1 -> P_0 -> M.
-- Writing C for the r_0 x r_2 matrix (-D_k d_1)(-D_l d_2), the class
-- vanishes if and only if C = G d_2 modulo the relations of M, column by
-- column, for some r_0 x r_1 matrix G over R.  This is a membership test in
-- the submodule of R^{r_0 r_2} generated by the flattenings of E_{ab} d_2 and
-- of the relations of M placed in each column.  Everything is homogeneous,
-- so the graded computation over the polynomial ring is the local
-- computation at the origin.
--
-- The germs:
--   (i)    R/(x1,x2,x3)                a line bundle on a smooth curve
--   (ii)   R/(x1,x2,x3,x4)             a skyscraper
--   (iii)  (x2,x3) R/(x1)              ideal of a smooth curve in a smooth divisor
--   (iv)   (x2,x3,x4) R/(x1)           ideal of a point in a smooth divisor
--   (v)    R/(x1)                      a smooth divisor
--   (vi)   (x1,x2) cap (x3,x4)         two transversal planes (Lemma, two branches)
--   (vii)  (x1,x3) R/(x1x2-x3x4)       a rank one maximal Cohen-Macaulay module on a node
--   (viii) ker(R/(x1) + R/(x2,x3,x4) -> k)   the glued germ of Example 11.2.7 at a gluing point
--   (ix)   (x1^2,x1x3,x3^2) R/(x1x2-x3x4)    a reflexive non-Cohen-Macaulay module on a node
--   (x)    R^2/(x1,x2,x3)              a rank two bundle on a smooth curve
--
-- Output: for each germ, the projective dimension, and the pairs (k,l) with
-- a_k a_l != 0.

R = QQ[x1,x2,x3,x4];
vars4 = {x1,x2,x3,x4};

flatCols = (C) -> (
    -- flatten an r0 x r2 matrix column-major into a column vector of R^{r0 r2}
    r0 := numrows C; r2 := numcols C;
    matrix table(r0*r2, 1, (i,j) -> C_(i % r0, i // r0))
);

yonedaSquares = (M0) -> (
    pres := presentation M0;
    M := coker pres;
    P := res(M, LengthLimit => 5);
    pd := length P;
    result := {};
    if pd >= 2 then (
        d1 := P.dd_1;   -- P_1 -> P_0
        d2 := P.dd_2;   -- P_2 -> P_1
        r0 := numrows d1; r1 := numcols d1; r2 := numcols d2;
        -- generators of the coboundary submodule of R^{r0 r2}
        cols := {};
        for a from 0 to r0-1 do for b from 0 to r1-1 do (
            E := map(R^r0, R^r1, (i,j) -> if i == a and j == b then 1_R else 0_R);
            cols = append(cols, flatCols(E * d2));
        );
        for c from 0 to r2-1 do for s from 0 to r1-1 do (
            rel := d1_{s};    -- a relation, column of d1, in R^{r0}
            V := map(R^(r0*r2), R^1, (i,j) -> if i // r0 == c then rel_(i % r0, 0) else 0_R);
            cols = append(cols, V);
        );
        B := image fold(cols, (u,v) -> u | v);
        for k from 0 to 3 do for l from 0 to 3 do (
            jk := - diff(vars4#k, d1);
            jl := - diff(vars4#l, d2);
            C := jk * jl;
            v := flatCols C;
            if (v % B) != 0 then result = append(result, (k+1, l+1));
        );
    );
    (pd, result)
);

report = (name, M) -> (
    (pd, sq) := yonedaSquares M;
    << name << ": pd = " << pd << ", nonzero squares a_k a_l at (k,l): " << sq << endl;
    sq
);

allpairs = (S) -> sort flatten for k in S list for l in S list if k != l then (k,l) else continue;

-- (i) line bundle on a smooth curve
sqi = report("(i)    R/(x1,x2,x3)", R^1/ideal(x1,x2,x3));
<< "       expected wedge^2 of the normal directions {1,2,3}: " << (sort sqi == allpairs {1,2,3}) << endl;

-- (ii) skyscraper
sqii = report("(ii)   R/(x1,..,x4)", R^1/ideal(x1,x2,x3,x4));
<< "       expected all pairs: " << (sort sqii == allpairs {1,2,3,4}) << endl;

-- (iii) ideal of a smooth curve in a smooth divisor
sqiii = report("(iii)  (x2,x3) R/(x1)", subquotient(matrix{{x2,x3}}, matrix{{x1}}));
<< "       expected exactly the pairs {1} x {2,3} and {2,3} x {1}: " << (sort sqiii == sort {(1,2),(1,3),(2,1),(3,1)}) << endl;

-- (iv) ideal of a point in a smooth divisor
sqiv = report("(iv)   (x2,x3,x4) R/(x1)", subquotient(matrix{{x2,x3,x4}}, matrix{{x1}}));
<< "       contains the transverse pairs {1} x {2,3,4} and {2,3,4} x {1}: " << (isSubset({(1,2),(1,3),(1,4),(2,1),(3,1),(4,1)}, sqiv)) << endl;

-- (v) smooth divisor
sqv = report("(v)    R/(x1)", R^1/ideal(x1));
<< "       expected none: " << (sqv == {}) << endl;

-- (vi) two transversal planes
sqvi = report("(vi)   (x1,x2) cap (x3,x4)", module intersect(ideal(x1,x2), ideal(x3,x4)));
<< "       expected N_1 tensor N_2 only: " << (sort sqvi == sort {(1,3),(1,4),(2,3),(2,4),(3,1),(4,1),(3,2),(4,2)}) << endl;

-- (vii) maximal Cohen-Macaulay rank one module on the node
sqvii = report("(vii)  (x1,x3) R/(x1x2-x3x4)", subquotient(matrix{{x1,x3}}, matrix{{x1*x2-x3*x4}}));
<< "       expected none (projective dimension one): " << (sqvii == {}) << endl;

-- (viii) the glued germ {(f,g) in R/(x1) + R/(x2,x3,x4) : f(0) = g(0)}
rels = matrix{{x1,0,0,0},{0,x2,x3,x4}};
gens8 = matrix{{1,x2,x3,x4,0},{1,0,0,0,x1}};
sqviii = report("(viii) glued germ ker(R/(x1) + R/(x2,x3,x4) -> k)", subquotient(gens8, rels));
<< "       contains the pairs normal to the curve, {2,3,4}: " << (isSubset(allpairs {2,3,4}, sqviii)) << endl;

-- (ix) reflexive non-Cohen-Macaulay module on the node
sqix = report("(ix)   (x1^2,x1x3,x3^2) R/(x1x2-x3x4)", subquotient(matrix{{x1^2,x1*x3,x3^2}}, matrix{{x1*x2-x3*x4}}));

-- (x) rank two bundle on a smooth curve
sqx = report("(x)    R^2/(x1,x2,x3)", R^2/ideal(x1,x2,x3));
<< "       expected wedge^2 of the normal directions {1,2,3}: " << (sort sqx == allpairs {1,2,3}) << endl;

-- (ix) is reflexive: the square of the ideal of a ruling on the node has the
-- ruling as its only associated prime, equals its saturation by an element
-- off the ruling, and is isomorphic to its double dual.
Rn = QQ[x1,x2,x3,x4]/(x1*x2-x3*x4);
Pn = ideal(x1,x3);
P2n = Pn^2;
<< "(ix)   associated primes of the square of the ruling ideal: " << associatedPrimes P2n << endl;
<< "       equal to its saturation by x2: " << (saturate(P2n, ideal(x2)) == P2n) << endl;
<< "       isomorphic to its double dual: " << (isIsomorphic(module P2n, Hom(Hom(module P2n, Rn^1), Rn^1)))#0 << endl;
