"""v4_subvar.py -- independent check of T3 claim 1 (abelian subvarieties Z_{p:q})."""
import sys, time
sys.dont_write_bytecode = True
from fractions import Fraction as F
from math import factorial, comb, gcd
from functools import reduce
from itertools import combinations
from sympy import Matrix, ilcm
from sympy.matrices.normalforms import hermite_normal_form
from ea import *
from model import Model

t0 = time.time()


def Zwedge(M, p, q):
    """wedge_i (q x_i + p B x_i): pulled-back point class of A/Z, Z = kernel."""
    w = one()
    for i in range(M.m):
        w = mul(w, add(g(M.x(i), F(q)), sc(F(p), M.Bx(i))))
    return w


def Dclass(M, p, q):
    return add(sc(F(q * q), M.beta()), sc(F(-p * q), M.ell()), sc(F(p * p), M.betahat()))


def track_weil(M):
    n, d = M.n, M.d
    gam = add(sc(F(d), M.beta()), sc(F(-1), M.betahat()))
    l = M.ell()
    re, im = {}, {}
    for k in range(n + 1):
        term = sc(F(comb(n, k)), mul(power(gam, n - k), power(l, k)))
        if k % 2 == 0:
            re = add(re, sc(F((-d) ** (k // 2)), term))
        else:
            im = add(im, sc(F(-((-d) ** ((k - 1) // 2))), term))
    return re, im


def slopes(maxc):
    out = []
    for p in range(-maxc, maxc + 1):
        for q in range(0, maxc + 1):
            if gcd(p, q) != 1:
                continue
            if q == 0 and p != 1:
                continue
            out.append((p, q))
    return out


for n, d in [(2, 1), (2, 2), (2, 3), (3, 1)]:
    M = Model(n, d)
    om1, om2 = track_weil(M)
    myre, myim = M.weil_pm()
    eta = M.eta()
    # [Z] = +- D^n/n!, integral, type (n,n), [Z]^2 = 0
    sl = slopes(4)
    Z = {}
    okZ = True
    for (p, q) in sl:
        z = sc(F(1, factorial(n)), power(Dclass(M, p, q), n))
        zw = Zwedge(M, p, q)
        okZ &= (z == zw or z == sc(F(-1), zw))
        okZ &= all(c.denominator == 1 for c in z.values())
        okZ &= not mul(z, z)
        okZ &= M.integral(mul(z, power(eta, n))) > 0
        Z[(p, q)] = z
    okT = all(M.is_type(M.cx(Z[s]), n) for s in [(0, 1), (1, 0), (1, 1), (-1, 1), (2, 3)])
    # intersection numbers
    okI = all(M.integral(mul(Z[s], Z[t])) == (s[0] * t[1] - s[1] * t[0]) ** (2 * n)
              for s, t in [((0, 1), (1, 0)), ((1, 1), (-1, 1)), ((1, 2), (2, 1)), ((-1, 3), (-2, 1)), ((3, 4), (1, 1))])
    Zs = list(Z.values())
    rk = rank(Zs)
    in1 = solve(om1, Zs) is not None and solve(om2, Zs) is not None
    inE = solve(power(eta, n), Zs) is not None
    print("n=%d d=%d: %d slopes; [Z]=+-wedge=D^n/n! integral, [Z]^2=0, deg>0: %s; type(n,n): %s; int Z_s Z_t = det^{2n}: %s; "
          "rank span = %d (2n+1=%d); Weil plane in span: %s; eta^n in span: %s  (%.1fs)"
          % (n, d, len(sl), okZ, okT, okI, rk, 2 * n + 1, in1, inE, time.time() - t0), flush=True)
    # least N with N*omega1 (track normalisation) in Z-span; project to coordinates where rank is full
    keys = sorted({k for z in Zs for k in z})
    chosen = []
    cur = []
    for k in keys:
        test = cur + [k]
        mat = Matrix([[z.get(kk, 0) for kk in test] for z in Zs])
        if mat.rank() == len(test):
            cur = test
        if len(cur) == 2 * n + 1:
            break
    A = Matrix([[int(z.get(k, 0)) for k in cur] for z in Zs])   # rows generate L'
    H = hermite_normal_form(A.T).T      # rows of H: a basis of the row lattice?  (use columns HNF of A^T)
    # H's nonzero rows form a Z-basis of the lattice generated by rows of A
    Hrows = [H.row(i) for i in range(H.rows) if any(H.row(i))]
    B = Matrix.vstack(*Hrows)
    for name, w in [("omega1(track)", om1), ("omega2(track)", om2), ("Re omega_+ (paper norm.)", myre)]:
        target = Matrix([[w.get(k, 0) for k in cur]])
        # solve x B = target
        x = B.T.solve(target.T)
        den = reduce(ilcm, [F(str(v)).denominator for v in x], 1)
        print("    least N with N*%s in Z-span of the [Z]'s (|p|,|q|<=4): %s" % (name, den), flush=True)
    if n == 2 and d == 1:
        c = add(sc(F(4), Z[(0, 1)]), sc(F(4), Z[(1, 0)]), sc(F(-1), Z[(1, 1)]), sc(F(-1), Z[(-1, 1)]))
        print("    4[0xX^]+4[Xx0]-[Z_1:1]-[Z_1:-1] == omega1(track): %s ; == -omega1(track): %s ; paper omega1 = d l^2 - gamma^2 = -omega1(track)"
              % (c == om1, c == sc(F(-1), om1)))
    if n == 2 and d == 2:
        c = add(sc(F(12), Z[(0, 1)]), sc(F(6), Z[(1, 0)]), sc(F(-2), Z[(1, 1)]), sc(F(-2), Z[(-1, 1)]))
        print("    12[Z_0:1]+6[Z_1:0]-2[Z_1:1]-2[Z_1:-1] == omega1(track): %s" % (c == om1))
    # T cap Ann[Z]
    T = M.tangent()
    dims = []
    for s in [(0, 1), (1, 1), (1, 2)]:
        zc = M.cx(Z[s])
        dims.append(len(T) - rank([M.Dv(v, zc) for v in T]))
    print("    dim T = %d, dim T cap Ann[Z] for 3 slopes = %s (n(n+1)/2 = %d)" % (len(T), dims, n * (n + 1) // 2), flush=True)
    if n == 2 and d == 1:
        imgs = []
        per = []
        for s in [(0, 1), (1, 0), (1, 1), (-1, 1)]:
            im_s = M.htk_images(M.cx(Z[s]), 2)
            per.append(rank(im_s))
            imgs += im_s
        print("    rank HT^2 _| [Z] per slope: %s ; rank of sum over 4 slopes: %d ; r(omega1) = %d" % (per, rank(imgs), M.r(om1)), flush=True)
