#!/usr/bin/env python3
"""
t4_basic.py -- n = 4, A = X x Xhat.  Exact checks of the Hodge ring H_A generated
by beta, betahat, ell, of the Weil classes, and of the classes of the abelian
subvarieties B_(p,q) = {(p x, q phi(x))}.

  (B1) dims of H_A in each degree (subring generated by beta, betahat, ell)
  (B2) W1, W2 (thm:splitclosed) are primitive: eta ^ W = 0, and independent
  (B3) [B_(1,0)] = betahat^4/4!, [B_(0,1)] = beta^4/4!, int [B]^2 = 0 etc.
  (B4) [B_(p,q)] = sum_k p^k q^(8-k) C_k with C_k in H_A (degree 8),
       and Re / Im of sum_k C_k z^k at z = the K-point equal W1, W2 up to scalar
  (B5) the span of the C_k is 9-dimensional and contains W; eta^4 is not in it
"""
import sys, time
from fractions import Fraction as Fr
from ext import *

n = 4
d = int(sys.argv[1]) if len(sys.argv) > 1 else 1
S = Split(n, d)
b, bh, l, eta = S.beta(), S.betahat(), S.ell(), S.eta()
t0 = time.time()

# (B1) H_A
pb = [power(b, k) for k in range(n + 1)]
pbh = [power(bh, k) for k in range(n + 1)]
pl = [power(l, k) for k in range(2 * n + 1)]
HA = {}
for k in range(0, 2 * n + 1):
    vecs = []
    for a in range(0, min(k, n) + 1):
        for bb in range(0, min(k - a, n) + 1):
            c = k - a - bb
            if c > 2 * n:
                continue
            vecs.append(wedge(wedge(pb[a], pbh[bb]), pl[c]))
    E = Echelon()
    for v in vecs:
        E.add(v)
    HA[k] = E
dims = [HA[k].rank() for k in range(2 * n + 1)]
print("(B1) dim H_A in H^{2k}, k=0..8:", dims, " total", sum(dims))

# (B2) Weil classes
W1, W2 = S.weil_pair()
print("(B2) eta^W1 = 0:", not wedge(eta, W1), " eta^W2 = 0:", not wedge(eta, W2))
E8 = HA[4]
print("     W1, W2 in H_A:", not E8.reduce(W1), not E8.reduce(W2))
print("     W1, W2, eta^4 independent:", rank_of([W1, W2, power(eta, 4)]) == 3)
print("     int W1^2 =", S.integral(wedge(W1, W1)), " int W2^2 =",
      S.integral(wedge(W2, W2)), " int W1 W2 =", S.integral(wedge(W1, W2)),
      " int eta^8 =", S.integral(power(eta, 8)))

# (B3) subtori
B10 = S.subtorus(1, 0)
B01 = S.subtorus(0, 1)
print("(B3) [B_(1,0)] = betahat^4/24:", add(B10, pbh[4], 24, -1) == {},
      "  [B_(0,1)] = beta^4/24:", add(B01, pb[4], 24, -1) == {})
for (p, q) in [(1, 1), (1, -1), (2, 1), (1, 2), (3, -2)]:
    Bpq = S.subtorus(p, q)
    inHA = not E8.reduce(Bpq)
    selfint = S.integral(wedge(Bpq, Bpq))
    meet = S.integral(wedge(Bpq, B10))
    print("     B_(%d,%d): in H_A %s, int [B]^2 = %d, int [B][B_(1,0)] = %d"
          " (expect q^8 = %d)" % (p, q, inHA, selfint, meet, q ** 8))

# (B4) the coefficient classes C_k: [B_(p,q)] = sum_k p^k q^(8-k) C_k.
# Recover C_k by interpolation over q = 1 and 9 values of p (Vandermonde).
ps = list(range(-4, 5))
vals = []
for p in ps:
    # B_(p,1) always has gcd 1
    vals.append(S.subtorus(p, 1))
# solve sum_k p^k C_k = vals[p]  (9 x 9 Vandermonde, exact)
import itertools
V = [[Fr(p) ** k for k in range(9)] for p in ps]
# invert V
def inv(M):
    m = len(M)
    A = [row[:] + [Fr(int(i == j)) for j in range(m)] for i, row in enumerate(M)]
    for c in range(m):
        piv = next(r for r in range(c, m) if A[r][c] != 0)
        A[c], A[piv] = A[piv], A[c]
        pv = A[c][c]
        A[c] = [x / pv for x in A[c]]
        for r in range(m):
            if r != c and A[r][c] != 0:
                f = A[r][c]
                A[r] = [x - f * y for x, y in zip(A[r], A[c])]
    return [row[m:] for row in A]
Vi = inv(V)
C = []
for k in range(9):
    acc = {}
    for i in range(9):
        if Vi[k][i] != 0:
            acc = add(acc, vals[i], 1, Vi[k][i])
    C.append(acc)
# check: sign convention of subtorus() may flip; check B_(p,1) reproduced and
# that the polynomial also reproduces B_(p,q) for q != 1 up to sign
ok = True
for (p, q) in [(1, 2), (3, 2), (-2, 3), (1, 0), (0, 1)]:
    poly = {}
    for k in range(9):
        poly = add(poly, C[k], 1, Fr(p) ** k * Fr(q) ** (8 - k))
    Bpq = S.subtorus(p, q)
    same = add(poly, Bpq, 1, -1) == {}
    ok = ok and same
print("(B4) [B_(p,q)] = sum_k p^k q^(8-k) C_k for test points:", ok)
print("     rank of C_0..C_8:", rank_of(C))
# Weil classes as values at the K-point: z = p/q with (p:q) = (1 : -delta)
# P(1, t) = sum_k C_k t^(8-k); at t = -delta: t^m = (-delta)^m
# real part: sum over m even of (-1)^m (-d)^(m/2) C_{8-m}; imaginary/delta: m odd
Re, Im = {}, {}
for m in range(9):
    c = (-1) ** m * (-d) ** (m // 2)
    if m % 2 == 0:
        Re = add(Re, C[8 - m], 1, c)
    else:
        Im = add(Im, C[8 - m], 1, c)
def proportional(u, v):
    if not u or not v:
        return False
    k0 = next(iter(u))
    if k0 not in v:
        return False
    r = Fr(u[k0]) / Fr(v[k0])
    return add(u, v, 1, -r) == {}, r
print("     Re P(1,-delta) prop. to W1, Im/delta prop. to W2:",
      proportional(Re, W1), proportional(Im, W2))

# (B5)
Esub = Echelon()
for c in C:
    Esub.add(c)
print("(B5) W1, W2 in span C_k:", not Esub.reduce(W1), not Esub.reduce(W2),
      "  eta^4 in span C_k:", not Esub.reduce(power(eta, 4)))
print("     degree-8 part of H_A has dim", HA[4].rank(),
      "; span of subtori classes has dim", Esub.rank())
print("time %.1fs" % (time.time() - t0))
