"""zsigma.py -- E = O_{0xX^}^4 + O_{Xx0}^4 + O_{G+}[odd] + O_{G-}[odd] (disjoint translates,
shifts 0,2,5,7) represents w1 at n = 2, d = 1.  Ext^1 = 40, Ext^2 = 60 (no cross terms);
sigma_E on each block is contraction HT^2 -> H^* into [Z] (the Ext algebra of O_Z is
generated by ev(HT^1)), so rank sigma_E = dim of the sum of the four images."""
import sys
sys.dont_write_bytecode = True
from fractions import Fraction as Fr
from split import Split
from subvar import Zclass
from ext import *
S = Split(2, 1)
w1, w2 = S.weil()
Z = {s: Zclass(S, *s) for s in [(0, 1), (1, 0), (1, 1), (1, -1)]}
comb = eadd(escale(Fr(4), Z[(0, 1)]), escale(Fr(4), Z[(1, 0)]), escale(Fr(-1), Z[(1, 1)]), escale(Fr(-1), Z[(1, -1)]))
print("4[Z_0:1] + 4[Z_1:0] - [Z_1:1] - [Z_1:-1] == w1 :", comb == w1)
imgs = []
per = []
for s, z in Z.items():
    im, _ = S.ht2_images(S.to_complex(z))
    per.append(rank_and_kernel(im))
    imgs += im
tot = rank_and_kernel(imgs)
print("rank HT^2 _| [Z] per slope:", per, "; rank of the sum of the four images:", tot)
print("Ext^2(E,E) = 10 * 6 = 60, rank sigma_E = %d, dim ker sigma_E = %d; Ext^1 = 40; r(w1) = %d" % (tot, 60 - tot, S.r_of(w1)))
